local Utils = require("VVR/Utils")

Utils.AddZombieType("49powerWagonPA", "Survivalist_Late;Survivalist_Mid;Survivalist02_Late;Survivalist02_Mid;Survivalist03_Late;Survivalist03_Mid;Survivalist04_Late;Survivalist04_Mid;Survivalist05_Late;Survivalist05_Mid;Bandit_Late;Bandit_Mid")
Utils.AddZombieType("49powerWagonPD", "Police")
Utils.AddZombieType("49powerWagonMP", "ArmyServiceUniform")

Utils.AddZombieType("59ambulance", "AmbulanceDriver")

Utils.AddZombieType("63Type2VanApocalypse", "Survivalist_Late;Survivalist_Mid;Survivalist02_Late;Survivalist02_Mid;Survivalist03_Late;Survivalist03_Mid;Survivalist04_Late;Survivalist04_Mid;Survivalist05_Late;Survivalist05_Mid;Bandit_Late;Bandit_Mid")
Utils.AddZombieType("63Type2VanMilitary", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("63Type2VanHippie", "Young;YoungCowpoke;Hobbyist;Party")

Utils.AddZombieType("67commandoPolice", "Police_SWAT;PoliceRiot")
Utils.AddZombieType("67commando", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("67commandoT50", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("70dodgePD", "Police")

Utils.AddZombieType("76chevyK10fd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("76chevyK20fd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("76chevyK30CCfd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("76chevyC30CCwrecker", "Trucker")
Utils.AddZombieType("76chevyC30SCwrecker", "Trucker")

Utils.AddZombieType("78amgeneralM35A2", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("78amgeneralM49A2C", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("78amgeneralM50A3", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("78amgeneralM62", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("80manKat1", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("81deloreanDMC12BTTF", "MadScientist")

Utils.AddZombieType("82jeepJ10pd", "Police")
Utils.AddZombieType("82jeepJ10ranger", "Ranger")

Utils.AddZombieType("83amgeneralM923", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("84jeepXJksp", "PoliceState")
Utils.AddZombieType("84jeepXJpd", "Police")
Utils.AddZombieType("84jeepXJranger", "Ranger")

Utils.AddZombieType("84mercLWB4M", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("85chevyImpalaSedanAirport", "AirportSecurityTarmac;AirportWorkerTarmac")
Utils.AddZombieType("85chevyImpalaSedanBCS", "Sheriff_Deputy")
Utils.AddZombieType("85chevyImpalaSedanCLPD", "Police")
Utils.AddZombieType("85chevyImpalaSedanFD", "Fireman")
Utils.AddZombieType("85chevyImpalaSedanKSP", "PoliceState")
Utils.AddZombieType("85chevyImpalaSedanLCPD", "Police")
Utils.AddZombieType("85chevyImpalaSedanMCS", "Sheriff_Deputy")
Utils.AddZombieType("85chevyImpalaSedanMPD", "Police")
Utils.AddZombieType("85chevyImpalaSedanPD", "Police")
Utils.AddZombieType("85chevyImpalaSedanPDu", "Detective")
Utils.AddZombieType("85chevyImpalaSedanPrison", "PrisonGuard")
Utils.AddZombieType("85chevyImpalaSedanRanger", "Ranger")
Utils.AddZombieType("85chevyImpalaSedanTaxi", "Generic01;Generic02;Generic03;Generic04;Generic05")
Utils.AddZombieType("85chevyImpalaSedanWPPD", "Police")

Utils.AddZombieType("85chevyStepVanSWAT", "Police_SWAT;PoliceRiot")

Utils.AddZombieType("85chevyStepVanLibrary", "Generic01;Generic02;Generic03;Generic04;Generic05")
Utils.AddZombieType("85chevyStepVanPropane", "Trucker")
Utils.AddZombieType("85chevyStepVanSeHospitality", "Chef")
Utils.AddZombieType("85chevyStepVanDelirosPlonkies", "Trucker")
Utils.AddZombieType("85chevyStepVanTheCompleteRepair", "Mechanic")
Utils.AddZombieType("85chevyStepVanSePaintingServices", "Trucker")
Utils.AddZombieType("85chevyStepVanLvAirportCatering", "AirportWorkerTarmac")
Utils.AddZombieType("85chevyStepVanPostal", "Postal")
Utils.AddZombieType("85chevyStepVanUsLogistics", "Trucker")
Utils.AddZombieType("85chevyStepVanMarineBites", "Trucker")
Utils.AddZombieType("85chevyStepVanRandys", "Farmer")
Utils.AddZombieType("85chevyStepVanLvMotorshop", "Mechanic")
Utils.AddZombieType("85chevyStepVanGenuine", "Trucker")
Utils.AddZombieType("85chevyStepVanHerald", "Trucker")
Utils.AddZombieType("85chevyStepVanScarletOak", "Trucker")
Utils.AddZombieType("85chevyStepVanJorgensen", "ConstructionWorker")
Utils.AddZombieType("85chevyStepVanZippeeMarket", "Trucker")
Utils.AddZombieType("85chevyStepVanCitrusWave", "Trucker")
Utils.AddZombieType("85chevyStepVanMrHuangsLaundry", "Trucker")
Utils.AddZombieType("85chevyStepVanSunBallz", "Trucker")

Utils.AddZombieType("86chevyK5ksp", "PoliceState")
Utils.AddZombieType("86chevyK5pd", "Police")
Utils.AddZombieType("86chevyM1008", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86chevyM1009", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86chevyM1009mp", "ArmyServiceUniform")
Utils.AddZombieType("86chevyM1010", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86chevyM1028", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86chevyM1031", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("86fordE150pd", "Bandit_Early")
Utils.AddZombieType("86chevyK5ksp", "PoliceState")
Utils.AddZombieType("86fordE150mccoy", "McCoys")
Utils.AddZombieType("86fordE150med", "Doctor;Nurse;Pharmacist")
Utils.AddZombieType("86fordE150slideSpiffo", "Spiffo")
Utils.AddZombieType("86fordE150so", "Sheriff_Deputy")

Utils.AddZombieType("86fordE150LVairportShuttle", "Generic01;Generic02;Generic03;Generic04;Generic05;Tourist")
Utils.AddZombieType("86fordE150beckmansBuilding", "ConstructionWorker")
Utils.AddZombieType("86fordE150blacksmith", "MetalWorker")
Utils.AddZombieType("86fordE150brewster", "Mechanic")
Utils.AddZombieType("86fordE150bugWipers", "ExterminatorSuited")
Utils.AddZombieType("86fordE150tasteTheBrew", "Trucker")
Utils.AddZombieType("86fordE150ccconstruction", "ConstructionWorker")
Utils.AddZombieType("86fordE150brushAndClay", "Trucker")
Utils.AddZombieType("86fordE150deerValley", "ConstructionWorker")
Utils.AddZombieType("86fordE150theGardenGods", "Farmer")
Utils.AddZombieType("86fordE150zenith", "Trucker")
Utils.AddZombieType("86fordE150greenes", "Trucker")
Utils.AddZombieType("86fordE150heritageTailors", "Trucker")
Utils.AddZombieType("86fordE150McCoyWoodworking", "ConstructionWorker")
Utils.AddZombieType("86fordE150jones", "MetalWorker")
Utils.AddZombieType("86fordE150kerrHomes", "ConstructionWorker")
Utils.AddZombieType("86fordE150knobCreek", "ConstructionWorker")
Utils.AddZombieType("86fordE150knoxTelecom", "ConstructionWorker")
Utils.AddZombieType("86fordE150knoxDistilery", "Trucker")
Utils.AddZombieType("86fordE150korshunovs", "Mechanic")
Utils.AddZombieType("86fordE150leatherwork", "Trucker")
Utils.AddZombieType("86fordE150lectromax", "Trucker")
Utils.AddZombieType("86fordE150locksmith", "Trucker")
Utils.AddZombieType("86fordE150lvLandscaping", "Farmer")
Utils.AddZombieType("86fordE150postal", "Postal")
Utils.AddZombieType("86fordE150stoneworksMasonry", "Trucker")
Utils.AddZombieType("86fordE150massGenfac", "Trucker")
Utils.AddZombieType("86fordE150meltingPointMetal", "MetalWorker")
Utils.AddZombieType("86fordE150metalheads", "MetalWorker")
Utils.AddZombieType("86fordE150michelesWoodshop", "ConstructionWorker")
Utils.AddZombieType("86fordE150mobileMechanics", "Mechanic")
Utils.AddZombieType("86fordE150mooresMechanics", "Mechanic")
Utils.AddZombieType("86fordE150oldMillWaterCompany", "ConstructionWorker")
Utils.AddZombieType("86fordE150oVoFarms", "Farmer")
Utils.AddZombieType("86fordE150pennSham", "ConstructionWorker")
Utils.AddZombieType("86fordE150perfick", "Trucker")
Utils.AddZombieType("86fordE150plattAutoRepair", "Mechanic")
Utils.AddZombieType("86fordE150pluggedInElectrics", "Trucker")
Utils.AddZombieType("86fordE150LBMWradio", "OfficeWorker")
Utils.AddZombieType("86fordE150riversideFab", "MetalWorker")
Utils.AddZombieType("86fordE150rosewoodWorking", "ConstructionWorker")
Utils.AddZombieType("86fordE150kyTransit", "Trucker")
Utils.AddZombieType("86fordE150schwab", "MetalWorker")
Utils.AddZombieType("86fordE150treyBaines", "Farmer")
Utils.AddZombieType("86fordE150uncloggers", "Trucker;Sanitation")
Utils.AddZombieType("86fordE150voltMojo", "Trucker")
Utils.AddZombieType("86fordE150wpCarpentry", "ConstructionWorker")
Utils.AddZombieType("86fordE150fossoil", "Fossoil")
Utils.AddZombieType("86fordE150creatureCruiser", "Young;Hobbyist;TinFoilHat")
Utils.AddZombieType("86fordE150theLadyDelighter", "Young;Naked;Party;WaiterStripper")
Utils.AddZombieType("86fordE150quantumVessel", "Young;Hobbyist;TinFoilHat")
Utils.AddZombieType("86fordE150valkyriesSpear", "Young;Hobbyist")
Utils.AddZombieType("86fordE150mesmerWagon", "Young;YoungCowpoke;Hobbyist;Party")

Utils.AddZombieType("86oshkoshFRTR55", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86oshkoshUSMC", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("86oshkoshKYFD", "FiremanFullSuit;Fireman")

Utils.AddZombieType("87buickRegalTurboTfbi", "Detective")

Utils.AddZombieType("87chevySuburbanCUCV", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("87fordB700military", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen;ArmyServiceUniform")
Utils.AddZombieType("87fordF700swat", "Police_SWAT;PoliceRiot")
Utils.AddZombieType("87fordB700prison", "Inmate;PrisonGuard")

Utils.AddZombieType("89fordBroncoPD", "Police;Sheriff_Deputy")
Utils.AddZombieType("89fordBroncoRanger", "Ranger")

Utils.AddZombieType("89deferWolf", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen;ArmyServiceUniform")

Utils.AddZombieType("90fordF350SWAT", "Police_SWAT;PoliceRiot")
Utils.AddZombieType("90fordF350ambulance", "AmbulanceDriver")

Utils.AddZombieType("90pierceArrow", "FiremanFullSuit;Fireman")

Utils.AddZombieType("91fordLTDksp", "PoliceState;Sheriff_Deputy")
Utils.AddZombieType("91fordLTDksp2", "PoliceState")
Utils.AddZombieType("91fordLTDpd", "Police")
Utils.AddZombieType("91fordLTDunmarked", "Detective")
Utils.AddZombieType("91fordLTDranger", "Ranger")
Utils.AddZombieType("91fordLTDtaxi", "Generic01;Generic02;Generic03;Generic04;Generic05")

Utils.AddZombieType("91fordRangerPD", "Police;Sheriff_Deputy")

Utils.AddZombieType("92amgeneralM998", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("92fordCVPIfd", "Fireman")
Utils.AddZombieType("92fordCVPI2ksp", "PoliceState")
Utils.AddZombieType("92fordCVPI2kspst", "PoliceState")
Utils.AddZombieType("92fordCVPI2so", "Sheriff_Deputy")
Utils.AddZombieType("92fordCVPI2sup", "Sheriff_Deputy")
Utils.AddZombieType("92fordCVPI", "Police;Sheriff_Deputy;PoliceState")
Utils.AddZombieType("92fordCVPI2", "Police;Sheriff_Deputy;PoliceState")
Utils.AddZombieType("92fordCVPIunmarked", "Detective")
Utils.AddZombieType("92fordCVPIpdu", "Detective")
Utils.AddZombieType("92fordCVPItaxi", "Generic01;Generic02;Generic03;Generic04;Generic05")

Utils.AddZombieType("92jeepYJranger", "Ranger")

Utils.AddZombieType("93chevySuburbanpd", "Police;Sheriff_Deputy")
Utils.AddZombieType("93chevySuburbanksp", "PoliceState")
Utils.AddZombieType("93chevySuburbanfbi", "Detective")
Utils.AddZombieType("93chevySuburbanpdu", "Detective")
Utils.AddZombieType("93chevySuburbanfd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("93chevySilveradoSClongFossoil", "Fossoil")
Utils.AddZombieType("93chevySilveradoXClongMcCoy", "McCoys")
Utils.AddZombieType("93chevySilveradoCClongfd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("93chevySilveradoXClongRanger", "Ranger")
Utils.AddZombieType("93chevySilveradoK3500flatbed", "Trucker")
Utils.AddZombieType("93chevySilveradoK3500wrecker", "Trucker")

Utils.AddZombieType("93chevySilveradoAirport", "AirportWorkerTarmac")
Utils.AddZombieType("93chevySilveradoK3500lvLandscaping", "Farmer")
Utils.AddZombieType("93chevySilveradoK3500mechanic", "Mechanic")
Utils.AddZombieType("93chevySilveradoMcCoyWoodworking", "ConstructionWorker")
Utils.AddZombieType("93chevySilveradoPennSham", "ConstructionWorker")
Utils.AddZombieType("93chevySilveradoPoliceBCS", "Sheriff_Deputy")
Utils.AddZombieType("93chevySilveradoPoliceMCS", "Sheriff_Deputy")
Utils.AddZombieType("93chevySilveradoRiversideFab", "MetalWorker")
Utils.AddZombieType("93chevySilveradoStoneworksMasonry", "Trucker")
Utils.AddZombieType("93chevySilveradoUncloggers", "Trucker;Sanitation")
Utils.AddZombieType("93chevySilveradoVoltMojo", "Trucker")
Utils.AddZombieType("93chevySilveradoWpCarpentry", "ConstructionWorker")
Utils.AddZombieType("93chevySuburbanAirportSec", "AirportSecurityTarmac")
Utils.AddZombieType("93chevySuburbanPoliceBCS", "Sheriff_Deputy")
Utils.AddZombieType("93chevySuburbanPoliceCLPD", "Police")
Utils.AddZombieType("93chevySuburbanPoliceLCPD", "Police")
Utils.AddZombieType("93chevySuburbanPoliceMCS", "Sheriff_Deputy")
Utils.AddZombieType("93chevySuburbanPoliceMPD", "Police")
Utils.AddZombieType("93chevySuburbanPoliceWPPD", "Police")
Utils.AddZombieType("93chevySuburbanPrison", "PrisonGuard")

Utils.AddZombieType("93fordElgin", "ConstructionWorker")
Utils.AddZombieType("93fordElginSpec", "ConstructionWorker")

Utils.AddZombieType("93fordF350pd", "Police;Sheriff_Deputy;PoliceState")
Utils.AddZombieType("93fordF350fd", "FiremanFullSuit;Fireman")
Utils.AddZombieType("93fordF350utilityDpw", "ConstructionWorker")
Utils.AddZombieType("93fordF350utilityFd", "FiremanFullSuit;Fireman")

Utils.AddZombieType("93mustangSSPpd", "Police")
Utils.AddZombieType("93mustangSSPpd2", "Police")
Utils.AddZombieType("93mustangSSPksp", "PoliceState")
Utils.AddZombieType("93mustangSSPksp2", "PoliceState")
Utils.AddZombieType("93mustangSSPkspCol", "PoliceState")
Utils.AddZombieType("93mustangSSPunmarked", "Detective")

Utils.AddZombieType("97bushmaster", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")
Utils.AddZombieType("97bushAmbulance", "ArmyInstructor;ArmyCamoDesert;ArmyCamoGreen")

Utils.AddZombieType("99fordCVPI", "Police;Sheriff_Deputy;PoliceState")
Utils.AddZombieType("99fordCVPIunmarked", "Detective")