local group = AttachedLocations.getGroup("Human")

group:getOrCreateLocation("RightCanteenSlot"):setAttachmentName("RightCanteenSlot_1")
group:getOrCreateLocation("LeftCanteenSlot"):setAttachmentName("LeftCanteenSlot_2")
group:getOrCreateLocation("RightGrenadeSlot"):setAttachmentName("RightGrenadeSlot_4")
group:getOrCreateLocation("LeftGrenadeSlot"):setAttachmentName("LeftGrenadeSlot_5")
group:getOrCreateLocation("M9BayonetSlot"):setAttachmentName("M9BayonetSlot_3")
group:getOrCreateLocation("RightGrenadeSlotOther"):setAttachmentName("RightGrenadeSlot_4_Other")
group:getOrCreateLocation("LeftGrenadeSlotOther"):setAttachmentName("LeftGrenadeSlot_5_Other")
group:getOrCreateLocation("RightGrenadeSlotWalkie"):setAttachmentName("RightGrenadeSlot_4_Walkie")
group:getOrCreateLocation("LeftGrenadeSlotWalkie"):setAttachmentName("LeftGrenadeSlot_5_Walkie")
group:getOrCreateLocation("RightGrenadeSlotCanteen"):setAttachmentName("RightGrenadeSlot_4_Canteen")
group:getOrCreateLocation("LeftGrenadeSlotCanteen"):setAttachmentName("LeftGrenadeSlot_5_Canteen")
group:getOrCreateLocation("AliceRightHandgunSlot"):setAttachmentName("AliceRightHandgunSlot_6")
