-- Works:

ItemTag.register("Trex:PeardriedTrex")
ItemTag.register("Trex:AppledriedTrex")
ItemTag.register("Trex:BananadriedTrex")
ItemTag.register("Trex:CherrydriedTrex")
ItemTag.register("Trex:LemondriedTrex")
ItemTag.register("Trex:LimedriedTrex")
ItemTag.register("Trex:MangodriedTrex")
ItemTag.register("Trex:OrangedriedTrex")
ItemTag.register("Trex:PeachdriedTrex")
ItemTag.register("Trex:PineappledriedTrex")
ItemTag.register("Trex:GrapefruitdriedTrex")
ItemTag.register("Trex:GrapesdriedTrex")
ItemTag.register("Trex:StrewberriedriedTrex")
ItemTag.register("Trex:BerrydriedTrex")

ItemTag.register("Trex:CookPeardriedTrex")
ItemTag.register("Trex:CookAppledriedTrex")
ItemTag.register("Trex:CookBananadriedTrex")
ItemTag.register("Trex:CookCherrydriedTrex")
ItemTag.register("Trex:CookLemondriedTrex")
ItemTag.register("Trex:CookLimedriedTrex")
ItemTag.register("Trex:CookMangodriedTrex")
ItemTag.register("Trex:CookOrangedriedTrex")
ItemTag.register("Trex:CookPeachdriedTrex")
ItemTag.register("Trex:CookPineappledriedTrex")
ItemTag.register("Trex:CookGrapefruitdriedTrex")
ItemTag.register("Trex:CookGrapesdriedTrex")
ItemTag.register("Trex:CookStrewberriedriedTrex")
ItemTag.register("Trex:CookBerrydriedTrex")

