require "TCMusicDefenitions"

	GlobalMusic["CassetteIPZMusicAllofMe"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicAWAKE"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicBansanka"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicBelindaAmigosxSiempre"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicBLOODHOUNDS"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicBreakingBadThemeSong"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicCalifornication"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusiccomet"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicDearGod"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicDebutantBall"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicFeelSpecial"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicGooGooDollsIris"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicHindiaeverythinguare"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicHINKIRO"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicIReallyWanttoStayAtYourHouse"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicInitialDBlackOut"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicListenNot"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicLostinParadise"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicMahalKitaBobo"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicMEGITSUNE"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicMICDrop(SteveAokiRemix)"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicOverdose"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicSANTEMIKINAH"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicSTECUSTECU"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicSunflower"] = "tsarcraft_music_01_62"
	GlobalMusic["CassetteIPZMusicWelcomeToTheBlackParade"] = "tsarcraft_music_01_62"

