--------------------------------------------------------------------------------
-- Better Sorting Reborn — category taxonomy (single source of truth).
--
-- Everything else derives from this table:
--   * IG_UI translation files      -> generated by tools/build_translations.py
--   * data-table validation        -> tools/validate.py
--
-- Fields per entry:
--   key     stable DisplayCategory value written into item scripts.
--           NEVER rename a key once released: it is the public API of the mod
--           (mod-support packs and other mods may reference it).
--   en, fr  category label per language.
--   vanilla true when the key already exists as a vanilla category (both B41
--           and B42). We then reuse the vanilla key and ship NO label override
--           (the game translates it in every language already). For those
--           entries en/fr document the vanilla labels for reference.
--
-- The order below is the reference/documentation order only; the in-game
-- inventory sorts categories alphabetically by (untranslated) key.
--
-- Taxonomy lineage: Better Sorting v2.0.4 by ChobitsCrazy (61 keys), with one
-- deliberate change: the original's "Cont" key is dropped in favor of the
-- vanilla "Container" key (the original itself used both inconsistently).
--------------------------------------------------------------------------------

BSR = BSR or {}

BSR.Categories = {
    { key = "Appear",      en = "Appearance",                fr = "Apparence" },
    { key = "Clean",       en = "Cleaning",                  fr = "Nettoyage" },
    { key = "ClothAcc",    en = "Clothing - Accessory",      fr = "Vêtement - Accessoire" },
    { key = "ClothArm",    en = "Clothing - Arms/Hands",     fr = "Vêtement - Bras/Mains" },
    { key = "ClothBack",   en = "Clothing - Backpack",       fr = "Vêtement - Sac à dos" },
    { key = "ClothBag",    en = "Clothing - Bag",            fr = "Vêtement - Sac" },
    { key = "ClothBody",   en = "Clothing - Body",           fr = "Vêtement - Corps" },
    { key = "ClothFeet",   en = "Clothing - Feet",           fr = "Vêtement - Pieds" },
    { key = "ClothHead",   en = "Clothing - Head",           fr = "Vêtement - Tête" },
    { key = "ClothJew",    en = "Clothing - Jewelry",        fr = "Vêtement - Bijoux" },
    { key = "ClothLeg",    en = "Clothing - Legs",           fr = "Vêtement - Jambes" },
    { key = "ClothMisc",   en = "Clothing - Misc",           fr = "Vêtement - Divers" },
    { key = "ClothUnder",  en = "Clothing - Underwear",      fr = "Vêtement - Sous-vêtements" },
    { key = "Collect",     en = "Collectable",               fr = "Objet de collection" },
    { key = "Container",   en = "Container",                 fr = "Sac", vanilla = true },
    { key = "Cook",        en = "Cooking",                   fr = "Cuisine" },
    { key = "CookB",       en = "Cooking - Brewing",         fr = "Cuisine - Brassage" },
    { key = "Craft",       en = "Crafting",                  fr = "Artisanat" },
    { key = "CraftAmmo",   en = "Crafting - Ammunition",     fr = "Artisanat - Munitions" },
    { key = "CraftCarp",   en = "Crafting - Carpentry",      fr = "Artisanat - Menuiserie" },
    { key = "CraftElec",   en = "Crafting - Electronics",    fr = "Artisanat - Électronique" },
    { key = "CraftMas",    en = "Crafting - Masonry",        fr = "Artisanat - Maçonnerie" },
    { key = "CraftMetal",  en = "Crafting - Metalworking",   fr = "Artisanat - Métallurgie" },
    { key = "CraftTailor", en = "Crafting - Tailoring",      fr = "Artisanat - Couture" },
    { key = "Drugs",       en = "Drugs",                     fr = "Médicaments" },
    { key = "Elec",        en = "Electronics",               fr = "Électronique" },
    { key = "FoodA",       en = "Food - Alcohol",            fr = "Nourriture - Alcool" },
    { key = "FoodB",       en = "Food - Beverage",           fr = "Nourriture - Boisson" },
    { key = "FoodP",       en = "Food - Perishable",         fr = "Nourriture - Périssable" },
    { key = "FoodN",       en = "Food - Non-Perishable",     fr = "Nourriture - Non périssable" },
    { key = "Fuel",        en = "Fuel",                      fr = "Combustible" },
    { key = "Furn",        en = "Furniture",                 fr = "Mobilier" },
    { key = "Junk",        en = "Junk",                      fr = "Déchet", vanilla = true },
    { key = "Key",         en = "Key",                       fr = "Clé" },
    { key = "LitC",        en = "Literature - Cartography",  fr = "Littérature - Cartographie" },
    { key = "LitE",        en = "Literature - Entertainment", fr = "Littérature - Divertissement" },
    { key = "LitR",        en = "Literature - Recipe",       fr = "Littérature - Recettes" },
    { key = "LitS",        en = "Literature - Skill",        fr = "Littérature - Compétences" },
    { key = "LitW",        en = "Literature - Writing",      fr = "Littérature - Écriture" },
    { key = "Mech",        en = "Mechanics",                 fr = "Mécanique" },
    { key = "MediaA",      en = "Media - Audio",             fr = "Média - Audio" },
    { key = "MediaG",      en = "Media - Game",              fr = "Média - Jeu vidéo" },
    { key = "MediaV",      en = "Media - Video",             fr = "Média - Vidéo" },
    { key = "Med",         en = "Medical",                   fr = "Médical" },
    { key = "Misc",        en = "Misc",                      fr = "Divers" },
    { key = "Paint",       en = "Paint",                     fr = "Peinture", vanilla = true },
    { key = "SurCamp",     en = "Survival - Camping",        fr = "Survie - Camping" },
    { key = "SurFarm",     en = "Survival - Farming",        fr = "Survie - Agriculture" },
    { key = "SurFish",     en = "Survival - Fishing",        fr = "Survie - Pêche" },
    { key = "SurTrap",     en = "Survival - Trapping",       fr = "Survie - Piégeage" },
    { key = "Tool",        en = "Tool",                      fr = "Outil", vanilla = true },
    { key = "Ammo",        en = "Ammo",                      fr = "Munitions", vanilla = true },
    { key = "WepAmmoMag",  en = "Weapon - Magazine",         fr = "Arme - Chargeur" },
    { key = "WepAmmoMagF", en = "Weapon - Magazine (Fixed)", fr = "Arme - Chargeur (fixe)" },
    { key = "WepBomb",     en = "Weapon - Bomb",             fr = "Arme - Explosif" },
    { key = "WepBow",      en = "Weapon - Bow",              fr = "Arme - Arc" },
    { key = "WepFire",     en = "Weapon - Firearm",          fr = "Arme - Arme à feu" },
    { key = "WepMelee",    en = "Weapon - Melee",            fr = "Arme - Mêlée" },
    { key = "WepPart",     en = "Weapon - Part",             fr = "Arme - Composant" },
    { key = "WepRange",    en = "Weapon - Ranged",           fr = "Arme - Distance" },
    { key = "WepShield",   en = "Weapon - Shield",           fr = "Arme - Bouclier" },
}
