-- Works:

ItemTag.register("Trex:CannedPear_Trex")
ItemTag.register("Trex:CannedPear_Open_Trex")
ItemTag.register("Trex:CannedApple_Trex")
ItemTag.register("Trex:CannedApple_Open_Trex")
ItemTag.register("Trex:CannedBanana_Trex")
ItemTag.register("Trex:CannedBanana_Open_Trex")
ItemTag.register("Trex:CannedCherry_Trex")
ItemTag.register("Trex:CannedCherry_Open_Trex")
ItemTag.register("Trex:CannedLemon_Trex")
ItemTag.register("Trex:CannedLemon_Open_Trex")
ItemTag.register("Trex:CannedLime_Trex")
ItemTag.register("Trex:CannedLime_Open_Trex")
ItemTag.register("Trex:CannedMango_Trex")
ItemTag.register("Trex:CannedMango_Open_Trex")
ItemTag.register("Trex:CannedOrange_Trex")
ItemTag.register("Trex:CannedOrange_Open_Trex")
ItemTag.register("Trex:CannedPeach_Trex")
ItemTag.register("Trex:CannedPeach_Open_Trex")
ItemTag.register("Trex:CannedPineapple_Trex")
ItemTag.register("Trex:CannedPineapple_Open_Trex")
ItemTag.register("Trex:CannedWatermelon_Trex")
ItemTag.register("Trex:CannedWatermelon_Open_Trex")
ItemTag.register("Trex:CannedBerry_Trex")
ItemTag.register("Trex:CannedBerry_Open_Trex")