Distributions = Distributions or {};
 
local distributionTable = {
	
	Bag_Courier_Leather = {
		rolls = 10,
		items = {
			"Leather_Sleeves_L", 10,
			"Leather_SleevesLeg_L", 10,
			"Latex_Micro_Shorts", 10,
			"Leather_Shorts", 10,
			"Leather_miniSkirt", 10,
			"Leather_miniSkirt2", 10,
			"Leather_PleatedSkirt", 10,
			"Leather_Skirt", 10,
			"Leather_Skirt_HW", 3,
			"Leather_Garter", 1,
			"Leather_Armband", 1,
			"HarnessBelt", 1,
			"Leather_Bandeau", 10,
			"Leather_Bolero", 10,
			"Leather_Leotard", 10,
			"Leather_Leotard_Novelty", 10,
			"Leather_Leotard_MC_Designer", 1,
			"Leather_Leotard_Sleeves", 10,
			"Leather_Long_Gloves", 10,
			"Leather_Pants", 10,
			"Leather_Novelty_Pants", 5,
			"Leather_Pants_Designer", 1,
			"Leather_Stockings", 10,
			"Leather_SupLongGloves", 0.5,
			"Leather_SupStockings", 0.5,
			"Leather_Top", 10,
			"Leather_CropTop", 10,
			"Leather_CropTop_Sleeves", 10,
			"Leather_UBCorset", 10,
			"Leather_Corset", 10,
			"Leather_Stirrup_Stockings1", 10,
			"Leather_Harness", 0.5,
			"Leather_Harness_Designer", 0.5,
			"Leather_Harness_Bra", 1,
			"Leather_Harness_Panties", 1,
			"Cuffs_Collar", 1,
			"Cuffs_Collar_Spiked", 1,
			"Leather_Sleeves_L", 0.5,
			"Leather_SleevesLeg_R", 0.5,
			
			"Leather_MicroShorts_High", 11,
			"", 2,
			"", 2,
		},
		
	},
	
	Bag_FrockinSplendor3_ToyBox = {
		rolls = 16,
		items = {
			"Leather_Sleeves_L", 6,
			"Leather_SleevesLeg_L", 6,
			"Latex_Micro_Shorts", 6,
			"Leather_Shorts", 6,
			"Leather_miniSkirt", 6,
			"Leather_miniSkirt2", 6,
			"Leather_PleatedSkirt", 6,
			"Leather_Skirt", 10,
			"Leather_Skirt_HW", 3,
			"Leather_Garter", 6,
			"Leather_Armband", 6,
			"HarnessBelt", 6,
			"Leather_Bandeau", 6,
			"Leather_Bodysuit", 15,
			"Leather_Jacket_Cropped_1", 6,
			"Leather_TrenchCoat_Long", 15,
			"Leather_TrenchCoat_Short", 15,
			"Leather_Jacket_Cropped", 0.25,
			"Leather_Bolero", 6,
			"Leather_Leotard", 6,
			"Leather_Leotard_Novelty", 6,
			"Leather_Leotard_MC_Designer", 3,
			"Leather_Leotard_Sleeves", 6,
			"Leather_Long_Gloves", 6,
			"Leather_Pants", 6,
			"Leather_Novelty_Pants", 5,
			"Leather_Pants_Designer", 3,
			"Leather_Stockings", 6,
			"Leather_SupLongGloves", 0.5,
			"Leather_SupStockings", 0.5,
			"Leather_Top", 6,
			"Leather_CropTop", 6,
			"Leather_CropTop_Sleeves", 6,
			"Leather_UBCorset", 6,
			"Leather_Corset", 6,
			"Leather_Stirrup_Stockings1", 6,
			"Leather_Harness", 3,
			"Leather_Harness_Designer", 3,
			"Leather_Harness_Bra", 3,
			"Leather_Harness_Panties", 3,
			"Cuffs_Collar", 3,
			"Cuffs_Collar_Spiked", 3,
			
			"Leather_MicroShorts_High", 9,
			"", 2,
			"", 2,
		},
		
	},
	
	Bag_FrockinSplendor3_GiftBag = {
		rolls = 12,
		items = {
			"Leather_Sleeves_L", 7,
			"Leather_SleevesLeg_L", 7,
			"Latex_Micro_Shorts", 7,
			"Leather_Shorts", 7,
			"Leather_miniSkirt", 7,
			"Leather_miniSkirt2", 7,
			"Leather_PleatedSkirt", 7,
			"Leather_Skirt", 5,
			"Leather_Skirt_HW", 2,
			"Leather_Bandeau", 7,
			"Leather_Bodysuit", 0.5,
			"Leather_Jacket_Cropped_1", 0.5,
			"Leather_Bolero", 7,
			"Leather_Leotard", 7,
			"Leather_Leotard_Novelty", 7,
			"Leather_Leotard_MC_Designer", 1,
			"Leather_Leotard_Sleeves", 7,
			"Leather_Long_Gloves", 7,
			"Leather_Pants", 7,
			"Leather_Novelty_Pants", 5,
			"Leather_Pants_Designer", 1,
			"Leather_Stockings", 7,
			"Leather_SupLongGloves", 0.5,
			"Leather_SupStockings", 0.5,
			"Leather_Top", 7,
			"Leather_CropTop", 7,
			"Leather_CropTop_Sleeves", 7,
			"Leather_UBCorset", 7,
			"Leather_Corset", 7,
			"Leather_Stirrup_Stockings1", 7,
			"Leather_Sleeves_L", 0.5,
			"Leather_SleevesLeg_R", 0.5,
			
			"Leather_MicroShorts_High", 9,
			"", 2,
			"", 2,
		},
		
	},
	
	Bag_FrockinSplendor_TasterBag = {
		rolls = 10,
		items = {
			"Leather_Stirrup_Stockings1", 5,
			"Leather_Harness", 5,
			"Leather_Harness_Designer", 5,
			"Leather_Harness_Bra", 5,
			"Leather_Harness_Panties", 5,
			"Cuffs_Collar", 5,
			"Cuffs_Collar_Spiked", 5,
			"Leather_Long_Gloves", 3,
			"Leather_Stockings", 3,
			"Leather_SupLongGloves", 1,
			"Leather_SupStockings", 1,
			"Latex_Micro_Shorts", 7,
			"Leather_Armband", 5,
			"Leather_Garter", 5,
			"HarnessBelt", 5,
			"Leather_Sleeves_L", 5,
			"Leather_SleevesLeg_R", 5,
			
			"Leather_Stirrup_Stockings1", 1,
			"Leather_Harness", 1,
			"Leather_Harness_Designer", 1,
			"Leather_Harness_Bra", 1,
			"Leather_Harness_Panties", 1,
			"Cuffs_Collar", 1,
			"Cuffs_Collar_Spiked", 1,
			"Leather_Long_Gloves", 3,
			"Leather_Stockings", 3,
			"Leather_SupLongGloves", 1,
			"Leather_SupStockings", 1,
			"Latex_Micro_Shorts", 7,
			"Leather_Armband", 1,
			"Leather_Garter", 1,
			"HarnessBelt", 1,
			"Leather_Sleeves_L", 1,
			"Leather_SleevesLeg_R", 1,
		},
		
	},
}

table.insert(Distributions, 1, distributionTable);