Distributions = Distributions or {};

local m = SandboxVars.CL_ClothesRate or 1
local distributionTable = {}
distributionTable.all = {}
distributionTable.all.clothesLineMiddle = 
{			rolls = 1,
            items = 
			{
			"JacketLong_Random", 0.5*m,
            "Jacket_Black", 0.5*m,
            "Jacket_Shellsuit_Black", 0.05*m,
            "Jacket_Shellsuit_Blue", 0.05*m,
            "Jacket_Shellsuit_Green", 0.05*m,
            "Jacket_Shellsuit_Pink", 0.05*m,
            "Jacket_Shellsuit_Teal", 0.05*m,
            "Jacket_Shellsuit_TINT", 0.2*m,
            "Jacket_WhiteTINT", 0.5*m,
            "Jumper_DiamondPatternTINT", 0.1*m,
            "Jumper_PoloNeck", 0.5*m,
            "Jumper_RoundNeck", 0.5*m,
            "Jumper_TankTopTINT", 0.5*m,
            "Jumper_VNeck", 0.5*m,
			"LongCoat_Bathrobe", 0.1*m,
			"Shirt_Denim", 0.05*m,
            "Shirt_FormalTINT", 0.5*m,
            "Shirt_FormalWhite", 0.5*m,
            "Shirt_FormalWhite_ShortSleeve", 1*m,
            "Shirt_FormalWhite_ShortSleeveTINT", 1*m,
            "Shirt_Lumberjack", 0.05*m,
            "Shorts_LongDenim", 1*m,
			"Trousers", 2*m,
            "TrousersMesh_DenimLight", 2*m,
            "Trousers_DefaultTEXTURE", 2*m,
            "Trousers_DefaultTEXTURE_HUE", 2*m,
            "Trousers_DefaultTEXTURE_TINT", 2*m,
            "Trousers_Denim", 1*m,
            "Trousers_JeanBaggy", 1*m,
            "Trousers_Shellsuit_Black", 0.05*m,
            "Trousers_Shellsuit_Blue", 0.05*m,
            "Trousers_Shellsuit_Green", 0.05*m,
            "Trousers_Shellsuit_Pink", 0.05*m,
            "Trousers_Shellsuit_Teal", 0.05*m,
            "Trousers_Shellsuit_TINT", 0.2*m,
            "Trousers_Suit", 0.5*m,
            "Trousers_SuitTEXTURE", 0.5*m,
            "Trousers_WhiteTINT", 2*m,
            "Tshirt_DefaultDECAL_TINT", 0.1*m,
            "Tshirt_DefaultTEXTURE_TINT", 1*m,
            "Tshirt_IndieStoneDECAL", 0.001*m,
            "Tshirt_PoloStripedTINT", 0.5*m,
            "Tshirt_PoloTINT", 0.5*m,
            "Tshirt_WhiteLongSleeveTINT", 1*m,
            "Tshirt_WhiteTINT", 2*m,
			"Bra_Strapless_AnimalPrint", 0.2*m,
            "Bra_Strapless_Black", 0.2*m,
            "Bra_Strapless_FrillyBlack", 0.2*m,
            "Bra_Strapless_FrillyPink", 0.2*m,
            "Bra_Strapless_RedSpots", 0.2*m,
            "Bra_Strapless_White", 0.2*m,
            "Bra_Straps_AnimalPrint", 0.2*m,
            "Bra_Straps_Black", 0.2*m,
            "Bra_Straps_FrillyBlack", 0.2*m,
            "Bra_Straps_FrillyPink", 0.2*m,
            "Bra_Straps_White", 0.2*m,
			"FrillyUnderpants_Black", 0.4*m,
            "FrillyUnderpants_Pink", 0.4*m,
            "FrillyUnderpants_Red", 0.4*m,
			"Garter", 0.2*m,
			"Corset", 0.2*m,
            "Corset_Black", 0.2*m,
			"Dress_Knees", 1*m,
            "Dress_Long", 1*m,
            "Dress_Normal", 1*m,
            },
			
			
			junk = {
                rolls = 1,
                items = {
                    
                }
            }
}

distributionTable["all"]["clothesLineEnd"] = 
{
			rolls = 1,
            items = 
			{
			"JacketLong_Random", 0.5*m,
            "Jacket_Black", 0.5*m,
            "Jacket_Shellsuit_Black", 0.05*m,
            "Jacket_Shellsuit_Blue", 0.05*m,
            "Jacket_Shellsuit_Green", 0.05*m,
            "Jacket_Shellsuit_Pink", 0.05*m,
            "Jacket_Shellsuit_Teal", 0.05*m,
            "Jacket_Shellsuit_TINT", 0.2*m,
            "Jacket_WhiteTINT", 0.5*m,
            "Jumper_DiamondPatternTINT", 0.1*m,
            "Jumper_PoloNeck", 0.5*m,
            "Jumper_RoundNeck", 0.5*m,
            "Jumper_TankTopTINT", 0.5*m,
            "Jumper_VNeck", 0.5*m,
			"LongCoat_Bathrobe", 0.1*m,
			"Shirt_Denim", 0.05*m,
            "Shirt_FormalTINT", 0.5*m,
            "Shirt_FormalWhite", 0.5*m,
            "Shirt_FormalWhite_ShortSleeve", 1*m,
            "Shirt_FormalWhite_ShortSleeveTINT", 1*m,
            "Shirt_Lumberjack", 0.05*m,
            "Shorts_LongDenim", 1*m,
			"Trousers", 2*m,
            "TrousersMesh_DenimLight", 2*m,
            "Trousers_DefaultTEXTURE", 2*m,
            "Trousers_DefaultTEXTURE_HUE", 2*m,
            "Trousers_DefaultTEXTURE_TINT", 2*m,
            "Trousers_Denim", 1*m,
            "Trousers_JeanBaggy", 1*m,
            "Trousers_Shellsuit_Black", 0.05*m,
            "Trousers_Shellsuit_Blue", 0.05*m,
            "Trousers_Shellsuit_Green", 0.05*m,
            "Trousers_Shellsuit_Pink", 0.05*m,
            "Trousers_Shellsuit_Teal", 0.05*m,
            "Trousers_Shellsuit_TINT", 0.2*m,
            "Trousers_Suit", 0.5*m,
            "Trousers_SuitTEXTURE", 0.5*m,
            "Trousers_WhiteTINT", 2*m,
            "Tshirt_DefaultDECAL_TINT", 0.1*m,
            "Tshirt_DefaultTEXTURE_TINT", 1*m,
            "Tshirt_IndieStoneDECAL", 0.001*m,
            "Tshirt_PoloStripedTINT", 0.5*m,
            "Tshirt_PoloTINT", 0.5*m,
            "Tshirt_WhiteLongSleeveTINT", 1*m,
            "Tshirt_WhiteTINT", 2*m,
			"Bra_Strapless_AnimalPrint", 0.2*m,
            "Bra_Strapless_Black", 0.2*m,
            "Bra_Strapless_FrillyBlack", 0.2*m,
            "Bra_Strapless_FrillyPink", 0.2*m,
            "Bra_Strapless_RedSpots", 0.2*m,
            "Bra_Strapless_White", 0.2*m,
            "Bra_Straps_AnimalPrint", 0.2*m,
            "Bra_Straps_Black", 0.2*m,
            "Bra_Straps_FrillyBlack", 0.2*m,
            "Bra_Straps_FrillyPink", 0.2*m,
            "Bra_Straps_White", 0.2*m,
			"FrillyUnderpants_Black", 0.4*m,
            "FrillyUnderpants_Pink", 0.4*m,
            "FrillyUnderpants_Red", 0.4*m,
			"Garter", 0.2*m,
			"Corset", 0.2*m,
            "Corset_Black", 0.2*m,
			"Dress_Knees", 1*m,
            "Dress_Long", 1*m,
            "Dress_Normal", 1*m,
            },
            
			junk = {
                rolls = 1,
                items = {
                    
                }
            }
}
		table.insert(Distributions, distributionTable);