FrockinSplendor2_Distribution = Distributions or {};
 
local distributionTable = {
	
	Bag_FrockinSplendor2_ToyBox = {
		rolls = 16,
		items = {
			"Cotton_WaistCoat", 3,
			"Cotton_WaistCoat_T", 3,
			"Cotton_Shorts", 3,
			"Cotton_MicroSkirt", 3,
			"Cotton_Boleros", 3,
			"Cotton_Top", 3,
			"Cotton_CropTop", 3,
			"Cotton_PleatedSkirt", 3,
			"Cotton_miniSkirt_HW", 3,
			"Cotton_miniSkirt_HW_1", 3,
			"Cotton_Top_Sleeves", 3,
			"Cotton_CropTop_Sleeves", 3,
			"Cotton_Gloves_Long", 3,
			"Cotton_Gloves_Long_2", 3,
			"Cotton_Gloves_Short", 3,
			"Cotton_Leotard", 3,
			"Cotton_Leotard_MC", 1,
			"Cotton_Leotard_HC", 1,
			"Cotton_Leotard_Sleeves", 3,
			"Cotton_Leotard_Sleeves_MC", 1,
			"Cotton_Leotard_Sleeves_HC", 1,
			"Cotton_Leotard_SleevesSrt", 3,
			"Cotton_Leotard_SleevesSrt_HC", 3,
			"Cotton_Leotard_SleevesSrter_MC", 3,
			
			"Sheer_Shirt", 2,
			"Cotton_Skirt1", 2,
			"Cotton_SkirtMini1", 2,
			"Cotton_SkirtMini4", 2,
			"Cotton_Skirt4", 2,
			"Cotton_SkirtPleated1", 2,
			"Cotton_SkirtPleated3", 2,
			"Cotton_SkirtPleatedMini1", 2,
			"Cotton_SkirtPleatedMini3", 2,
			"Sheer_Shirt_Button", 2,
			
			"Cotton_Skirt_Beach", 2,
			"Cotton_Skirt_Beach_1", 2,
			
			"Socks_ThighHigh1", 1.2,
			"Socks_ThighHigh3", 1.2,
			"Socks_Longer", 1.2,
			"Socks_Crew", 1.2,
			"Socks_Ankle", 1.2,
			"Socks_Heavy", 1.2,
			"Fitness_Leggings_Black", 1,
			"Fitness_Leggings_Alt", 1,
			"Fitness_Leggings_Blue", 1,
			"Fitness_Leggings_Cyan", 1,
			"Fitness_Leggings_Nude", 1,
			"Fitness_Leggings_Org", 1,
			"Fitness_Leggings_Purp", 1,
			"Fitness_Leggings_Red", 1,
			"Fitness_Leggings_Whit", 1,
			"Fitness_Leggings_Yel", 1,
			"Fitness_Leggings_Fish", 1,
			
			"Cotton_WaistCoat", 2,
			"Cotton_WaistCoat_T", 2,
			"Cotton_WaistCoat_DoubleBreasted", 2,
			
			"Cotton_Pants_Higher", 3,
			"Cotton_Pants", 2,
			"Cotton_Pants_Lower", 2,

			"Denim_PleatedSkirt", 2,
		},
		
	},
	
	Bag_FrockinSplendor2_GiftBag = {
		rolls = 12,
		items = {
			"Cotton_WaistCoat", 1.1,
			"Cotton_WaistCoat_T", 1.1,
			"Cotton_Shorts", 1.1,
			"Cotton_MicroSkirt", 1.1,
			"Cotton_Boleros", 1.1,
			"Cotton_Top", 1.1,
			"Cotton_CropTop", 1.1,
			"Cotton_PleatedSkirt", 1.1,
			"Cotton_miniSkirt_HW", 1.1,
			"Cotton_miniSkirt_HW_1", 1.1,
			"Cotton_Top_Sleeves", 1.1,
			"Cotton_CropTop_Sleeves", 1.1,
			"Cotton_Gloves_Long", 1.1,
			"Cotton_Gloves_Long_2", 1.1,
			"Cotton_Gloves_Short", 1.1,
			"Cotton_Leotard", 1.1,
			"Cotton_Leotard_MC", 1,
			"Cotton_Leotard_HC", 1,
			"Cotton_Leotard_Sleeves", 1.1,
			"Cotton_Leotard_Sleeves_MC", 1,
			"Cotton_Leotard_Sleeves_HC", 1,
			"Cotton_Leotard_SleevesSrt", 1.1,
			"Cotton_Leotard_SleevesSrt_HC", 1.1,
			"Cotton_Leotard_SleevesSrter_MC", 1.1,
			
			"Sheer_Shirt", 2,
			"Cotton_Skirt1", 2,
			"Cotton_SkirtMini1", 2,
			"Cotton_SkirtMini4", 2,
			"Cotton_Skirt4", 2,
			"Cotton_SkirtPleated1", 2,
			"Cotton_SkirtPleated3", 2,
			"Cotton_SkirtPleatedMini1", 2,
			"Cotton_SkirtPleatedMini3", 2,
			"Sheer_Shirt_Button", 2,
			
			"Cotton_Skirt_Beach", 2,
			"Cotton_Skirt_Beach_1", 2,
			
			"Cotton_WaistCoat", 2,
			"Cotton_WaistCoat_T", 2,
			"Cotton_WaistCoat_DoubleBreasted", 2,
			
			"Cotton_Pants_Higher", 3,
			"Cotton_Pants", 2,
			"Cotton_Pants_Lower", 2,
			
			"Denim_PleatedSkirt", 2,
		},
		
	},
	
	Bag_FrockinSplendor2_TasterBag = {
		rolls = 12,
		items = {
			"Socks_ThighHigh1", 2,
			"Socks_ThighHigh3", 2,
			"Socks_Longer", 2,
			"Socks_Crew", 2,
			"Socks_Ankle", 2,
			"Socks_Heavy", 2,
			"Fitness_Leggings_Black", 2,
			"Fitness_Leggings_Alt", 2,
			"Fitness_Leggings_Blue", 2,
			"Fitness_Leggings_Cyan", 2,
			"Fitness_Leggings_Nude", 2,
			"Fitness_Leggings_Org", 2,
			"Fitness_Leggings_Purp", 2,
			"Fitness_Leggings_Red", 2,
			"Fitness_Leggings_Whit", 2,
			"Fitness_Leggings_Yel", 2,
			"Fitness_Leggings_Fish", 2,
			
			"Socks_ThighHigh1", 2,
			"Socks_ThighHigh3", 2,
			"Socks_Longer", 2,
			"Socks_Crew", 2,
			"Socks_Ankle", 2,
			"Fitness_Leggings_Black", 2,
			"Fitness_Leggings_Alt", 2,
			"Fitness_Leggings_Blue", 2,
			"Fitness_Leggings_Cyan", 2,
			"Fitness_Leggings_Nude", 2,
			"Fitness_Leggings_Org", 2,
			"Fitness_Leggings_Purp", 2,
			"Fitness_Leggings_Red", 2,
			"Fitness_Leggings_Whit", 2,
			"Fitness_Leggings_Yel", 2,
			"Fitness_Leggings_Fish", 2,
			
			"Cotton_Tights_1", 2,
			"Knitted_Cotton_Tights_1", 2,
			"Cotton_Tights_2", 2,
			"Knitted_Cotton_Tights_2", 2,
		},
		
	},
}

table.insert(FrockinSplendor2_Distribution, 1, distributionTable);