--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: All Skill Books.
-- 15 skill lines x 5 volumes, all sorted to Literature - Skill.
--
-- Covers (one guard per mod in the original):
--   AllSkillBooks (AllSkillBooks) — https://steamcommunity.com/sharedfiles/filedetails/?id=2699202565
--
-- Mappings migrated from Better Sorting (AllSkillBooks_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "AllSkillBooks",
    mods = { "AllSkillBooks" },
    data = {
        LitS = {
            items = {
                "AllSkillBooks.BookAiming1",
                "AllSkillBooks.BookAiming2",
                "AllSkillBooks.BookAiming3",
                "AllSkillBooks.BookAiming4",
                "AllSkillBooks.BookAiming5",
                "AllSkillBooks.BookAxe1",
                "AllSkillBooks.BookAxe2",
                "AllSkillBooks.BookAxe3",
                "AllSkillBooks.BookAxe4",
                "AllSkillBooks.BookAxe5",
                "AllSkillBooks.BookBlunt1",
                "AllSkillBooks.BookBlunt2",
                "AllSkillBooks.BookBlunt3",
                "AllSkillBooks.BookBlunt4",
                "AllSkillBooks.BookBlunt5",
                "AllSkillBooks.BookFitness1",
                "AllSkillBooks.BookFitness2",
                "AllSkillBooks.BookFitness3",
                "AllSkillBooks.BookFitness4",
                "AllSkillBooks.BookFitness5",
                "AllSkillBooks.BookLightfooted1",
                "AllSkillBooks.BookLightfooted2",
                "AllSkillBooks.BookLightfooted3",
                "AllSkillBooks.BookLightfooted4",
                "AllSkillBooks.BookLightfooted5",
                "AllSkillBooks.BookLongBlade1",
                "AllSkillBooks.BookLongBlade2",
                "AllSkillBooks.BookLongBlade3",
                "AllSkillBooks.BookLongBlade4",
                "AllSkillBooks.BookLongBlade5",
                "AllSkillBooks.BookMaintenance1",
                "AllSkillBooks.BookMaintenance2",
                "AllSkillBooks.BookMaintenance3",
                "AllSkillBooks.BookMaintenance4",
                "AllSkillBooks.BookMaintenance5",
                "AllSkillBooks.BookNimble1",
                "AllSkillBooks.BookNimble2",
                "AllSkillBooks.BookNimble3",
                "AllSkillBooks.BookNimble4",
                "AllSkillBooks.BookNimble5",
                "AllSkillBooks.BookReloading1",
                "AllSkillBooks.BookReloading2",
                "AllSkillBooks.BookReloading3",
                "AllSkillBooks.BookReloading4",
                "AllSkillBooks.BookReloading5",
                "AllSkillBooks.BookSmallBlade1",
                "AllSkillBooks.BookSmallBlade2",
                "AllSkillBooks.BookSmallBlade3",
                "AllSkillBooks.BookSmallBlade4",
                "AllSkillBooks.BookSmallBlade5",
                "AllSkillBooks.BookSmallBlunt1",
                "AllSkillBooks.BookSmallBlunt2",
                "AllSkillBooks.BookSmallBlunt3",
                "AllSkillBooks.BookSmallBlunt4",
                "AllSkillBooks.BookSmallBlunt5",
                "AllSkillBooks.BookSneaking1",
                "AllSkillBooks.BookSneaking2",
                "AllSkillBooks.BookSneaking3",
                "AllSkillBooks.BookSneaking4",
                "AllSkillBooks.BookSneaking5",
                "AllSkillBooks.BookSpear1",
                "AllSkillBooks.BookSpear2",
                "AllSkillBooks.BookSpear3",
                "AllSkillBooks.BookSpear4",
                "AllSkillBooks.BookSpear5",
                "AllSkillBooks.BookSprinting1",
                "AllSkillBooks.BookSprinting2",
                "AllSkillBooks.BookSprinting3",
                "AllSkillBooks.BookSprinting4",
                "AllSkillBooks.BookSprinting5",
                "AllSkillBooks.BookStrength1",
                "AllSkillBooks.BookStrength2",
                "AllSkillBooks.BookStrength3",
                "AllSkillBooks.BookStrength4",
                "AllSkillBooks.BookStrength5",
            },
        },
    },
})
