--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: MoreMaps.
-- Every added map and map-location item sorted to Cartography.
--
-- Covers (one guard per mod in the original):
--   MoreMaps (MoreMaps) — https://steamcommunity.com/sharedfiles/filedetails/?id=2729427093
--
-- Mappings migrated from Better Sorting (MoreMaps_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "MoreMaps",
    mods = { "MoreMaps" },
    data = {
        LitC = {
            items = {
                "Base.AbandonedFactoryMap",
                "Base.BillionaireSafehouseLocation",
                "Base.BlackwoodMap",
                "Base.BlueberryMap",
                "Base.CONResearchMap",
                "Base.CabinLocation1",
                "Base.CabinLocation2",
                "Base.CabinLocation3",
                "Base.CabinLocation4",
                "Base.CabinLocation5",
                "Base.CampGroundsLocation",
                "Base.CenterCoryerdonMap",
                "Base.ChernavilleMap",
                "Base.ChinatownMap",
                "Base.ChristmasVillageMap",
                "Base.ConstructionFactoryMap",
                "Base.CoryerdonMap",
                "Base.CountryClubMap",
                "Base.DixieMap",
                "Base.EC_CentraliaMap",
                "Base.EC_CompleteMap",
                "Base.EC_CustomsBorderZoneMap",
                "Base.EC_DarkFallsMap",
                "Base.EC_ErenCityMap",
                "Base.EC_HiddenSwampsMap",
                "Base.EC_IrvingtonMap",
                "Base.EC_LakeHeisenbergMap",
                "Base.EC_RuralZoneMap",
                "Base.EC_SanDitoAirportMap",
                "Base.EC_TrainStationMap",
                "Base.EZPZCommunityCenterMap",
                "Base.EastCoryerdonMap",
                "Base.EasternSummerCampMap",
                "Base.EkronMap",
                "Base.FK_FortKnoxMap",
                "Base.FK_QuitmanMap",
                "Base.FortBenningMap",
                "Base.FortRedstoneMap",
                "Base.FortRockRidgeMap",
                "Base.FortWaterfrontMap",
                "Base.GlenportMap",
                "Base.GrapeseedMap",
                "Base.GreenleafMap",
                "Base.HongKongYauMaTeiMap",
                "Base.HyruleCountyMap",
                "Base.KentuckyMap",
                "Base.KingsmouthMap2",
                "Base.LakeIvyMap2",
                "Base.LindenMap",
                "Base.LittleTownshipMap",
                "Base.LouisvilleAudubonMap",
                "Base.LouisvilleCentralMap",
                "Base.LouisvilleChapelmountDownsMap",
                "Base.LouisvilleEastMap",
                "Base.LouisvilleEvergreenHillMap",
                "Base.LouisvilleGatedCommunityMap",
                "Base.LouisvilleIroquoisMap",
                "Base.LouisvilleLSUMap",
                "Base.LouisvilleLeafhillHeightsMap",
                "Base.LouisvilleMap",
                "Base.LouisvilleNorthCommercialDistrictMap",
                "Base.LouisvilleOldMap",
                "Base.LouisvillePhoenixHillMap",
                "Base.LouisvillePortlandMap",
                "Base.LouisvilleScarletOakMap",
                "Base.LouisvilleSouthMap",
                "Base.MansionAdress",
                "Base.MarchRidgeExpansionMap",
                "Base.MilitaryAirportMap",
                "Base.MilitaryBaseMap",
                "Base.MuldraughMilitaryBaseMap",
                "Base.MuldraughRailyardMap",
                "Base.MuldraughWarehouseComplexMap",
                "Base.NorthRavenCreekMap",
                "Base.OldParkTownMap",
                "Base.OldPineVillageMap",
                "Base.OverTheRiverMap",
                "Base.PitstopMap",
                "Base.PonyRoamOMap",
                "Base.RavenCreekMap",
                "Base.RavenCreekPortFacilitiesMap",
                "Base.RefordvilleMap",
                "Base.RemusMap",
                "Base.ResearchFacilityMap",
                "Base.RiverwoodMap",
                "Base.RosewoodExpansionMap",
                "Base.SL_NewDenverMap",
                "Base.SL_RoseberyMap",
                "Base.SL_SilvertonMap",
                "Base.ScenicGroveMap",
                "Base.SmallTownWestMap",
                "Base.SouthCoryerdonMap",
                "Base.SouthEastRavenCreekMap",
                "Base.StationMULD650Location",
                "Base.StationRIVS500Location",
                "Base.StationROSE099Location",
                "Base.StationWESTP88Location",
                "Base.StationZULULocation",
                "Base.SurvivorWarehouseLocation",
                "Base.TrimbleCountyLaGrangeMap",
                "Base.TrimbleCountyPowerStationMap",
                "Base.TugalandMap",
                "Base.ValleyStationMallAreaMap",
                "Base.ValleyStationMap",
                "Base.WestPointExpansionMap",
                "Base.WestPointFireDepartmentMap",
                "Base.WestPointSouthTrailerParkMap",
                "Base.WesternMilitaryComplexMap",
                "Base.WildberriesMap",
            },
        },
    },
})
