--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: School's Out.
-- https://steamcommunity.com/sharedfiles/filedetails/?id=2904220876
--
-- Japanese school uniforms, all declared in the mod's own "seifuku" module.
--
-- Mappings migrated from Better Sorting v2.0.4 (SchoolsOut_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "SchoolsOut",
    mods = { "seifuku" },
    data = {
        ClothAcc = {
            items = {
                "seifuku.Scarf_CuteCollarBlack",
                "seifuku.Scarf_CuteCollarBlue",
                "seifuku.Scarf_CuteCollarRed",
                "seifuku.Tie_NecktieBlack",
                "seifuku.Tie_NecktieBlue",
                "seifuku.Tie_NecktiePink",
                "seifuku.Tie_NecktieRed",
                "seifuku.Tie_NecktieYellow",
                "seifuku.Tie_RibbonBlack",
                "seifuku.Tie_RibbonBlackHi",
                "seifuku.Tie_RibbonBlue",
                "seifuku.Tie_RibbonBlueHi",
                "seifuku.Tie_RibbonPink",
                "seifuku.Tie_RibbonPinkHi",
                "seifuku.Tie_RibbonRed",
                "seifuku.Tie_RibbonRedHi",
                "seifuku.Tie_RibbonSingleBlack",
                "seifuku.Tie_RibbonSingleBlackHi",
                "seifuku.Tie_RibbonSingleBlue",
                "seifuku.Tie_RibbonSingleBlueHi",
                "seifuku.Tie_RibbonSinglePink",
                "seifuku.Tie_RibbonSinglePinkHi",
                "seifuku.Tie_RibbonSingleRed",
                "seifuku.Tie_RibbonSingleRedHi",
                "seifuku.Tie_RibbonSingleYellow",
                "seifuku.Tie_RibbonSingleYellowHi",
                "seifuku.Tie_RibbonYellow",
                "seifuku.Tie_RibbonYellowHi",
                "seifuku.Tie_StringBlack",
                "seifuku.Tie_StringBlackHi",
                "seifuku.Tie_StringBlue",
                "seifuku.Tie_StringBlueHi",
                "seifuku.Tie_StringPink",
                "seifuku.Tie_StringPinkHi",
                "seifuku.Tie_StringRed",
                "seifuku.Tie_StringRedHi",
                "seifuku.Tie_StringYellow",
                "seifuku.Tie_StringYellowHi",
                "seifuku.Tie_TriangleBlack",
                "seifuku.Tie_TriangleBlue",
                "seifuku.Tie_TriangleButterflyBlack",
                "seifuku.Tie_TriangleButterflyBlue",
                "seifuku.Tie_TriangleButterflyPink",
                "seifuku.Tie_TriangleButterflyRed",
                "seifuku.Tie_TriangleButterflyYellow",
                "seifuku.Tie_TrianglePink",
                "seifuku.Tie_TriangleRed",
                "seifuku.Tie_TriangleSmallBlack",
                "seifuku.Tie_TriangleSmallBlue",
                "seifuku.Tie_TriangleSmallPink",
                "seifuku.Tie_TriangleSmallRed",
                "seifuku.Tie_TriangleSmallYellow",
                "seifuku.Tie_TriangleYellow",
                "seifuku.TriangleTieBlack",
                "seifuku.TriangleTieBlue",
                "seifuku.TriangleTiePink",
                "seifuku.TriangleTieRed",
                "seifuku.TriangleTieYellow",
            },
        },
        ClothBody = {
            items = {
                "seifuku.FemaleUniform_Blazer2ButtonBeige",
                "seifuku.FemaleUniform_Blazer2ButtonBeigeCrest",
                "seifuku.FemaleUniform_Blazer2ButtonBeigeUnbtn",
                "seifuku.FemaleUniform_Blazer2ButtonBeigeUnbtnCrest",
                "seifuku.FemaleUniform_Blazer2ButtonBlack",
                "seifuku.FemaleUniform_Blazer2ButtonBlackCrest",
                "seifuku.FemaleUniform_Blazer2ButtonBlackUnbtn",
                "seifuku.FemaleUniform_Blazer2ButtonBlackUnbtnCrest",
                "seifuku.FemaleUniform_Blazer2ButtonBlue",
                "seifuku.FemaleUniform_Blazer2ButtonBlueCrest",
                "seifuku.FemaleUniform_Blazer2ButtonBlueUnbtn",
                "seifuku.FemaleUniform_Blazer2ButtonBlueUnbtnCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBeige",
                "seifuku.FemaleUniform_Blazer3ButtonBeigeCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBeigeUnbtn",
                "seifuku.FemaleUniform_Blazer3ButtonBeigeUnbtnCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBlack",
                "seifuku.FemaleUniform_Blazer3ButtonBlackCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBlackUnbtn",
                "seifuku.FemaleUniform_Blazer3ButtonBlackUnbtnCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBlue",
                "seifuku.FemaleUniform_Blazer3ButtonBlueCrest",
                "seifuku.FemaleUniform_Blazer3ButtonBlueUnbtn",
                "seifuku.FemaleUniform_Blazer3ButtonBlueUnbtnCrest",
                "seifuku.FemaleUniform_Sailor",
                "seifuku.FemaleUniform_SailorBlackBlack",
                "seifuku.FemaleUniform_SailorShortBlackBlack",
                "seifuku.FemaleUniform_Shirt",
                "seifuku.FemaleUniform_ShirtShort",
                "seifuku.FemaleUniform_SukumizuComp",
                "seifuku.FemaleUniform_SukumizuNewType",
                "seifuku.FemaleUniform_SukumizuWhiteComp",
                "seifuku.FemaleUniform_SukumizuWhiteNewType",
                "seifuku.FemaleUniform_SweaterBabyBlue",
                "seifuku.FemaleUniform_SweaterBeige",
                "seifuku.FemaleUniform_SweaterBlack",
                "seifuku.FemaleUniform_SweaterGrey",
                "seifuku.FemaleUniform_SweaterNavyBlue",
                "seifuku.FemaleUniform_SweaterShortBabyBlue",
                "seifuku.FemaleUniform_SweaterShortBeige",
                "seifuku.FemaleUniform_SweaterShortBlack",
                "seifuku.FemaleUniform_SweaterShortGrey",
                "seifuku.FemaleUniform_SweaterShortNavyBlue",
                "seifuku.GymUniform_Shirt",
                "seifuku.JacketCute",
                "seifuku.MaleUniform_Gakuran",
                "seifuku.MaleUniform_GakuranUnbtn",
                "seifuku.PonchoGura",
                "seifuku.PonchoGuraDOWN",
                "seifuku.SchoolUniform_Sukumizu",
                "seifuku.SchoolUniform_SukumizuWhite",
                "seifuku.SchoolUniform_Summer",
                "seifuku.SchoolUniform_Winter",
            },
        },
        ClothFeet = {
            items = {
                "seifuku.Shoes_Loafers",
                "seifuku.Shoes_Uwabaki",
                "seifuku.Stockings_CuteBlack",
                "seifuku.Stockings_CuteBlackSemiTrans",
                "seifuku.Stockings_CuteBlackTrans",
                "seifuku.Stockings_CuteWhite",
            },
        },
        ClothHead = {
            items = {
                "seifuku.Hat_CuteMask",
            },
        },
        ClothLeg = {
            items = {
                "seifuku.FemaleUniform_SkirtBlue",
                "seifuku.FemaleUniform_SkirtBlueShort",
                "seifuku.GymUniform_Bloomers",
                "seifuku.GymUniform_Shorts",
                "seifuku.MaleUniform_Sukumizu",
                "seifuku.MaleUniform_Trousers",
                "seifuku.MaleUniform_TrousersBlue",
                "seifuku.SchoolUniform_Skirt",
                "seifuku.SchoolUniform_SkirtMini",
            },
        },
    },
})
