--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: the original's SmallMod bundle.
-- A large grab-bag of small third-party mods (one guard each). See the mods
-- list below for the individual workshop IDs.
--
-- Two scoped rules replace unenumerable/format-breaking entries: all
-- Onifurniture.* items -> Furniture, and RDC_Z777's remote-door items (names
-- contain spaces) -> Electronics.
--
-- Kitsune's ammo bench (KACB/KMMCB/KMISCCB) re-uses Brita's reloading items;
-- they are listed here too (data + the GunPowder override) and deliberately
-- overlap the Arsenal-Brita pack, so the bench sorts them whether Brita is
-- installed or not. The engine resolves the overlap deterministically at boot.
--
-- Mappings migrated from Better Sorting (SmallMod_Items.lua), "Cont" ->
-- "Container".
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "SmallMod (misc mod support)",
    mods = { "4ColorBicPen", "4ColorBicPenFix", "ahzclothing", "1537876121", "AAS", "AnaLGiNs_RenewableFoodResources", "antiserum", "antiserum_beta", "AntiserumHC", "AntiserumHCSelfTestKit", "ArmoredVests", "AutoGate", "2211423190", "BCGRareWeapons", "BCGTools", "BedfordFalls", "BetterFlashlights", "Helicopter", "betterLockpicking", "zReBetterLockpicking", "TowingCar", "BogaPizza", "DBDA", "CanRepairDoors", "2207313208", "Computer", "ComputerClassicsGamePack", "ComputerCorporalsGamePack", "ComputerGTAGamePack", "CoolBag", "ttr-CorpseStudy", "CrashedCarsMod", "Defecation", "DrivingSkill", "eggonsFannyPackBalancing", "eggonsSharpenYourBlades", "EliazFitnessStrengthBooks", "EssentialCrafting", "ExamineCorpses", "ExamineCorpsesPLUS", "FencingKits", "ForScience", "FuelAPI", "FunctionalChainsaw", "icecreammaker", "ISA_41", "waterPipes", "KACB", "KMMCB", "KMISCCB", "LactoseCrossbow", "KCMcrossbowCompatibility", "Remastered Kitsune's Crossbow Mod Compatibility", "Ladders", "MANYBAGS", "MilPoncho", "MCM", "ToadTraits", "ToadTraitsDisablePrepared", "ToadTraitsDisableSpec", "nattachments", "Onifurniture", "PertsPartyTiles", "PlayerTraps", "PSurvival", "RadioToGrid", "SlingMod", "SAPPHEATER", "SavottaBackpacks", "ScavengingSkill", "SecretZ_v3", "SecretZ_v2", "SecretZ", "Silencer", "SimplePowderedMilk", "SkillRecoveryJournal", "PwSleepingbags", "SlingModFix", "smokinjoessmokes", "SpecialEmergencyVehiclesFRsm", "spraypaintEDIT", "tactorgsol", "RS_WaterCistern", "RS_WaterCistern_FR_Overwrite", "RS_WaterCistern_KI5_Addon", "TheyKnew", "DRK_1", "VehicleRepairOverhaul", "VPR_RecyclingCenter", "rSemiTruck", "WaterDispenser", "rWaterTrailer", "rWaterTrailerSemi", "MattSimpleAddonsFriuts", "XnerTree", "RDC_Z777" },
    rules = {
        { module = "Onifurniture", category = "Furn" },
        { contains = { "Master V2 Remote", "Master V3 Remote", "Remote Door Control" }, module = "Base", category = "Elec" },
    },
    overrides = {
        CraftAmmo = {
            items = {
                "Base.GunPowder",
            },
        },
    },
    data = {
        Ammo = {
            items = {
                "LactoseCrossbow.CrossbowBolt",
                "LactoseCrossbow.CrossbowBoltBundle",
                "LactoseCrossbow.CrossbowBolts",
                "LactoseCrossbow.LCCrossbowBoltAluminium",
                "LactoseCrossbow.LCCrossbowBoltAluminiumBundle",
            },
        },
        ClothAcc = {
            items = {
                "Base.SlingA",
                "Base.SlingAalt",
                "Base.SlingAalt2",
                "Base.SlingAalt3",
            },
        },
        ClothArm = {
            items = {
                "Base.ahzfitnessarms",
            },
        },
        ClothBack = {
            items = {
                "Base.AliceBackPack",
                "Base.AliceBackPackExtraPocket",
                "Base.AliceBackPackExtraPocket2",
                "Base.Bag_ALICEpack_Pink",
                "Base.Jaakari_L_Backpack",
                "Base.Jaakari_XL_Backpack",
                "Base.MilitaryAliceBackPack",
                "Base.MilitaryAliceBackPackExtraPocket",
                "MoreTraits.Bag_SmallHikingBag",
                "MoreTraits.PackerBag",
                "PrimitiveSurvival.PS_PrimitiveBag",
                "PrimitiveSurvival.PS_SheetBag",
                "TheyKnew.MysteriousSatchel",
            },
        },
        ClothBag = {
            items = {
                "Base.FannyPackXL",
                "Base.FannyPackXLBack",
                "Base.Interceptor_Pouches",
                "Base.Interceptor_Pouches_Straps",
                "Base.SportsFannyPack",
                "Base.SportsFannyPackBack",
            },
        },
        ClothBody = {
            items = {
                "Armor.Boilersuit_Flying",
                "Armor.HazmatSuit",
                "Armor.Vest_BulletArmy",
                "Armor.Vest_BulletCivilian",
                "Armor.Vest_BulletPolice",
                "Base.AnimeTshirt",
                "Base.Interceptor_Armor",
                "Base.Interceptor_Armor_s",
                "Base.Interceptor_Armor_v",
                "Base.Jacket_ATFclosed",
                "Base.Jacket_DEAclosed",
                "Base.Jacket_FBIlg",
                "Base.Jacket_FBIlgblack",
                "Base.Jacket_FBIlgblackconidFBI",
                "Base.Jacket_FBIlgconidfbi",
                "Base.Jacket_RIOTlgblack",
                "Base.Jacket_USMSHclosed",
                "Base.MPonchoBlackDOWN",
                "Base.MPonchoBlackUP",
                "Base.MPonchoGreenDOWN",
                "Base.MPonchoGreenUP",
                "Base.MPonchoShoulder",
                "Base.MPonchoShoulderBLA",
                "Base.MPonchoShoulderBLAdown",
                "Base.MPonchoShoulderDOWN",
                "Base.MPonchoShoulderYEL",
                "Base.MPonchoShoulderYELdown",
                "Base.MPonchoYellowDOWN",
                "Base.MPonchoYellowUP",
                "Base.Marpat_Jacket_d",
                "Base.Marpat_Jacket_w",
                "Base.Shirt_FormalWhiteFBIIDLG",
                "Base.Vest_BulletRIOTlggeneric",
                "Base.Vest_BulletRiotLG",
                "Base.Vest_Bulletfbi",
                "Base.Vest_BulletfbiRIOTLg",
                "Base.Vest_Bulletfbigreen",
                "Base.ahztoplongsleeve",
                "Base.ahztoplongsleevecut",
                "MoreTraits.AntiqueJacket",
                "MoreTraits.AntiqueVest",
                "RotatorsClothing.TShirt_RotatorsBlack",
                "TheyKnew.MysteriousHazmat",
            },
        },
        ClothFeet = {
            items = {
                "Base.ahzfitnesssocks",
                "MoreTraits.AntiqueBoots",
            },
        },
        ClothHead = {
            items = {
                "Armor.Hat_BalaclavaFace",
                "Armor.Hat_BalaclavaFull",
                "Armor.Hat_GasMask",
                "Armor.Hat_NBCmask",
                "Armor.Hat_SPHhelmet",
                "Base.Hat_BaseballCapATF",
                "Base.Hat_BaseballCapATF_Reverse",
                "Base.Hat_BaseballCapDEA",
                "Base.Hat_BaseballCapDEA_Reverse",
                "Base.Hat_BaseballCapFBILG",
                "Base.Hat_BaseballCapFBILG_Reverse",
                "Base.Hat_HardHat_Miner_With_Light",
                "Base.Hat_PASGT_Helmet",
                "Base.Hat_TPASGT_Helmet",
                "Base.Hat_USMC_Cap_d",
                "Base.Hat_USMC_Cap_w",
                "Base.Hat_blackRiotHelmetfbilg",
                "RotatorsClothing.Hat_BaseballCapRotators",
                "RotatorsClothing.Hat_BaseballCapRotators_Reverse",
            },
        },
        ClothLeg = {
            items = {
                "Base.Marpat_Pants_d",
                "Base.Marpat_Pants_w",
                "Base.Trousers_PoliceRiotfbilg",
                "Base.ahzfitnesspants",
                "Base.ahzpleatedminiskirt",
                "Base.ahzpleatedminiskirt_t",
                "Base.ahzpleatedminiskirt_t_plaid1",
                "Base.ahzpleatedminiskirt_t_plaid2",
                "Base.ahzshortpleatedskirt",
                "Base.ahzshortpleatedskirt_close",
                "Base.ahzshortpleatedskirt_t",
                "Base.ahzshortpleatedskirt_t_close",
                "Base.ahzshortpleatedskirt_t_plaid1",
                "Base.ahzshortpleatedskirt_t_plaid1_close",
                "Base.ahzshortpleatedskirt_t_plaid2",
                "Base.ahzshortpleatedskirt_t_plaid2_close",
            },
        },
        ClothUnder = {
            items = {
                "Base.ahzfitnessbra",
                "Base.ahzuwhighwaist_t",
                "Base.ahzuwtightsshort",
            },
        },
        Container = {
            items = {
                "FuelAPI.LargePetrolCan",
                "LactoseCrossbow.LCQuiver",
                "WaterDispenser.WaterJugEmpty",
                "WaterDispenser.WaterJugWaterFull",
                "tactorgsol.tactorgsol_admin",
                "tactorgsol.tactorgsol_large",
                "tactorgsol.tactorgsol_medium",
                "tactorgsol.tactorgsol_small",
            },
        },
        Cook = {
            items = {
                "ANL.DriedSugarBeets",
                "ANL.DryJarOfYeast",
                "ANL.JarOfCrushedBerries",
                "ANL.JarOfVinegarBase",
                "ANL.JarOfYeast",
                "ANL.WildYeastBase",
            },
        },
        Craft = {
            items = {
                "ANL.SmallSaltRock",
                "AxeRecrafting.AxeHandle",
                "AxeRecrafting.FireAxeHead",
                "AxeRecrafting.HandAxeHead",
                "AxeRecrafting.MetalAxeHandle",
                "AxeRecrafting.WoodAxeHead",
                "Base.GlassMold",
                "Base.GlassPane",
                "Base.GlassShard",
                "PrimitiveSurvival.PS_BarkStrip",
                "PrimitiveSurvival.PS_BranchesBundle",
                "PrimitiveSurvival.PS_SmallRope",
            },
        },
        CraftAmmo = {
            items = {
                "Base.Lead00Buck_Pack",
                "Base.Lead30_Pack",
                "Base.Lead38_Pack",
                "Base.Lead44_Pack",
                "Base.Lead45_Pack",
                "Base.Lead50_Pack",
                "Base.Lead545_Pack",
                "Base.Lead556_Pack",
                "Base.Lead57_Pack",
                "Base.Lead9_Pack",
                "Base.PrimerLG_Pack",
                "Base.PrimerSG_Pack",
                "Base.PrimerSM_Pack",
            },
        },
        CraftElec = {
            items = {
                "AutoGate.GateComponents",
            },
        },
        CraftMetal = {
            items = {
                "FencingKit.ChainWireRoll",
                "FencingKit.FenceKit",
            },
        },
        CraftTailor = {
            items = {
                "Base.ExtraPocket",
                "Base.NATT_AlicepackNonPouch",
                "Base.NATT_AlicepackPouch",
                "Base.NATT_Bedroll",
                "Base.NATT_Container",
                "Base.NATT_ContainerSmallLeft",
                "Base.NATT_ContainerSmallRight",
                "Base.NATT_Flashlight",
                "Base.NATT_Left",
                "Base.NATT_Remove_Bedroll",
                "Base.NATT_Remove_Container",
                "Base.NATT_Remove_ContainerSmallLeft",
                "Base.NATT_Remove_ContainerSmallRight",
                "Base.NATT_Remove_Flashlight",
                "Base.NATT_Remove_Left",
                "Base.NATT_Remove_Right",
                "Base.NATT_Remove_ShortWeapon",
                "Base.NATT_Remove_UtilityLeft",
                "Base.NATT_Remove_UtilityRight",
                "Base.NATT_Remove_Weapon",
                "Base.NATT_Right",
                "Base.NATT_ShortWeapon",
                "Base.NATT_UtilityLeft",
                "Base.NATT_UtilityRight",
                "Base.NATT_Weapon",
            },
        },
        Drugs = {
            items = {
                "Base.CartonOfSmokes",
                "Base.PackOfSmokes",
                "CigaretteMod.CigaretteCarton",
                "CigaretteMod.CigarettesOne",
            },
        },
        Elec = {
            items = {
                "AutoGate.GateController",
                "ISA.DIYBattery",
                "ISA.DeepCycleBattery",
                "ISA.ISAInverter",
                "ISA.PowerBank",
                "ISA.SolarFailsafe",
                "ISA.SolarPanel",
                "ISA.SolarPanelFlat",
                "ISA.SolarPanelMounted",
                "ISA.SolarPanelWall",
                "ISA.SuperBattery",
                "ISA.WiredCarBattery",
                "SAPPHEATER.ElectricHeater",
                "SAPPHEATER.HeaterCircuit",
                "SAPPHEATER.OutdoorHeater",
                "SAPPHEATER.SmallHeater",
                "rat.HamRadio1Grid",
                "rat.HamRadio2Grid",
                "rat.HamRadioMakeShiftGrid",
                "rat.RadioBlackGrid",
                "rat.RadioMakeShiftGrid",
                "rat.RadioRedGrid",
                "rat.WalkieTalkie1Grid",
                "rat.WalkieTalkie2Grid",
                "rat.WalkieTalkie3Grid",
                "rat.WalkieTalkie4Grid",
                "rat.WalkieTalkie5Grid",
                "rat.WalkieTalkieMakeShiftGrid",
            },
        },
        FoodB = {
            items = {
                "AAS.CocaCola",
                "AAS.CocaColaBox",
                "AAS.DietCoke",
                "AAS.DietCokeBox",
                "AAS.DrPepper",
                "AAS.DrPepperBox",
                "AAS.FantaGrape",
                "AAS.FantaGrapeBox",
                "AAS.GingerAle",
                "AAS.GingerAleBox",
                "AAS.MountainDew",
                "AAS.MountainDewBox",
                "AAS.Pepsi",
                "AAS.PepsiBox",
                "AAS.RCCola",
                "AAS.RCColaBox",
                "AAS.RootBeer",
                "AAS.RootBeerBox",
                "ANL.WildBerryWine",
                "BogaPizza.RumFull",
                "FuelAPI.LargePetrolCanWater",
                "MoreTraits.BloodBox",
            },
        },
        FoodN = {
            items = {
                "Base.fhqPowderedMilkPouch",
                "BogaPizza.BBQSauce",
                "BogaPizza.WhiteSauce",
                "icecreammaker.IceCreamMix",
                "icecreammaker.IceCreamMixCaramel",
                "icecreammaker.IceCreamMixCookieDough",
                "icecreammaker.IceCreamMixCookiesCreme",
                "icecreammaker.IceCreamMixStrawberry",
            },
        },
        FoodP = {
            items = {
                "ANL.GratedBerries",
                "ANL.SlicedSugarBeets",
                "ANL.SugarBeet",
                "BogaPizza.ChiliPepper",
                "BogaPizza.DicedPineapple",
                "BogaPizza.NdujaSausage",
                "BogaPizza.NdujaSausageSlice",
                "BogaPizza.PizzaCheese",
                "BogaPizza.PizzaDough",
                "BogaPizza.PizzaEtna",
                "BogaPizza.PizzaHamMushroom",
                "BogaPizza.PizzaHawaii",
                "BogaPizza.PizzaNduja",
                "BogaPizza.PizzaPineapple",
                "BogaPizza.PizzaRumHam",
                "BogaPizza.PizzaSauced",
                "BogaPizza.PizzaSeafood",
                "BogaPizza.RumHam",
                "BogaPizza.RumHamSlice",
                "Bottling.BottlingBacon",
                "Bottling.BottlingBaconBits",
                "Bottling.BottlingBaconRashers",
                "Bottling.BottlingChicken",
                "Bottling.BottlingFrogMeat",
                "Bottling.BottlingHam",
                "Bottling.BottlingMeatPatty",
                "Bottling.BottlingMuttonChop",
                "Bottling.BottlingPorkChop",
                "Bottling.BottlingRabbitmeat",
                "Bottling.BottlingSmallanimalmeat",
                "Bottling.BottlingSmallbirdmeat",
                "Bottling.BottlingSteak",
                "BottlingFish.BottlingFishFillet",
                "BottlingFish.BottlingSalmon",
                "MattSimpleAddons.MSABlackBerries",
                "MattSimpleAddons.MSABlack_Cherry",
                "MattSimpleAddons.MSAMulberry",
                "MattSimpleAddons.MSARaspberries",
                "MattSimpleAddons.MSAmerican_Plumb",
                "MoreTraits.ZombPatty",
                "icecreammaker.ConeCaramel",
                "icecreammaker.ConeChocolate",
                "icecreammaker.ConeCookieDough",
                "icecreammaker.ConeCookiesCreme",
                "icecreammaker.ConeStrawberry",
                "icecreammaker.IceCreamCaramel",
                "icecreammaker.IceCreamChocolate",
                "icecreammaker.IceCreamCookieDough",
                "icecreammaker.IceCreamCookiesCreme",
                "icecreammaker.IceCreamStrawberry",
            },
        },
        Fuel = {
            items = {
                "FuelAPI.LargePetrolCanFull",
                "WaterDispenser.WaterJugPetrolFull",
            },
        },
        Furn = {
            items = {
                "Ladders.SteelLadder",
                "Ladders.WoodenLadder",
                "SZ.Mov_Barrier01",
                "SZ.Mov_SecurityTerminal",
            },
        },
        Junk = {
            items = {
                "AAS.CocaColaEmpty",
                "AAS.CrushedCan",
                "AAS.DietCokeEmpty",
                "AAS.DrPepperEmpty",
                "AAS.FantaGrapeEmpty",
                "AAS.GingerAleEmpty",
                "AAS.MountainDewEmpty",
                "AAS.PepsiEmpty",
                "AAS.RCColaEmpty",
                "AAS.RootBeerEmpty",
            },
        },
        Key = {
            items = {
                "SZ.Key_BlackCard",
                "SZ.Key_BlueCard",
                "SZ.Key_GreenCard",
                "SZ.Key_RedCard",
                "SZ.Key_SystemL0",
                "SZ.Key_YellowCard",
            },
        },
        LitC = {
            items = {
                "Base.BedfordMap",
                "ISA.Stash_Louisville1",
                "ISA.Stash_RiversideW1",
                "ISA.Stash_RosewoodE1",
                "SZ.Bunker01",
                "SZ.Bunker02",
                "SZ.Bunker03",
                "SZ.Bunker04",
                "SZ.TopSecret",
                "SZ.TopSecret2",
                "SZ.TopSecret3",
                "SZ.labmap1",
                "SZ.opmap1",
                "SZ.opmap2",
                "SZ.opmap3",
            },
        },
        LitE = {
            items = {
                "DBDA.Carrie",
                "DBDA.Cujo",
                "DBDA.DBDA1",
                "DBDA.DBDA2",
                "DBDA.DBDA3",
                "DBDA.DBDA4",
                "DBDA.Doc",
                "DBDA.Dream",
                "DBDA.Green",
                "DBDA.It",
                "DBDA.Mist",
                "DBDA.Out",
                "DBDA.Pet",
                "DBDA.Shine",
                "DBDA.Stand",
                "DBDA.TW",
                "DBDA.TWSR",
                "DBDA.Who",
            },
        },
        LitR = {
            items = {
                "AI_HELI.HeliMag",
                "ANL.AnlRenewMag1",
                "ANL.AnlRenewMag2",
                "AutoGate.AutoGateMag",
                "Base.Lyman49th_Manual",
                "Base.RDCZHijackingMagazineVol1",
                "BetLock.AlarmMag",
                "BetLock.LockpickingMag",
                "ESYB.MagazineAllAboutBladeBevels",
                "ESYB.MagazineHomemadeGrindingTools",
                "ESYB.MagazineJapaneseMastersSpecialEdition",
                "ESYB.MagazineTableGrinderUserManual",
                "ESYB.MagazineTypicalSharpeningMistakes",
                "ExamineCorpse.nmMedicalMagazine1",
                "ExamineCorpse.nmMedicalMagazine2",
                "ISA.ISAMag1",
                "MoreTraits.AntiqueMag1",
                "MoreTraits.AntiqueMag2",
                "MoreTraits.AntiqueMag3",
                "MoreTraits.MedicalMag1",
                "MoreTraits.MedicalMag2",
                "MoreTraits.MedicalMag3",
                "MoreTraits.MedicalMag4",
            },
        },
        LitS = {
            items = {
                "Base.BookElectricManual",
                "Base.BookFitness1",
                "Base.BookFitness2",
                "Base.BookFitness3",
                "Base.BookFitness4",
                "Base.BookFitness5",
                "Base.BookMedicalJournal",
                "Base.BookStrength1",
                "Base.BookStrength2",
                "Base.BookStrength3",
                "Base.BookStrength4",
                "Base.BookStrength5",
                "Base.SkillRecoveryJournal",
                "DrivingSkill.DrivingSkill_BookDriving1",
                "DrivingSkill.DrivingSkill_BookDriving2",
                "DrivingSkill.DrivingSkill_BookDriving3",
                "DrivingSkill.DrivingSkill_BookDriving4",
                "DrivingSkill.DrivingSkill_BookDriving5",
                "ScavengerSkill.ScavengerSkill_BookScavenging1",
                "ScavengerSkill.ScavengerSkill_BookScavenging2",
                "ScavengerSkill.ScavengerSkill_BookScavenging3",
                "ScavengerSkill.ScavengerSkill_BookScavenging4",
                "ScavengerSkill.ScavengerSkill_BookScavenging5",
            },
        },
        LitW = {
            items = {
                "BicPen.BicPen",
            },
        },
        Mech = {
            items = {
                "Base.10000_Water_Tank1",
                "Base.10000_Water_Tank2",
                "Base.10000_Water_Tank3",
                "Base.1500_Water_Tank1",
                "Base.1500_Water_Tank2",
                "Base.1500_Water_Tank3",
                "Base.3000_Water_Tank1",
                "Base.3000_Water_Tank2",
                "Base.3000_Water_Tank3",
                "Base.3000_Water_Tank_Tainted1",
                "Base.3000_Water_Tank_Tainted2",
                "Base.3000_Water_Tank_Tainted3",
                "Base.BigTrunk0",
                "Base.FRSideContainer_RS1",
                "Base.FRSideContainer_RS2",
                "Base.FRSideContainer_RS3",
                "Base.FrontCarDoor0",
                "Base.GloveBox0",
                "Base.NormalTrunk0",
                "Base.RS_WaterFilter",
                "Base.SmallTrunk0",
                "Base.TrunkDoor0",
                "Rotators.750Tank2",
                "Rotators.AxleModernTire2",
                "Rotators.AxleNormalTire2",
                "Rotators.AxleOldTire2",
                "Rotators.DoubleModernTire2",
                "Rotators.DoubleNormalTire2",
                "Rotators.DoubleOldTire2",
                "Rotators.SemiTruckArmorDoor_Item2",
                "Rotators.SemiTruckArmorFront_Item2",
                "Rotators.SemiTruckArmorRear_Item2",
                "Rotators.SemiTruckBullbar_Item2",
                "Rotators.WaterTrailerTankFilter2",
                "Rotators.WaterTrailerTankLid1",
                "Rotators.WaterTrailerTankLid2",
                "Rotators.WaterTrailerTankPump1",
                "Rotators.WaterTrailerTankPump2",
            },
        },
        Med = {
            items = {
                "Antiserum.AntiserumChemicalWorkstation",
                "Antiserum.AntiserumChemicals",
                "Antiserum.AntiserumCure",
                "Antiserum.AntiserumEmptyInjector",
                "Antiserum.AntiserumEmptyInjectorPack",
                "Antiserum.AntiserumJournalOfResearch",
                "Antiserum.AntiserumSample",
                "Antiserum.AntiserumStrong",
                "Antiserum.AntiserumTestTube",
                "Antiserum.AntiserumTestTubePack",
                "Antiserum.AntiserumUsedInjector",
                "Antiserum.AntiserumWeak",
                "AntiserumTestKit.AntiserumTestKit",
                "CorpseStudyMod.MedicalJournal",
                "Defecation.AntiDiarrhealPill",
                "Defecation.AntiDiarrhealPillBox",
                "ExamineCorpse.nmMedicalStudiesJournal",
                "MoreTraits.ZombificationCure",
                "TheyKnew.Zomboxivir",
                "TheyKnew.Zomboxycycline",
            },
        },
        MediaG = {
            items = {
                "Computer.Disc_Game",
            },
        },
        Misc = {
            items = {
                "Base.CrazedRamblings",
                "Base.CrazedRamblings2",
                "Base.CrazedRamblings3",
                "Base.CrazedRamblings4",
                "Base.JarLidBoxs",
                "LactoseCrossbow.LCTestAttachment",
                "MoreTraits.PapierMache",
            },
        },
        SurCamp = {
            items = {
                "Base.Sleepingbag",
                "Base.SleepingbagBK",
                "Base.SleepingbagBKRolled",
                "Base.SleepingbagG",
                "Base.SleepingbagGRolled",
                "Base.SleepingbagLB",
                "Base.SleepingbagLBRolled",
                "Base.SleepingbagO",
                "Base.SleepingbagORolled",
                "Base.SleepingbagP",
                "Base.SleepingbagPRolled",
                "Base.SleepingbagR",
                "Base.SleepingbagRRolled",
                "Base.SleepingbagRolled",
                "PrimitiveSurvival.PS_TwigsBundle",
            },
        },
        SurFarm = {
            items = {
                "ANL.SugarBeetBagSeed",
                "ANL.SugarBeetSeed",
                "Defecation.HumanFeces",
                "MCM.AvocadoBagSeed",
                "MCM.Avocadoseed",
                "MCM.CornBagSeed",
                "MCM.Cornseed",
                "MCM.EggplantBagSeed",
                "MCM.Eggplantseed",
                "MCM.LeekBagSeed",
                "MCM.Leekseed",
                "MCM.LettuceBagSeed",
                "MCM.Lettuceseed",
                "MCM.OnionBagSeed",
                "MCM.Onionseed",
                "MCM.PepperBagSeed",
                "MCM.Pepperseed",
                "MCM.WatermelonBagSeed",
                "MCM.Watermelonseed",
                "MCM.ZucchiniBagSeed",
                "MCM.Zucchiniseed",
                "XNTree.XNSaplingApple",
                "XNTree.XNSaplingBanana",
                "XNTree.XNSaplingCherry",
                "XNTree.XNSaplingLemon",
                "XNTree.XNSaplingOrange",
                "XNTree.XNSaplingPeach",
                "XNTree.XNSaplingPineapple",
                "waterPipes.WaterPipe",
                "waterPipes.WaterPipe2",
            },
        },
        SurTrap = {
            items = {
                "Trap.BearTrap",
                "Trap.BearTrapClosed",
                "Trap.PropaneTrap",
                "Trap.SpikeTrap",
                "Trap.SpikeTrapClosed",
            },
        },
        Tool = {
            items = {
                "Base.BF_EgenerexLite",
                "Base.BF_HeadLight",
                "Base.BF_OldFlashlight",
                "Base.BF_SpiffoLite",
                "Base.DoorsRepairKitEpoxy",
                "Base.DoorsRepairKitMetal",
                "Base.DoorsRepairKitWood",
                "Base.EmptyLighter",
                "Base.HandTorch_Army1",
                "Base.HandTorch_Army2",
                "Base.HandTorch_CK_LED",
                "Base.HandTorch_ManLite",
                "Base.IcePocket",
                "Base.Lee_LoadMaster",
                "Base.LighterEmpty",
                "Base.LighterFluid",
                "Base.Lyman_TMag",
                "Base.PlasticLighter_Black",
                "Base.PlasticLighter_Blue",
                "Base.PlasticLighter_Green",
                "Base.PlasticLighter_Orange",
                "Base.PlasticLighter_Purple",
                "Base.PlasticLighter_Red",
                "Base.PlasticLighter_Yellow",
                "Base.Torch1",
                "Base.Torch2",
                "Base.Torch3",
                "Base.Torch4",
                "Base.Torch5",
                "Base.Torch6",
                "Base.Torch7",
                "Base.TorchArmy1",
                "Base.TorchArmy2",
                "Base.WaterPocket",
                "BetLock.BobbyPin",
                "BetLock.HandmadeBobbyPin",
                "ESYB.HomemadeWhetstone",
                "ESYB.Sandstone",
                "ESYB.TableGrinder",
                "ESYB.TableGrinderWithoutWheels",
                "ESYB.Whetstone",
                "FixAFlat.FixAFlat",
                "Ftool.Chainsaw",
                "MoreTraits.AntiqueHammer",
                "MoreTraits.BloodyCrowbar",
                "MoreTraits.Thumper",
                "TowingCar.TowBar",
                "spraypaint.ChalkBlue",
                "spraypaint.ChalkCyan",
                "spraypaint.ChalkGreen",
                "spraypaint.ChalkOrange",
                "spraypaint.ChalkRed",
                "spraypaint.ChalkViolet",
                "spraypaint.ChalkWhite",
                "spraypaint.ChalkYellow",
                "spraypaint.SpraycanBlack",
                "spraypaint.SpraycanBlue",
                "spraypaint.SpraycanCyan",
                "spraypaint.SpraycanGreen",
                "spraypaint.SpraycanOrange",
                "spraypaint.SpraycanRed",
                "spraypaint.SpraycanViolet",
                "spraypaint.SpraycanWhite",
                "spraypaint.SpraycanYellow",
            },
        },
        WepBow = {
            items = {
                "LactoseCrossbow.CrossbowStrungNylon",
                "LactoseCrossbow.CrossbowStrungSteel",
                "LactoseCrossbow.CrossbowStrungString",
                "LactoseCrossbow.ModernCrossbowStrungNylon",
                "LactoseCrossbow.ModernCrossbowStrungSteel",
                "LactoseCrossbow.ModernCrossbowStrungString",
            },
        },
        WepFire = {
            items = {
                "Base.AZZK_pistol",
                "SZ.BCS_Pistol",
                "SZ.BCS_Shotgun",
                "SZ.Barrys_Shotgun",
                "SZ.Garrys_44",
            },
        },
        WepMelee = {
            items = {
                "BCGRareWeapons.ReinforcedBaseballBat",
                "BCGRareWeapons.VikingAxe",
                "BCGTools.CheapSurvivalKnife",
                "BCGTools.HandHatchet",
                "BCGTools.KukriMachete",
                "BCGTools.RancherMachete",
                "BCGTools.SpearCheapSurvivalKnife",
                "BCGTools.SpearSurvivalKnife",
                "BCGTools.SplittingAxe",
                "BCGTools.SurvivalKnife",
                "Base.BatLeth",
                "Base.MekLeth",
                "Base.OverlookFireAxe",
                "BicPen.ComicBicPen",
                "MoreTraits.AntiqueAxe",
                "MoreTraits.AntiqueKatana",
                "MoreTraits.AntiqueSpear",
                "MoreTraits.ObsidianBlade",
                "MoreTraits.PapierMacheSword",
                "MoreTraits.Slugger",
            },
        },
        WepPart = {
            items = {
                "LactoseCrossbow.CrossbowStringNylon",
                "LactoseCrossbow.CrossbowStringSteel",
                "LactoseCrossbow.CrossbowStringString",
                "LactoseCrossbow.CrossbowUnstrung",
                "LactoseCrossbow.ModernCrossbowUnstrung",
                "Silencer.HMSilencer",
                "Silencer.Silencer",
            },
        },
    },
})
