--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Spongie's clothing & open jackets.
-- Clothing (mod items and vanilla open/roll/tuck variants added by
-- the mods) sorted into the Clothing sub-categories.
--
-- Covers (one guard per mod in the original):
--   SpongiesClothing (SpnCloth, SpnClothVanilla) — https://steamcommunity.com/sharedfiles/filedetails/?id=2684285534
--   Spongie's Open Jackets (SpnOpenCloth) — https://steamcommunity.com/sharedfiles/filedetails/?id=2812326159
--
-- Mappings migrated from Better Sorting (Spongie_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "Spongie",
    mods = { "SpnCloth", "SpnClothVanilla", "SpnOpenCloth" },
    data = {
        ClothArm = {
            items = {
                "Spongie.Gloves_LeatherFingerless",
                "Spongie.Gloves_MilitaryFingerless",
                "Spongie.Gloves_StripedLong",
            },
        },
        ClothBody = {
            items = {
                "Base.BoilersuitOPEN",
                "Base.Boilersuit_BlueRedOPEN",
                "Base.Boilersuit_FlyingOPEN",
                "Base.Boilersuit_PrisonerKhakiOPEN",
                "Base.Boilersuit_PrisonerOPEN",
                "Base.Boilersuit_YellowOPEN",
                "Base.HoodieDOWN_WhiteTINTOPEN",
                "Base.HoodieUP_WhiteTINTOPEN",
                "Base.JacketLong_DoctorOPEN",
                "Base.JacketLong_RandomOPEN",
                "Base.JacketLong_SantaGreenOPEN",
                "Base.JacketLong_SantaOPEN",
                "Base.Jacket_ArmyCamoDesertOPEN",
                "Base.Jacket_ArmyCamoGreenOPEN",
                "Base.Jacket_BlackOPEN",
                "Base.Jacket_BlackVest",
                "Base.Jacket_BlackVestOPEN",
                "Base.Jacket_ChefOPEN",
                "Base.Jacket_CoatArmyOPEN",
                "Base.Jacket_FiremanOPEN",
                "Base.Jacket_LeatherBarrelDogsOPEN",
                "Base.Jacket_LeatherBarrelDogsVest",
                "Base.Jacket_LeatherBarrelDogsVestOPEN",
                "Base.Jacket_LeatherIronRodentOPEN",
                "Base.Jacket_LeatherIronRodentVest",
                "Base.Jacket_LeatherIronRodentVestOPEN",
                "Base.Jacket_LeatherWildRacoonsOPEN",
                "Base.Jacket_LeatherWildRacoonsVest",
                "Base.Jacket_LeatherWildRacoonsVestOPEN",
                "Base.Jacket_PoliceOPEN",
                "Base.Jacket_RangerOPEN",
                "Base.Jacket_Shellsuit_BlackOPEN",
                "Base.Jacket_Shellsuit_BlueOPEN",
                "Base.Jacket_Shellsuit_GreenOPEN",
                "Base.Jacket_Shellsuit_PinkOPEN",
                "Base.Jacket_Shellsuit_TINTOPEN",
                "Base.Jacket_Shellsuit_TealOPEN",
                "Base.Jacket_VarsityOPEN",
                "Base.Jacket_WhiteOPEN",
                "Base.Jumper_DiamondPatternTINTTIED",
                "Base.Jumper_PoloNeckTIED",
                "Base.Jumper_RoundNeckTIED",
                "Base.Jumper_VNeckTIED",
                "Base.Shirt_Baseball_KYOPEN",
                "Base.Shirt_Baseball_RangersOPEN",
                "Base.Shirt_Baseball_ZOPEN",
                "Base.Shirt_Bowling_BlueOPEN",
                "Base.Shirt_Bowling_BrownOPEN",
                "Base.Shirt_Bowling_GreenOPEN",
                "Base.Shirt_Bowling_LimeGreenOPEN",
                "Base.Shirt_Bowling_PinkOPEN",
                "Base.Shirt_Bowling_WhiteOPEN",
                "Base.Shirt_CamoDesertOPEN",
                "Base.Shirt_CamoDesertOPENROLLOPEN",
                "Base.Shirt_CamoDesertROLL",
                "Base.Shirt_CamoGreenOPEN",
                "Base.Shirt_CamoGreenOPENROLL",
                "Base.Shirt_CamoGreenROLL",
                "Base.Shirt_CamoUrbanOPEN",
                "Base.Shirt_CamoUrbanOPENROLL",
                "Base.Shirt_CamoUrbanROLL",
                "Base.Shirt_DenimOPEN",
                "Base.Shirt_DenimOPENROLL",
                "Base.Shirt_DenimROLL",
                "Base.Shirt_FormalTINTOPEN",
                "Base.Shirt_FormalTINTOPENROLL",
                "Base.Shirt_FormalTINTROLL",
                "Base.Shirt_FormalWhiteOPEN",
                "Base.Shirt_FormalWhiteOPENROLL",
                "Base.Shirt_FormalWhiteROLL",
                "Base.Shirt_FormalWhite_ShortSleeveOPEN",
                "Base.Shirt_FormalWhite_ShortSleeveTINTOPEN",
                "Base.Shirt_HawaiianRedOPEN",
                "Base.Shirt_HawaiianTINTOPEN",
                "Base.Shirt_Jockey01OPEN",
                "Base.Shirt_Jockey01OPENROLL",
                "Base.Shirt_Jockey01ROLL",
                "Base.Shirt_Jockey02OPEN",
                "Base.Shirt_Jockey02OPENROLL",
                "Base.Shirt_Jockey02ROLL",
                "Base.Shirt_Jockey03OPEN",
                "Base.Shirt_Jockey03OPENROLL",
                "Base.Shirt_Jockey03ROLL",
                "Base.Shirt_Jockey04OPEN",
                "Base.Shirt_Jockey04OPENROLL",
                "Base.Shirt_Jockey04ROLL",
                "Base.Shirt_Jockey05OPEN",
                "Base.Shirt_Jockey05OPENROLL",
                "Base.Shirt_Jockey05ROLL",
                "Base.Shirt_Jockey06OPEN",
                "Base.Shirt_Jockey06OPENROLL",
                "Base.Shirt_Jockey06ROLL",
                "Base.Shirt_LumberjackOPEN",
                "Base.Shirt_LumberjackOPENROLL",
                "Base.Shirt_LumberjackROLL",
                "Base.Shirt_OfficerWhiteOPEN",
                "Base.Shirt_OfficerWhiteOPENROLL",
                "Base.Shirt_OfficerWhiteROLL",
                "Base.Shirt_PoliceBlueOPEN",
                "Base.Shirt_PoliceBlueOPENROLL",
                "Base.Shirt_PoliceBlueROLL",
                "Base.Shirt_PoliceGreyOPEN",
                "Base.Shirt_PoliceGreyOPENROLL",
                "Base.Shirt_PoliceGreyROLL",
                "Base.Shirt_PriestOPEN",
                "Base.Shirt_PriestOPENROLL",
                "Base.Shirt_PriestROLL",
                "Base.Shirt_PrisonGuardOPEN",
                "Base.Shirt_PrisonGuardOPENROLL",
                "Base.Shirt_PrisonGuardROLL",
                "Base.Shirt_RangerOPEN",
                "Base.Shirt_RangerOPENROLL",
                "Base.Shirt_RangerROLL",
                "Base.Shirt_ScrubsROLL",
                "Base.Shirt_WorkmanOPEN",
                "Base.Shirt_WorkmanOPENROLL",
                "Base.Shirt_WorkmanROLL",
                "Base.Suit_JacketOPEN",
                "Base.Suit_JacketTINTOPEN",
                "Base.Tshirt_PoliceBlueOPEN",
                "Base.Tshirt_PoliceGreyOPEN",
                "Base.Tshirt_RangerOPEN",
                "Base.Tshirt_WhiteLongSleeveROLL",
                "Base.Tshirt_WhiteLongSleeveTINTROLL",
                "Base.WeddingJacketOPEN",
                "Spongie.Jacket_Bomber",
                "Spongie.Jacket_BomberOPEN",
                "Spongie.Jacket_Denim",
                "Spongie.Jacket_DenimOPEN",
                "Spongie.Jacket_Field",
                "Spongie.Jacket_FieldOPEN",
                "Spongie.Jacket_Flight",
                "Spongie.Jacket_FlightOPEN",
                "Spongie.Jacket_FlightVest",
                "Spongie.Jacket_FlightVestOPEN",
                "Spongie.Jacket_PoliceArmor",
                "Spongie.Jacket_PoliceArmorLong",
                "Spongie.Jacket_SheepWool",
                "Spongie.Jacket_SheepWoolOPEN",
                "Spongie.Jacket_WinterCoat",
                "Spongie.Jacket_WinterCoatDOWN",
                "Spongie.Jumper_Military",
                "Spongie.Jumper_MilitaryTIED",
                "Spongie.Jumper_TurtleVest",
                "Spongie.TShirt_Compression",
                "Spongie.TShirt_CompressionLong",
                "Spongie.Vest_Waterproof",
            },
        },
        ClothLeg = {
            items = {
                "Base.TrousersMesh_DenimLightTUCK",
                "Base.TrousersTUCK",
                "Base.Trousers_ArmyServiceTUCK",
                "Base.Trousers_BlackTUCK",
                "Base.Trousers_CamoDesertTUCK",
                "Base.Trousers_CamoGreenTUCK",
                "Base.Trousers_CamoUrbanTUCK",
                "Base.Trousers_ChefTUCK",
                "Base.Trousers_DenimTUCK",
                "Base.Trousers_FiremanTUCK",
                "Base.Trousers_JeanBaggyTUCK",
                "Base.Trousers_LeatherBlackTUCK",
                "Base.Trousers_NavyBlueTUCK",
                "Base.Trousers_PaddedTUCK",
                "Base.Trousers_PoliceGreyTUCK",
                "Base.Trousers_PoliceTUCK",
                "Base.Trousers_PrisonGuardTUCK",
                "Base.Trousers_RangerTUCK",
                "Base.Trousers_ScrubsTUCK",
                "Base.Trousers_SuitTUCK",
                "Base.Trousers_SuitWhiteTUCK",
                "Base.Trousers_WhiteTINTTUCK",
                "Spongie.Shorts_Spandex",
                "Spongie.Shorts_SpandexLong",
            },
        },
    },
})
