--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Video Game Consoles.
-- Consoles, handhelds and every game cartridge -> Electronics.
--
-- Covers:
--   Video_Game_Consoles (Video Game Consoles)
--   — https://steamcommunity.com/sharedfiles/filedetails/?id=2831786301
--   VGC_Addon_GameBoyGames (Addon - More Game Boy Games)
--   — https://steamcommunity.com/sharedfiles/filedetails/?id=2949768076
--
-- The addon is a separate Workshop item but only ever adds cartridges for the
-- base mod's Game Boy, so both IDs share one pack: with a single mod active the
-- other's items simply do not exist and are skipped at boot.
--
-- Mappings migrated from Better Sorting v2.0.4 (VideoGameConsoles_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "VideoGameConsoles",
    mods = { "Video_Game_Consoles", "VGC_Addon_GameBoyGames" },
    data = {
        Elec = {
            items = {
                "VGC_Addon_GameBoyGames.GB_Cartridge_Alleyway",
                "VGC_Addon_GameBoyGames.GB_Cartridge_AvengingSpirit",
                "VGC_Addon_GameBoyGames.GB_Cartridge_BalloonKid",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Baseball",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Batman",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Battletoads",
                "VGC_Addon_GameBoyGames.GB_Cartridge_BionicCommando",
                "VGC_Addon_GameBoyGames.GB_Cartridge_BubbleBobble",
                "VGC_Addon_GameBoyGames.GB_Cartridge_BugsBunny",
                "VGC_Addon_GameBoyGames.GB_Cartridge_BugsBunny2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Castlevania",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Castlevania2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Catrap",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dexterity",
                "VGC_Addon_GameBoyGames.GB_Cartridge_DoubleDragon",
                "VGC_Addon_GameBoyGames.GB_Cartridge_DoubleDragon2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_DrMario",
                "VGC_Addon_GameBoyGames.GB_Cartridge_DuckTales",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dummy1",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dummy2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dummy3",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dummy4",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Dummy5",
                "VGC_Addon_GameBoyGames.GB_Cartridge_F1Race",
                "VGC_Addon_GameBoyGames.GB_Cartridge_FFLegend",
                "VGC_Addon_GameBoyGames.GB_Cartridge_FFLegend2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Fantasy",
                "VGC_Addon_GameBoyGames.GB_Cartridge_FortifiedZone",
                "VGC_Addon_GameBoyGames.GB_Cartridge_GargoylesQuest",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Golf",
                "VGC_Addon_GameBoyGames.GB_Cartridge_KidDracula",
                "VGC_Addon_GameBoyGames.GB_Cartridge_KidIcarus",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Kirby",
                "VGC_Addon_GameBoyGames.GB_Cartridge_LittleMermaid",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Mario",
                "VGC_Addon_GameBoyGames.GB_Cartridge_MegaMan",
                "VGC_Addon_GameBoyGames.GB_Cartridge_MegaMan2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_MegaMan3",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Metroid2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Mickey",
                "VGC_Addon_GameBoyGames.GB_Cartridge_MotocrossManiacs",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Nemesis",
                "VGC_Addon_GameBoyGames.GB_Cartridge_NinjaGaiden",
                "VGC_Addon_GameBoyGames.GB_Cartridge_OperationC",
                "VGC_Addon_GameBoyGames.GB_Cartridge_QIX",
                "VGC_Addon_GameBoyGames.GB_Cartridge_RType",
                "VGC_Addon_GameBoyGames.GB_Cartridge_RolansCurse",
                "VGC_Addon_GameBoyGames.GB_Cartridge_RolansCurse2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_SolarStriker",
                "VGC_Addon_GameBoyGames.GB_Cartridge_SolomonsClub",
                "VGC_Addon_GameBoyGames.GB_Cartridge_StarWars",
                "VGC_Addon_GameBoyGames.GB_Cartridge_StarWars2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_SuperMario2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_SuperRC",
                "VGC_Addon_GameBoyGames.GB_Cartridge_SwordOfHope",
                "VGC_Addon_GameBoyGames.GB_Cartridge_TMNT",
                "VGC_Addon_GameBoyGames.GB_Cartridge_TMNT2",
                "VGC_Addon_GameBoyGames.GB_Cartridge_TailGator",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Tennis",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Tetris",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Trax",
                "VGC_Addon_GameBoyGames.GB_Cartridge_WaveRace",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Yoshi",
                "VGC_Addon_GameBoyGames.GB_Cartridge_YoshisCookie",
                "VGC_Addon_GameBoyGames.GB_Cartridge_Zelda",
                "Video_Game_Consoles.Atari",
                "Video_Game_Consoles.Atari_Cartridge_Asteroids",
                "Video_Game_Consoles.Atari_Cartridge_Combat",
                "Video_Game_Consoles.Atari_Cartridge_MSPacman",
                "Video_Game_Consoles.Atari_Cartridge_Pitfall",
                "Video_Game_Consoles.Atari_Cartridge_Spaceinvaders",
                "Video_Game_Consoles.GB_Cartridge_Fantasy",
                "Video_Game_Consoles.GB_Cartridge_Kirby",
                "Video_Game_Consoles.GB_Cartridge_Mario",
                "Video_Game_Consoles.GB_Cartridge_Tetris",
                "Video_Game_Consoles.GB_Cartridge_Zelda",
                "Video_Game_Consoles.GG_Cartridge_AxBattler",
                "Video_Game_Consoles.GG_Cartridge_Shinobi",
                "Video_Game_Consoles.GG_Cartridge_Sonic",
                "Video_Game_Consoles.GG_Cartridge_Vampire",
                "Video_Game_Consoles.GG_Cartridge_sor2",
                "Video_Game_Consoles.GameBoy",
                "Video_Game_Consoles.GameBoy_nobat",
                "Video_Game_Consoles.Game_Gear",
                "Video_Game_Consoles.Game_Gear_nobat",
                "Video_Game_Consoles.Genesis",
                "Video_Game_Consoles.Genesis_Cartridge_Aladdin",
                "Video_Game_Consoles.Genesis_Cartridge_gaxe",
                "Video_Game_Consoles.Genesis_Cartridge_ghouls",
                "Video_Game_Consoles.Genesis_Cartridge_sonic",
                "Video_Game_Consoles.Genesis_Cartridge_street",
                "Video_Game_Consoles.NES",
                "Video_Game_Consoles.NES_Cartridge_Contra",
                "Video_Game_Consoles.NES_Cartridge_Mario3",
                "Video_Game_Consoles.NES_Cartridge_Megaman",
                "Video_Game_Consoles.NES_Cartridge_Metroid",
                "Video_Game_Consoles.NES_Cartridge_Zelda",
                "Video_Game_Consoles.SNES",
                "Video_Game_Consoles.SNES_Cartridge_Fox",
                "Video_Game_Consoles.SNES_Cartridge_MK2",
                "Video_Game_Consoles.SNES_Cartridge_Mana",
                "Video_Game_Consoles.SNES_Cartridge_Mario",
                "Video_Game_Consoles.SNES_Cartridge_NBA",
            },
        },
    },
})
