--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Jigga's Greenfire Mod.
-- https://steamcommunity.com/sharedfiles/filedetails/?id=1703604612
--
-- Mappings migrated from Better Sorting (JiggasGreenFireMod_Items.lua): 110
-- lines, no repeats -> 110 items. The one commented-out upstream line
-- (Greenfire.Marshmallows -> FoodN) is not migrated; the generic food rules
-- cover it. The 11 Hydrocraft.* smoking items the original lists under this
-- guard are kept here, exactly as upstream: the guard is what decides, and
-- unknown items are skipped at boot when Hydrocraft is not installed.
--
-- Overlap with the MoreCigsMod pack: 32 Greenfire.* items (the tobacco,
-- cigar/carton and seed block) are also mapped there, to the SAME categories,
-- so which pack wins is a no-op. Each mod still sorts them when it runs alone.
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "JiggasGreenFireMod",
    mods = { "jiggasGreenfireMod", "jiggasAddictionMod" },
    data = {
        Drugs = {
            items = {
                "Greenfire.Blunt",
                "Greenfire.BluntCigar",
                "Greenfire.BluntWrap",
                "Greenfire.Bong",
                "Greenfire.CannaButter",
                "Greenfire.CannaCigar",
                "Greenfire.CannaJar",
                "Greenfire.CannaJar2",
                "Greenfire.CannaJar3",
                "Greenfire.CannaJar4",
                "Greenfire.Cannabis",
                "Greenfire.CannabisShake",
                "Greenfire.CigarLeaf",
                "Greenfire.DelCannaCigar",
                "Greenfire.DryBTobacco",
                "Greenfire.DryCannabisFanLeaf",
                "Greenfire.DryCannabisSugarLeaf",
                "Greenfire.DryTCanna",
                "Greenfire.DryUnCanna",
                "Greenfire.FreshBTobacco",
                "Greenfire.FreshCannabisFanLeaf",
                "Greenfire.FreshCannabisSugarLeaf",
                "Greenfire.FreshTCanna",
                "Greenfire.FreshUnCanna",
                "Greenfire.GFCigar",
                "Greenfire.GFCigarette",
                "Greenfire.GFCigaretteCarton",
                "Greenfire.GFCigaretteCase",
                "Greenfire.GFCigarettes",
                "Greenfire.GFEmptyCigaretteCarton",
                "Greenfire.GFGrinder",
                "Greenfire.GFUsedCigaretteCarton",
                "Greenfire.HalfBlunt",
                "Greenfire.HalfBluntCigar",
                "Greenfire.HalfCannaCigar",
                "Greenfire.HalfCigar",
                "Greenfire.HalfDelCannaCigar",
                "Greenfire.HalfHashBlunt",
                "Greenfire.HalfHashJoint",
                "Greenfire.HalfJoint",
                "Greenfire.HalfKiefBlunt",
                "Greenfire.HalfKiefJoint",
                "Greenfire.HalfMixedBlunt",
                "Greenfire.HalfPreCannaCigar",
                "Greenfire.HalfResCannaCigar",
                "Greenfire.HalfSpaceBlunt",
                "Greenfire.HashBlunt",
                "Greenfire.HashBong",
                "Greenfire.HashJoint",
                "Greenfire.HashPipe",
                "Greenfire.HashPress",
                "Greenfire.Hashish",
                "Greenfire.Joint",
                "Greenfire.KgCannabis",
                "Greenfire.Kief",
                "Greenfire.KiefBlunt",
                "Greenfire.KiefBong",
                "Greenfire.KiefJoint",
                "Greenfire.KiefPipe",
                "Greenfire.MixedBlunt",
                "Greenfire.NiceCrispiez",
                "Greenfire.NiceCrispiezPan",
                "Greenfire.OzCannabis",
                "Greenfire.PipeTobaccoBag",
                "Greenfire.PreCannaCigar",
                "Greenfire.ResCannaCigar",
                "Greenfire.RollNylon",
                "Greenfire.RollingPapers",
                "Greenfire.SBrownie",
                "Greenfire.SBrowniePan",
                "Greenfire.SCrispySauce",
                "Greenfire.ShakeBong",
                "Greenfire.ShakePipe",
                "Greenfire.SilkScreen",
                "Greenfire.SmokingPipe",
                "Greenfire.SpaceBlunt",
                "Greenfire.Spliff",
                "Greenfire.Tobacco",
                "Greenfire.TobaccoBong",
                "Greenfire.TobaccoPipe",
                "Greenfire.UnCannaJar",
                "Greenfire.UnCannaJar2",
                "Greenfire.UnCannaJar3",
                "Greenfire.UnCannaJar4",
                "Greenfire.UncuredCannaCigar",
                "Greenfire.UncuredCigar",
                "Greenfire.UncuredDelCannaCigar",
                "Greenfire.UncuredPreCannaCigar",
                "Greenfire.UncuredResCannaCigar",
                "Greenfire.WeedBong",
                "Greenfire.WeedPipe",
                "Hydrocraft.HCBongacrylicdirty",
                "Hydrocraft.HCBongacrylicempty",
                "Hydrocraft.HCBongacrylicfull",
                "Hydrocraft.HCBongdirty",
                "Hydrocraft.HCBongempty",
                "Hydrocraft.HCBongfull",
                "Hydrocraft.HCClaypipesmoking",
                "Hydrocraft.HCCorncobpipe",
                "Hydrocraft.HCCorncobpipehemp",
                "Hydrocraft.HCHempbudcured",
                "Hydrocraft.HCPipehemp",
            },
        },
        LitR = {
            items = {
                "Greenfire.AficMag1",
                "Greenfire.CannaMag1",
                "Greenfire.CannaMag2",
                "Greenfire.CannaMag3",
            },
        },
        SurFarm = {
            items = {
                "Greenfire.CannabisBagSeed",
                "Greenfire.CannabisSeed",
                "Greenfire.TobaccoBagSeed",
                "Greenfire.TobaccoSeed",
            },
        },
    },
})
