--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: MRE XIII (US military rations).
--
-- Covers:
--   1521582441 (MRE XIII — this mod's ID is its Workshop ID)
--   — https://steamcommunity.com/sharedfiles/filedetails/?id=1521582441
--
-- The whole upstream file is commented out (its 107 lines are the food section
-- the original disabled in favour of its generic perishable/non-perishable
-- rule). Migrated anyway, unlike the food lines of packs that keep other active
-- mappings: it is this file's ENTIRE content, and the rations' accessories
-- (spoon, ration heater, accessory packets, boxes and pallets) are not of item
-- type Food, so the generic rule would never sort them with the meals.
--
-- Mappings migrated from Better Sorting v2.0.4 (MRE_XIII_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "MRE_XIII",
    mods = { "1521582441" },
    data = {
        FoodN = {
            items = {
                "USMRE.MREAccessoryPacketA",
                "USMRE.MREAccessoryPacketB",
                "USMRE.MREApplesauce",
                "USMRE.MREBeefStew",
                "USMRE.MREBeefStewHot",
                "USMRE.MREBeefStewHotS",
                "USMRE.MREBeefStewS",
                "USMRE.MREBevBasewithSugar",
                "USMRE.MREBevBasewithSugarCuppa",
                "USMRE.MREBrownieChocCovered",
                "USMRE.MRECandy1",
                "USMRE.MRECandy2",
                "USMRE.MRECandy3",
                "USMRE.MRECheesespread",
                "USMRE.MREChewingGum",
                "USMRE.MREChickenStew",
                "USMRE.MREChickenStewHot",
                "USMRE.MREChickenStewHotS",
                "USMRE.MREChickenStewS",
                "USMRE.MREChickenalaKing",
                "USMRE.MREChickenalaKingHot",
                "USMRE.MREChickenalaKingHotS",
                "USMRE.MREChickenalaKingS",
                "USMRE.MREChickenwithRice",
                "USMRE.MREChickenwithRiceHot",
                "USMRE.MREChickenwithRiceHotS",
                "USMRE.MREChickenwithRiceS",
                "USMRE.MRECocoa",
                "USMRE.MRECoffee",
                "USMRE.MRECookieChocCovered",
                "USMRE.MRECornedBeefHash",
                "USMRE.MRECornedBeefHashHot",
                "USMRE.MRECornedBeefHashHotS",
                "USMRE.MRECornedBeefHashS",
                "USMRE.MRECrackers",
                "USMRE.MRECrackersCheesespread",
                "USMRE.MRECrackersJelly",
                "USMRE.MRECrackersPeanutButter",
                "USMRE.MRECreamSubstitute",
                "USMRE.MRECuppa",
                "USMRE.MRECuppaCocoa",
                "USMRE.MREEscallopedPotatoeswithHam",
                "USMRE.MREEscallopedPotatoeswithHamHot",
                "USMRE.MREEscallopedPotatoeswithHamHotS",
                "USMRE.MREEscallopedPotatoeswithHamS",
                "USMRE.MREFlamelessRationHeater",
                "USMRE.MREFreezedriedfruit",
                "USMRE.MREFruit",
                "USMRE.MREHamSlice",
                "USMRE.MREHamSliceHot",
                "USMRE.MREHamSliceHotS",
                "USMRE.MREHamSliceS",
                "USMRE.MREHotSource",
                "USMRE.MREJelly",
                "USMRE.MREMeatballswithTomatoSauce",
                "USMRE.MREMeatballswithTomatoSauceHot",
                "USMRE.MREMeatballswithTomatoSauceHotS",
                "USMRE.MREMeatballswithTomatoSauceS",
                "USMRE.MREOatmealCookieBar",
                "USMRE.MREOmeletwithHam",
                "USMRE.MREOmeletwithHamHot",
                "USMRE.MREOmeletwithHamHotS",
                "USMRE.MREOmeletwithHamS",
                "USMRE.MREPeanutButter",
                "USMRE.MREPorkwithRiceinBBQSauce",
                "USMRE.MREPorkwithRiceinBBQSauceHot",
                "USMRE.MREPorkwithRiceinBBQSauceHotS",
                "USMRE.MREPorkwithRiceinBBQSauceS",
                "USMRE.MREPotatoesAuGrautin",
                "USMRE.MREPoundCake",
                "USMRE.MRESpaghettiwithMeatSauce",
                "USMRE.MRESpaghettiwithMeatSauceHot",
                "USMRE.MRESpaghettiwithMeatSauceHotS",
                "USMRE.MRESpaghettiwithMeatSauceS",
                "USMRE.MRESpoon",
                "USMRE.MRESugar",
                "USMRE.MRESugarFreeBevBase",
                "USMRE.MRESugarFreeBevBaseCuppa",
                "USMRE.MRETunawithNoodles",
                "USMRE.MRETunawithNoodlesHot",
                "USMRE.MRETunawithNoodlesHotS",
                "USMRE.MRETunawithNoodlesS",
                "USMRE.MREbox",
                "USMRE.MREboxPallet01",
                "USMRE.MREboxPallet02",
                "USMRE.MREboxPallet03",
                "USMRE.MREboxPallet04",
                "USMRE.MREboxPallet05",
                "USMRE.MREboxPallet06",
                "USMRE.MREboxPallet07",
                "USMRE.MREboxPallet08",
                "USMRE.MREboxPallet09",
                "USMRE.MREboxPallet10",
                "USMRE.MREboxPallet11",
                "USMRE.MREboxPallet12",
                "USMRE.MREmenu01",
                "USMRE.MREmenu02",
                "USMRE.MREmenu03",
                "USMRE.MREmenu04",
                "USMRE.MREmenu05",
                "USMRE.MREmenu06",
                "USMRE.MREmenu07",
                "USMRE.MREmenu08",
                "USMRE.MREmenu09",
                "USMRE.MREmenu10",
                "USMRE.MREmenu11",
                "USMRE.MREmenu12",
            },
        },
    },
})
