--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Advanced GEAR.
-- https://steamcommunity.com/sharedfiles/filedetails/?id=2050264961
--
-- One of four independent Workshop mods bundled in the original's
-- Planetalgol_Items.lua, one guard each. They ship as four packs so each
-- block keeps the exact scope the original gave it: Advanced GEAR's block
-- re-categorizes item names that are VANILLA in build 42 (Base.Canteen,
-- Base.Multitool, Base.P38, Base.WaterPurificationTablets — mod-added back
-- when the original was written), which must not move when only a sibling
-- mod is installed.
--
-- The five Trap.* items below overlap the SmallMod pack (PlayerTraps),
-- which sorts them to SurTrap. With both mods active SmallMod wins (packs
-- resolve by name order); with Advanced GEAR alone they sort to Tool as
-- the original intended.
--
-- Twelve of the original's lines are dropped: the vests, ammo straps,
-- Jacket_Black, MakeUp_GreenCamo and Mugfull already sort to the same
-- category through the Data/ tables, mod or no mod.
--
-- Mappings migrated from Better Sorting v2.0.4 (Planetalgol_Items.lua),
-- with the original's "Cont" key remapped to "Container".
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "Planetalgol (Advanced GEAR)",
    mods = { "ADVANCEDGEAR" },
    data = {
        Ammo = {
            items = {
                "Base.FlareCartridge",
                "Base.FlareCartridgeBox",
            },
        },
        Appear = {
            items = {
                "Base.MakeUp_GreenCamo2",
            },
        },
        ClothAcc = {
            items = {
                "Base.BulletBandolier",
                "Base.CalfSheath",
                "Base.ShotgunShellBandolier",
                "Base.ThighHolsterDouble",
                "Base.ThighHolsterSimple",
            },
        },
        ClothBack = {
            items = {
                "Base.Bag_ALICEpack_Army_With2Attachments",
                "Base.Bag_ALICEpack_Army_With3Attachments",
                "Base.Bag_ALICEpack_Army_WithAttachment",
                "Base.Bag_ALICEpack_With2Attachments",
                "Base.Bag_ALICEpack_With3Attachments",
                "Base.Bag_ALICEpack_WithAttachment",
                "Base.Bag_BigHikingBag_With2Attachments",
                "Base.Bag_BigHikingBag_WithAttachment",
                "Base.Bag_NormalHikingBag_With2Attachments",
                "Base.Bag_NormalHikingBag_WithAttachment",
                "Base.Bag_Schoolbag_WithAttachment",
                "Base.Bag_SurvivorBag_With2Attachments",
                "Base.Bag_SurvivorBag_With3Attachments",
                "Base.Bag_SurvivorBag_WithAttachment",
            },
        },
        ClothBag = {
            items = {
                "Base.Fanny_Pack_Blue",
                "Base.Fanny_Pack_Green",
                "Base.Fanny_Pack_Pink",
                "Base.Fanny_Pack_Red",
                "Base.Fanny_Pack_Teal",
            },
        },
        ClothBody = {
            items = {
                "Base.BackRig",
                "Base.CCVest",
                "Base.ChestRig",
                "Base.Vest_BulletEMS",
                "Base.Vest_BulletFire",
                "Base.Vest_BulletPress",
                "Base.Webbing",
                "Base.WebbingLoose",
                "Base.Webbing_Black",
                "Base.Webbing_BlackLoose",
                "Base.Webbing_Military",
                "Base.Webbing_MilitaryLoose",
            },
        },
        ClothFeet = {
            items = {
                "Base.AssaultBoots",
                "Base.AssaultBootsDesert",
            },
        },
        ClothHead = {
            items = {
                "Base.BallisticMask",
                "Base.SkullHalfMask",
                "Base.SniperVeil",
            },
        },
        Collect = {
            items = {
                "Base.BlackwebDiskette",
                "Base.IntelFolder",
                "Base.LabKeycard",
            },
        },
        Container = {
            items = {
                "Base.Canteen",
                "Base.MRE_Coffee_Mug",
                "Base.MRE_Coffee_Mug_Red",
                "Base.MRE_Coffee_Mug_Spiffo",
                "Base.MRE_Coffee_Mug_White",
            },
        },
        Cook = {
            items = {
                "Base.MRE_BevBasewithSugar",
                "Base.MRE_Cocoa",
                "Base.MRE_SugarFreeBevBase",
                "Base.WaterPurificationTablets",
                "Base.WaterPurificationTablets_Empty",
            },
        },
        CraftTailor = {
            items = {
                "Base.CeramicPlate",
                "Base.KevlarPlate",
                "Base.TitaniumPlate",
                "Movables.camo_netting_0",
            },
        },
        FoodB = {
            items = {
                "Base.Canteenfull",
                "Base.MRE_BevwithSugar_Mug",
                "Base.MRE_BevwithSugar_Mug_Red",
                "Base.MRE_BevwithSugar_Mug_Spiffo",
                "Base.MRE_BevwithSugar_Mug_White",
                "Base.MRE_BevwithSugar_WaterBottle",
                "Base.MRE_Cocoa_Mug",
                "Base.MRE_Cocoa_Mug_Red",
                "Base.MRE_Cocoa_Mug_Spiffo",
                "Base.MRE_Cocoa_Mug_White",
                "Base.MRE_Coffee",
                "Base.MRE_SugarFreeBev_Mug",
                "Base.MRE_SugarFreeBev_Mug_Red",
                "Base.MRE_SugarFreeBev_Mug_Spiffo",
                "Base.MRE_SugarFreeBev_Mug_White",
                "Base.MRE_SugarFreeBev_WaterBottle",
            },
        },
        FoodN = {
            items = {
                "Base.MRE",
                "Base.MRE_Applesauce",
                "Base.MRE_BeefStew",
                "Base.MRE_BeefStew_Heating",
                "Base.MRE_BeefStew_Open",
                "Base.MRE_BrownieChocCovered",
                "Base.MRE_Cheesespread",
                "Base.MRE_ChickenStew",
                "Base.MRE_ChickenStew_Heating",
                "Base.MRE_ChickenStew_Open",
                "Base.MRE_ChickenalaKing",
                "Base.MRE_ChickenalaKing_Heating",
                "Base.MRE_ChickenalaKing_Open",
                "Base.MRE_ChickenwithRice",
                "Base.MRE_ChickenwithRice_Heating",
                "Base.MRE_ChickenwithRice_Open",
                "Base.MRE_ChowMeinNoodles",
                "Base.MRE_CookieChocCovered",
                "Base.MRE_CornedBeefHash",
                "Base.MRE_CornedBeefHash_Heating",
                "Base.MRE_CornedBeefHash_Open",
                "Base.MRE_Crackers",
                "Base.MRE_EscallopedPotatoeswithHam",
                "Base.MRE_EscallopedPotatoeswithHam_Heating",
                "Base.MRE_EscallopedPotatoeswithHam_Open",
                "Base.MRE_Freezedriedfruit",
                "Base.MRE_HamSlice",
                "Base.MRE_HamSlice_Heating",
                "Base.MRE_HamSlice_Open",
                "Base.MRE_Jelly",
                "Base.MRE_MeatballswithTomatoSauce",
                "Base.MRE_MeatballswithTomatoSauce_Heating",
                "Base.MRE_MeatballswithTomatoSauce_Open",
                "Base.MRE_OatmealCookieBar",
                "Base.MRE_OmeletwithHam",
                "Base.MRE_OmeletwithHam_Heating",
                "Base.MRE_OmeletwithHam_Open",
                "Base.MRE_PeanutButter",
                "Base.MRE_PorkwithRiceinBBQSauce",
                "Base.MRE_PorkwithRiceinBBQSauce_Heating",
                "Base.MRE_PorkwithRiceinBBQSauce_Open",
                "Base.MRE_PotatoSticks",
                "Base.MRE_PotatoesAuGrautin",
                "Base.MRE_PoundCake",
                "Base.MRE_Side",
                "Base.MRE_SpaghettiwithMeatSauce",
                "Base.MRE_SpaghettiwithMeatSauce_Heating",
                "Base.MRE_SpaghettiwithMeatSauce_Open",
                "Base.MRE_Stack",
                "Base.MRE_TunawithNoodles",
                "Base.MRE_TunawithNoodles_Heating",
                "Base.MRE_TunawithNoodles_Open",
                "Base.Peanut_Butter_Patrol_Cookie",
            },
        },
        FoodP = {
            items = {
                "Base.MRE_BeefStew_Hot",
                "Base.MRE_BeefStew_Hot_HotSauce",
                "Base.MRE_ChickenStew_Hot",
                "Base.MRE_ChickenStew_Hot_HotSauce",
                "Base.MRE_ChickenalaKing_Hot",
                "Base.MRE_ChickenalaKing_Hot_HotSauce",
                "Base.MRE_ChickenwithRice_Hot",
                "Base.MRE_ChickenwithRice_Hot_HotSauce",
                "Base.MRE_CornedBeefHash_Hot",
                "Base.MRE_CornedBeefHash_Hot_HotSauce",
                "Base.MRE_Crackers_Cheesespread",
                "Base.MRE_Crackers_Jelly",
                "Base.MRE_Crackers_PeanutButter",
                "Base.MRE_EscallopedPotatoeswithHam_Hot",
                "Base.MRE_EscallopedPotatoeswithHam_Hot_HotSauce",
                "Base.MRE_Fruit",
                "Base.MRE_HamSlice_Hot",
                "Base.MRE_HamSlice_Hot_HotSauce",
                "Base.MRE_MeatballswithTomatoSauce_Hot",
                "Base.MRE_MeatballswithTomatoSauce_Hot_HotSauce",
                "Base.MRE_OmeletwithHam_Hot",
                "Base.MRE_OmeletwithHam_Hot_HotSauce",
                "Base.MRE_PorkwithRiceinBBQSauce_Hot",
                "Base.MRE_PorkwithRiceinBBQSauce_Hot_HotSauce",
                "Base.MRE_SpaghettiwithMeatSauce_Hot",
                "Base.MRE_SpaghettiwithMeatSauce_Hot_HotSauce",
                "Base.MRE_TunawithNoodles_Hot",
                "Base.MRE_TunawithNoodles_Hot_HotSauce",
                "Base.Paratrooper_Potluck_Pie",
            },
        },
        Junk = {
            items = {
                "Base.BrushkitEmpty",
                "Base.FactionBanner",
                "Base.MRE_BeefStew_Finished",
                "Base.MRE_Box",
                "Base.MRE_ChickenStew_Finished",
                "Base.MRE_ChickenalaKing_Finished",
                "Base.MRE_ChickenwithRice_Finished",
                "Base.MRE_Cocoa_Trash",
                "Base.MRE_Coffee_Trash",
                "Base.MRE_CornedBeefHash_Finished",
                "Base.MRE_Crackers_Trash",
                "Base.MRE_Drink_Trash",
                "Base.MRE_EscallopedPotatoeswithHam_Finished",
                "Base.MRE_FlamelessRationHeater_Trash",
                "Base.MRE_HamSlice_Finished",
                "Base.MRE_Meal_Carton_Trash",
                "Base.MRE_Meal_Pouch_Trash",
                "Base.MRE_MeatballswithTomatoSauce_Finished",
                "Base.MRE_OmeletwithHam_Finished",
                "Base.MRE_PorkwithRiceinBBQSauce_Finished",
                "Base.MRE_Pouch_Trash",
                "Base.MRE_Side_Carton_Trash",
                "Base.MRE_Side_Pouch_Trash",
                "Base.MRE_SpaghettiwithMeatSauce_Finished",
                "Base.MRE_Spread_Trash",
                "Base.MRE_TunawithNoodles_Finished",
                "Base.MaintkitEmpty",
                "Base.Small_Cardboard_Box",
                "Base.WD40Empty",
                "Trap.Nothing",
            },
        },
        Tool = {
            items = {
                "Base.Brushkit",
                "Base.CliponCompass",
                "Base.Compass",
                "Base.Compass2",
                "Base.Flashlight_Military",
                "Base.Leatherdad",
                "Base.MRE_FlamelessRationHeater",
                "Base.Maintkit",
                "Base.Multitool",
                "Base.P38DT",
                "Base.SAK",
                "Base.WD40",
                "Base.WristCompass_Left",
                "Base.WristCompass_Right",
                "Trap.BearTrap",
                "Trap.BearTrapClosed",
                "Trap.PropaneTrap",
                "Trap.SpikeTrap",
                "Trap.SpikeTrapClosed",
            },
        },
        WepBomb = {
            items = {
                "Base.ConcussionGrenade",
                "Base.IncendiaryGrenade",
                "Base.SmokeGrenade",
                "Base.StunGrenade",
                "Explosives.LandMine",
                "Explosives.LandMineBig",
                "Explosives.LandMineBigBox",
                "Explosives.LandMineBigSet",
                "Explosives.LandMineBox",
                "Explosives.LandMineSet",
            },
        },
        WepFire = {
            items = {
                "Base.DoubleBarrelShotgunSawnOff2",
                "Base.FlareGun",
                "Base.HuntingRifleSawnOff",
                "Base.VarmintRifleSawnOff",
            },
        },
        WepMelee = {
            items = {
                "Base.Knuckleduster",
                "Base.Kukri",
                "Base.PA_TacticalKukri",
                "Base.PA_TrenchKnife",
                "Base.PA_TrenchKnife2",
                "Base.PA_TrenchKnifeB",
                "Base.PA_TrenchKnifeB2",
                "Base.PA_TrenchKnifeC",
                "Base.PA_TrenchKnifeC2",
                "Base.PLGR",
            },
        },
    },
})
