--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Soul Filcher's mods.
-- Covers Soul Filcher's ...Time series (BeautifyingTime, CookingTime,
-- DressingTime, ...). Each is guarded on both its short and its SoulFilchers-
-- prefixed workshop ID. See the mods list below.
--
-- Mappings migrated from Better Sorting (SoulFilchers_Items.lua), "Cont" ->
-- "Container".
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "Soul Filcher's mods",
    mods = { "BeautifyingTime", "SoulFilchersBeautifyingTime", "BuildingTime", "SoulFilchersBuildingTime", "ClearingTime", "SoulFilchersClearingTime", "CookingTime", "SoulFilchersCookingTime", "DressingTime", "SoulFilchersDressingTime", "DrinkingTime", "SoulFilchersDrinkingTime", "ExploringTime", "SoulFilchersExploringTime", "FarmingTime", "SoulFilchersFarmingTime", "ForagingTime", "SoulFilchersForagingTime", "FreezingTime", "SoulFilchersFreezingTime", "LearningTime", "SoulFilchersLearningTime", "RelaxingTime", "SoulFilchersRelaxingTime", "PhotographingTime", "SoulFilchersPhotographingTime" },
    overrides = {
        WepMelee = {
            items = {
                "Base.Corkscrew",
            },
        },
    },
    data = {
        Appear = {
            items = {
                "MoreSkillBooks.Other_Moustache",
                "filcher.HairDyeAuburn",
                "filcher.HairDyeAvocado",
                "filcher.HairDyeCherry",
                "filcher.HairDyeCyan",
                "filcher.HairDyeDarkBlue",
                "filcher.HairDyeDarkBrown",
                "filcher.HairDyeDarkTurquoise",
                "filcher.HairDyeDeepPurple",
                "filcher.HairDyeGrey",
                "filcher.HairDyeLightBlonde",
                "filcher.HairDyeLilac",
                "filcher.HairDyeLime",
                "filcher.HairDyeMagenta",
                "filcher.HairDyeOlive",
                "filcher.HairDyeOrange",
                "filcher.HairDyePurple",
                "filcher.HairDyeSnowWhite",
                "filcher.HairDyeTurquoise",
            },
        },
        ClothAcc = {
            items = {
                "MoreSkillBooks.Belt_Black",
                "MoreSkillBooks.Belt_TINT",
                "MoreSkillBooks.Belt_Tools",
                "MoreSkillBooks.Other_BunnyTail",
                "MoreSkillBooks.Other_RaccoonTail",
                "MoreSkillBooks.Scarf_PureWhite",
                "MoreSkillBooks.Scarf_StripedGreenWhite",
                "MoreSkillBooks.Scarf_StripedRedGreen",
                "MoreSkillBooks.Scarf_StripedRedYellow",
                "MoreSkillBooks.Tie_FullTINT",
                "MoreSkillBooks.Tie_Full_Black",
            },
        },
        ClothArm = {
            items = {
                "MoreSkillBooks.Gloves_White",
                "MoreSkillBooks.Gloves_Yellow",
            },
        },
        ClothBack = {
            items = {
                "MoreSkillBooks.Bag_BigHikingBagTINT",
                "MoreSkillBooks.Bag_NormalHikingBagTINT",
                "MoreSkillBooks.Bag_SchoolbagTINT",
            },
        },
        ClothBag = {
            items = {
                "MoreSkillBooks.Bag_FannyPackTINTBack",
                "MoreSkillBooks.Bag_FannyPackTINTFront",
            },
        },
        ClothBody = {
            items = {
                "MoreSkillBooks.Apron_TINT",
                "MoreSkillBooks.Dress_Cardinals",
                "MoreSkillBooks.Dress_Fancy",
                "MoreSkillBooks.Dress_Mini",
                "MoreSkillBooks.FancyJacket",
                "MoreSkillBooks.Jacket_Brown",
                "MoreSkillBooks.Jacket_Red",
                "MoreSkillBooks.SkeletonSuit",
                "MoreSkillBooks.SlendermanSuit",
                "MoreSkillBooks.Swimsuit_SexyBunny",
                "MoreSkillBooks.Swimsuit_SexyTINT",
                "MoreSkillBooks.Tshirt_CutBellyTINT",
                "MoreSkillBooks.Tshirt_CutBellyWHITE",
                "MoreSkillBooks.Tshirt_LongTranspBlack",
                "MoreSkillBooks.Tshirt_MiscDECALTINT",
                "MoreSkillBooks.Tshirt_MiscDECALWHITE",
                "MoreSkillBooks.Tshirt_SleevelessTINT",
                "MoreSkillBooks.Tshirt_SleevelessWHITE",
                "MoreSkillBooks.Tshirt_WhiteTINT_OUT",
                "MoreSkillBooks.Vest_WaistcoatDarkGreen",
                "MoreSkillBooks.Vest_WaistcoatDarkRed",
                "MoreSkillBooks.Vest_WaistcoatGreen",
                "MoreSkillBooks.Vest_WaistcoatRed",
                "MoreSkillBooks.Vest_WaistcoatTartan",
                "MoreSkillBooks.Vest_WaistcoatWHITE",
            },
        },
        ClothFeet = {
            items = {
                "MoreSkillBooks.Shoes_BootsTINT",
                "MoreSkillBooks.Shoes_Clown",
                "MoreSkillBooks.Shoes_SantaBoots",
                "MoreSkillBooks.Sock_Ankle_Left",
                "MoreSkillBooks.Sock_Ankle_Right",
                "MoreSkillBooks.Sock_Long_Left",
                "MoreSkillBooks.Sock_Long_Right",
                "MoreSkillBooks.Socks_Ballet",
                "MoreSkillBooks.Socks_LegWarmers",
                "MoreSkillBooks.Socks_StockingsBlack",
            },
        },
        ClothHead = {
            items = {
                "MoreSkillBooks.Glasses_3D",
                "MoreSkillBooks.Glasses_TINT",
                "MoreSkillBooks.Glasses_White",
                "MoreSkillBooks.Hat_BaseballCapSpiffo",
                "MoreSkillBooks.Hat_BaseballCapSpiffo_Reverse",
                "MoreSkillBooks.Hat_BaseballCapTINT",
                "MoreSkillBooks.Hat_BaseballCapTINT_Reverse",
                "MoreSkillBooks.Hat_BaseballCapVote",
                "MoreSkillBooks.Hat_BaseballCapVote_Reverse",
                "MoreSkillBooks.Hat_BaseballCapWhite",
                "MoreSkillBooks.Hat_BaseballCapWhite_Reverse",
                "MoreSkillBooks.Hat_Bucket",
                "MoreSkillBooks.Hat_BunnyEars",
                "MoreSkillBooks.Hat_CookingPot",
                "MoreSkillBooks.Hat_DinoHat",
                "MoreSkillBooks.Hat_Fox",
                "MoreSkillBooks.Hat_HeadbandSimpleTINT",
                "MoreSkillBooks.Hat_MickeyEars",
                "MoreSkillBooks.Hat_TopHat",
                "MoreSkillBooks.Hat_Wig",
                "MoreSkillBooks.Hat_WoolyHatCartman",
                "MoreSkillBooks.Hat_WoolyHatDouble",
                "MoreSkillBooks.Hat_WoolyHatXmas",
                "MoreSkillBooks.Other_ClownNose",
            },
        },
        ClothLeg = {
            items = {
                "MoreSkillBooks.DungareesShort",
                "MoreSkillBooks.DungareesShortTINT",
                "MoreSkillBooks.DungareesTINT",
                "MoreSkillBooks.DungareesWhite",
                "MoreSkillBooks.Shorts_MiniDenim",
                "MoreSkillBooks.Shorts_MiniDenimBlack",
                "MoreSkillBooks.Shorts_MiniDenimLight",
                "MoreSkillBooks.Skirt_Ballet",
                "MoreSkillBooks.Skirt_KneesTartan",
                "MoreSkillBooks.Skirt_Santa",
                "MoreSkillBooks.Skirt_SantaGreen",
                "MoreSkillBooks.Trousers_TightDenim",
                "MoreSkillBooks.Trousers_TightDenimBlack",
                "MoreSkillBooks.Trousers_TightDenimLight",
            },
        },
        ClothMisc = {
            items = {
                "MoreSkillBooks.Other_Billboard",
                "MoreSkillBooks.Other_BillboardGod",
                "MoreSkillBooks.Other_BillboardVote",
                "MoreSkillBooks.Other_Floatsie",
                "MoreSkillBooks.Other_FloatsieFlamingo",
            },
        },
        Container = {
            items = {
                "Base.WaterGallonEmpty",
                "MoreSkillBooks.Bag_ToteSF",
                "MoreSkillBooks.Bag_ToteSFWeen",
                "MoreSkillBooks.Bag_ToteSFXmas",
                "filcher.Briefcase",
                "filcher.SFEmptyTray",
            },
        },
        Cook = {
            items = {
                "filcher.Cinnamon",
                "filcher.EmptyGlass",
                "filcher.JarAndLid",
                "filcher.SFBakingTrayCornbread",
                "filcher.SFBarbecue",
                "filcher.SFCornBatter",
                "filcher.SFCornbreadBatter",
                "filcher.SFCupcakeBatter",
                "filcher.SFCupcakeTray",
                "filcher.SFCurry",
                "filcher.SFOregano",
                "filcher.SFPaprika",
                "filcher.SFPizzaDough",
                "filcher.SFPizzaPrep",
                "filcher.SFPlainBreadDough",
                "filcher.SFThinStick",
                "filcher.SFWheat",
                "filcher.TeaExtract",
            },
        },
        Craft = {
            items = {
                "filcher.SFBucketSnow",
                "filcher.SnowPaintbucket",
                "filcher.SnowPot",
                "filcher.TinCanSnow",
            },
        },
        CraftMas = {
            items = {
                "filcher.Bricks",
                "filcher.SFBrickMold",
                "filcher.SFClay",
                "filcher.SFClayBag",
                "filcher.SFGlassPanel",
                "filcher.SFMoldedBricks",
                "filcher.SFSealant",
            },
        },
        Drugs = {
            items = {
                "filcher.Cigarette",
            },
        },
        Elec = {
            items = {
                "Base.CameraExpensiveReady",
                "Base.CameraReady",
                "MoreSkillBooks.WristWatch_Left_DigitalBlue",
                "MoreSkillBooks.WristWatch_Right_DigitalBlue",
            },
        },
        FoodB = {
            items = {
                "Base.BeerCanWater",
                "Base.FountainCupWater",
                "Base.JarWater",
                "Base.PetrolCanWater",
                "Base.PlasticCupWater",
                "Base.Pop2CanWater",
                "Base.Pop3CanWater",
                "Base.PopCanWater",
                "Base.RoastingPanWater",
                "Base.TinCanWater",
                "Base.WaterDishFull",
                "Base.WaterGallon",
                "filcher.Lemonade",
                "filcher.SFBoxOfTea",
                "filcher.SFDrink",
                "filcher.SFDrinkBase",
                "filcher.SFIceTray",
                "filcher.SFJuice",
                "filcher.SFWaterTray",
                "filcher.TinCanWater",
                "filcher.WaterGlass",
            },
        },
        FoodN = {
            items = {
                "filcher.CannedHam",
                "filcher.CannedSoup",
                "filcher.CannedSpagetti",
                "filcher.CannedSpinach",
                "filcher.DriedApricots",
                "filcher.Macaroni",
                "filcher.Olives",
                "filcher.SFAcorns",
                "filcher.SFBeanBowl",
                "filcher.SFBeans",
                "filcher.SFBeetPot",
                "filcher.SFBeetSyrupPot",
                "filcher.SFCatfood",
                "filcher.SFChili",
                "filcher.SFChocolateWaferSticksJar",
                "filcher.SFCupcakePrep",
                "filcher.SFHazelnutCream",
                "filcher.SFHickoryNut",
                "filcher.SFHoney",
                "filcher.SFIcecreamEvolved",
                "filcher.SFJelly",
                "filcher.SFPawpaw",
                "filcher.SFPersimmon",
                "filcher.SFPickles",
                "filcher.SFPicklingJar",
                "filcher.SFPineNuts",
                "filcher.SFPlainBreadRotten",
                "filcher.SFPlum",
                "filcher.SFPopsicle2Melted",
                "filcher.SFPopsicle3Melted",
                "filcher.SFPopsicle4Melted",
                "filcher.SFPopsicle5Melted",
                "filcher.SFPopsicleMelted",
                "filcher.SFTomatoSauce",
                "filcher.SFWaterPotBeans",
                "filcher.SFWhippedCream",
                "filcher.SaucepanFries",
                "filcher.TeaLeaves",
            },
        },
        FoodP = {
            items = {
                "filcher.Beercheese",
                "filcher.Beetroot",
                "filcher.BreadPieces",
                "filcher.CannedBeetroot",
                "filcher.CannedHamOpen",
                "filcher.CannedPumpkin",
                "filcher.CannedSoupOpen",
                "filcher.Cauliflower",
                "filcher.EggFried",
                "filcher.IcecreamBowl",
                "filcher.OpenCannedSpagetti",
                "filcher.OpenCannedSpinach",
                "filcher.PumpkinPieWholeRaw",
                "filcher.SFBasil",
                "filcher.SFCalabrese",
                "filcher.SFCatfoodOpen",
                "filcher.SFChocolateWaferStick",
                "filcher.SFChocolateWaferSticksJarOpen",
                "filcher.SFCornbread",
                "filcher.SFCorndogRaw",
                "filcher.SFCupcake",
                "filcher.SFCupcakes",
                "filcher.SFDeadCrow",
                "filcher.SFFig",
                "filcher.SFGuacamole",
                "filcher.SFHotdog",
                "filcher.SFKiwi",
                "filcher.SFPapaya",
                "filcher.SFPizzaRaw",
                "filcher.SFPizzaSlice",
                "filcher.SFPlainBreadCooked",
                "filcher.SFPopsicle",
                "filcher.SFPopsicle2",
                "filcher.SFPopsicle3",
                "filcher.SFPopsicle4",
                "filcher.SFPopsicle5",
                "filcher.SFPorkribs",
                "filcher.SFPotatoSliced",
                "filcher.SFRaspberry",
                "filcher.SFRosemary",
                "filcher.SFSausage",
                "filcher.SFTruffles",
                "filcher.SFTurnip",
                "filcher.Spoonbread",
                "filcher.Toasts",
            },
        },
        Fuel = {
            items = {
                "filcher.BottleWithGasPop",
                "filcher.BottleWithGasWater",
            },
        },
        Junk = {
            items = {
                "Base.CameraFilmRevealed",
                "Base.Picture",
                "filcher.GiftCard",
                "filcher.Magic8Ball",
                "filcher.PostcardLocal",
                "filcher.PostcardOthers",
                "filcher.RippedPages",
                "filcher.SFChessboard",
                "filcher.SFCloth",
                "filcher.SFClothDirty",
                "filcher.SFLetter",
                "filcher.SFThermometer",
            },
        },
        LitE = {
            items = {
                "filcher.ColoringBook",
                "filcher.Crosswords",
                "filcher.NotesJokes",
                "filcher.Novel",
                "filcher.SFLetterToYou",
            },
        },
        LitR = {
            items = {
                "Base.SFPhotoMag",
                "filcher.BookMaintenance1",
                "filcher.BookMaintenance2",
                "filcher.BookMaintenance3",
                "filcher.BookMaintenance4",
                "filcher.BookMaintenance5",
                "filcher.CookingNotes1",
                "filcher.CookingNotes2",
                "filcher.ElectronicsNotes1",
                "filcher.ElectronicsNotes2",
                "filcher.ElectronicsNotes3",
                "filcher.ElectronicsNotes4",
                "filcher.ElectronicsNotes5",
                "filcher.EngineerNotes1",
                "filcher.EngineerNotes2",
                "filcher.EngineerNotes3",
                "filcher.EngineerNotes4",
                "filcher.EngineerNotes5",
                "filcher.FarmingNotes1",
                "filcher.FarmingNotes2",
                "filcher.FarmingNotes3",
                "filcher.FishingNotes1",
                "filcher.FishingNotes2",
                "filcher.HerbalistNotes",
                "filcher.HuntingNotes1",
                "filcher.HuntingNotes2",
                "filcher.HuntingNotes3",
                "filcher.MechanicNotes1",
                "filcher.MechanicNotes2",
                "filcher.MechanicNotes3",
                "filcher.MetalworkNotes1",
                "filcher.MetalworkNotes2",
                "filcher.MetalworkNotes3",
                "filcher.MetalworkNotes4",
                "filcher.RadioNotes1",
                "filcher.RadioNotes2",
                "filcher.RadioNotes3",
                "filcher.SFBookFarm",
                "filcher.SFCookingGuide",
                "filcher.SFCookingMag1",
                "filcher.SFCookingMag2",
                "filcher.SFCookingMag3",
                "filcher.SFCookingNotes1",
                "filcher.SFFarmMag2",
                "filcher.SFFarmMag3",
                "filcher.SFGuideCooking",
                "filcher.SFGuideEletronics",
                "filcher.SFGuideEngineering",
                "filcher.SFGuideFishing",
                "filcher.SFGuideMechanics",
                "filcher.SFGuideMetalworking",
                "filcher.SFGuideRadio",
                "filcher.SFGuideTrapping",
                "filcher.SFMasonMag",
                "filcher.SFMetalworkMag5",
                "filcher.SmithingNotes1",
                "filcher.SmithingNotes2",
                "filcher.SmithingNotes3",
                "filcher.SmithingNotes4",
                "filcher.SmithingNotes5",
            },
        },
        LitS = {
            items = {
                "Base.BookPhotography1",
                "Base.BookPhotography2",
                "Base.BookPhotography3",
                "Base.BookPhotography4",
                "Base.BookPhotography5",
                "filcher.BookMasonry1",
                "filcher.BookMasonry2",
                "filcher.BookMasonry3",
                "filcher.BookMasonry4",
                "filcher.BookMasonry5",
            },
        },
        LitW = {
            items = {
                "Base.PhotographicPaper",
                "filcher.GreenPen",
                "filcher.MulticolorPen",
            },
        },
        Misc = {
            items = {
                "filcher.SFSnowball",
            },
        },
        SurFarm = {
            items = {
                "filcher.BeetBagSeed",
                "filcher.BeetSeed",
                "filcher.CauliflowerBagSeed",
                "filcher.CauliflowerSeed",
                "filcher.CornBagSeed",
                "filcher.CornSeed",
                "filcher.GardeningSprayCigarettes",
                "filcher.GardeningSprayMilk",
                "filcher.LettuceBagSeed",
                "filcher.LettuceSeed",
                "filcher.SFLemonGrassBagSeed",
                "filcher.SFLemonGrassSeed",
                "filcher.SFWheatBagSeed",
                "filcher.SFWheatSeed",
                "filcher.TeaBagSeed",
                "filcher.TeaSeed",
            },
        },
        Tool = {
            items = {
                "filcher.BatteryLamp",
                "filcher.Flare",
                "filcher.GasLantern",
                "filcher.GasLanternEmpty",
                "filcher.GasLanternLit",
                "filcher.HandTruckBlue",
                "filcher.HandTruckRed",
                "filcher.HeadTorch",
                "filcher.MasonsTrowel",
                "filcher.SFChisel",
                "filcher.SFGrainGrinder",
                "filcher.TorchBranch",
                "filcher.TorchBranchLit",
                "filcher.TorchChairLeg",
                "filcher.TorchChairLegLit",
                "filcher.TorchPlank",
                "filcher.TorchPlankLit",
                "filcher.TorchTableLeg",
                "filcher.TorchTableLegLit",
            },
        },
        WepMelee = {
            items = {
                "filcher.ClosedUmbrellaPink",
                "filcher.PoolballInSock",
                "filcher.Recorder",
                "filcher.UmbrellaPink",
                "filcher.WalkingCane",
                "filcher.WoodenCross",
            },
        },
        WepRange = {
            items = {
                "filcher.NailGun",
            },
        },
    },
})
