--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Tsar's mods (Autotsar & co).
-- Covers Tsar's vehicle/trailer/boat mods, True Actions Dancing and
-- True Music (Tsarcraft). See the mods list below for the Workshop IDs.
--
-- The 75 explicit TAD dance mags/cards are mapped to Literature-Recipe /
-- Collectable. The old core also had a rule sending every other TAD
-- module item of type "Normal" to Misc; that is reproduced faithfully
-- as a scoped pack rule below (explicit overrides still win).
--
-- Mappings migrated from Better Sorting (TsarMods_Items.lua), "Cont" -> "Container".
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "TsarMods",
    mods = { "agrotsar", "AquatsarYachtClub", "ATA_Bus", "ATA_Mustang", "ATA_Mustang_x2", "ATA_Mustang_x4", "ATA_Jeep", "ATA_Jeep_x2", "ATA_Jeep_x4", "ATA_Jeep_x10", "ATA_Dadge", "ATA_Luton", "ATA_Petyarbuilt", "ATA_Samara", "ATA_VanDeRumba", "amclub", "autotsartrailers", "TrueActionsDancing", "truemusic", "tsarslib", "TMC_Trolley" },
    rules = {
        { module = "TAD", type = "Normal", category = "Misc" },
    },
    data = {
        ClothHead = {
            items = {
                "Aquatsar.DivingMask",
            },
        },
        Collect = {
            items = {
                "TAD.BobTA_Afoxe_Samba_Raggae_card",
                "TAD.BobTA_Belly_Dancing_One_card",
                "TAD.BobTA_Belly_Dancing_Three_card",
                "TAD.BobTA_Belly_Dancing_Two_card",
                "TAD.BobTA_Boogaloo_card",
                "TAD.BobTA_Breakdance_1990_card",
                "TAD.BobTA_Breakdance_Freezes_Combo_card",
                "TAD.BobTA_Charleston_card",
                "TAD.BobTA_Gandy_card",
                "TAD.BobTA_House_Dancing_card",
                "TAD.BobTA_Locking_card",
                "TAD.BobTA_Moonwalk_Two_card",
                "TAD.BobTA_Northern_Soul_Spin_Dip_and_Splits_card",
                "TAD.BobTA_Northern_Soul_Spin_and_Floor_Work_card",
                "TAD.BobTA_Rick_Dancing_card",
                "TAD.BobTA_Robot_One_card",
                "TAD.BobTA_Robot_Two_card",
                "TAD.BobTA_Salsa_Two_card",
                "TAD.BobTA_Samba_Olodum_card",
                "TAD.BobTA_Samba_Pagode_card",
                "TAD.BobTA_Slide_Step_card",
                "TAD.BobTA_Snake_card",
                "TAD.BobTA_Thriller_Four_card",
                "TAD.BobTA_Thriller_One_card",
                "TAD.BobTA_Thriller_Three_card",
                "TAD.BobTA_Thriller_Two_card",
                "TAD.BobTA_Tut_One_card",
                "TAD.BobTA_Tut_Two_card",
                "TAD.BobTA_Wave_One_card",
                "TAD.BobTA_Wave_Two_card",
            },
        },
        Container = {
            items = {
                "ATA2.ATA2ItemContainer",
            },
        },
        Elec = {
            items = {
                "Base.TsarEarthing",
                "Tsarcraft.TCBoombox",
                "Tsarcraft.TCVinylplayer",
                "Tsarcraft.TCWalkman",
            },
        },
        FoodN = {
            items = {
                "TAD.CloseKosmotsars",
            },
        },
        Furn = {
            items = {
                "Base.TransportCounter",
                "Base.TransportCupboard",
                "Base.TransportDrawer",
                "Base.TransportFreezer",
                "Base.TransportFridge",
                "Base.TransportMedicine",
                "Base.TransportMicrowave",
                "Base.TransportOven",
                "Base.TransportSeatBoxWooden",
                "Base.TransportShelve",
            },
        },
        Junk = {
            items = {
                "Aquatsar.TaintedLiterature",
            },
        },
        LitR = {
            items = {
                "Agrotsar.AgrotsarMag",
                "Aquatsar.BoatMag",
                "Aquatsar.SwimMag",
                "Autotsar.ATADodgeTuningMag",
                "Autotsar.ATALutonTuningMag",
                "Autotsar.ATAPetyarbuiltTuningMag",
                "Autotsar.ATATuningFordMustang",
                "Autotsar.ATAVanDeRumbaTuningMag",
                "Autotsar.AtTuningMagBus",
                "Autotsar.AtTuningMagJeep",
                "Autotsar.Bullbar2Blueprint",
                "Autotsar.Bullbar3Blueprint",
                "TAD.BobTA_African_Noodle_Mag",
                "TAD.BobTA_African_Rainbow_Mag",
                "TAD.BobTA_Arm_Push_Mag",
                "TAD.BobTA_Arm_Wave_One_Mag",
                "TAD.BobTA_Arms_Hip_Hop_Mag",
                "TAD.BobTA_Around_The_World_Mag",
                "TAD.BobTA_Bboy_Hip_Hop_One_Mag",
                "TAD.BobTA_Bboy_Hip_Hop_Three_Mag",
                "TAD.BobTA_Bboy_Hip_Hop_Two_Mag",
                "TAD.BobTA_Body_Wave_Mag",
                "TAD.BobTA_Booty_Step_Mag",
                "TAD.BobTA_Breakdance_Brooklyn_Uprock_Mag",
                "TAD.BobTA_Cabbage_Patch_Mag",
                "TAD.BobTA_Can_Can_Mag",
                "TAD.BobTA_Chicken_Mag",
                "TAD.BobTA_Crazy_Legs_Mag",
                "TAD.BobTA_Defile_De_Samba_Parade_Mag",
                "TAD.BobTA_Hokey_Pokey_Mag",
                "TAD.BobTA_Kick_Step_Mag",
                "TAD.BobTA_Macarena_Mag",
                "TAD.BobTA_Maraschino_Mag",
                "TAD.BobTA_MoonWalk_One_Mag",
                "TAD.BobTA_Northern_Soul_Spin_Mag",
                "TAD.BobTA_Northern_Soul_Spin_On_Floor_Mag",
                "TAD.BobTA_Raise_The_Roof_Mag",
                "TAD.BobTA_Really_Twirl_Mag",
                "TAD.BobTA_Rib_Pops_Mag",
                "TAD.BobTA_Rockette_Kick_Mag",
                "TAD.BobTA_Rumba_Dancing_Mag",
                "TAD.BobTA_Running_Man_One_Mag",
                "TAD.BobTA_Running_Man_Three_Mag",
                "TAD.BobTA_Running_Man_Two_Mag",
                "TAD.BobTA_Salsa_Double_Twirl_Mag",
                "TAD.BobTA_Salsa_Double_Twirl_and_Clap_Mag",
                "TAD.BobTA_Salsa_Mag",
                "TAD.BobTA_Salsa_Side_to_Side_Mag",
                "TAD.BobTA_Shim_Sham_Mag",
                "TAD.BobTA_Shimmy_Mag",
                "TAD.BobTA_Shuffling_Mag",
                "TAD.BobTA_Side_to_Side_Mag",
                "TAD.BobTA_Twist_One_Mag",
                "TAD.BobTA_Twist_Two_Mag",
                "TAD.BobTA_Uprock_Indian_Step_Mag",
                "TAD.BobTA_YMCA_Mag",
            },
        },
        Mech = {
            items = {
                "ATA2.ATABullbar1Item",
                "ATA2.ATABullbar2Item",
                "ATA2.ATABullbarPoliceItem1",
                "ATA2.ATAFendersWideItem",
                "ATA2.ATASkirtsSideItem",
                "ATA2.ATASpoilerFrontItem",
                "ATA2.ATASpoilerRear1Item",
                "ATA2.ATASpoilerRear2Item",
                "Agrotsar.APlowshare",
                "Agrotsar.ASeederPlate",
                "Agrotsar.ASeederTankLarge",
                "Agrotsar.ASeederTankMedium",
                "Agrotsar.ASeederTankSmall",
                "Aquatsar.AirBagNormal1",
                "Aquatsar.AirBagNormal2",
                "Aquatsar.AirBagNormal3",
                "Aquatsar.BoatPropeller",
                "Aquatsar.ManualStarter",
                "Aquatsar.NotRemovableBoatSeat1",
                "Aquatsar.NotRemovableBoatSeat2",
                "Aquatsar.NotRemovableBoatSeat3",
                "Aquatsar.Sails",
                "Autotsar.ATADodgeBullbar1Item",
                "Autotsar.ATADodgeBullbar2Item",
                "Autotsar.ATADodgeBullbar3Item",
                "Autotsar.ATADodgeProtectionWindowFrontItem",
                "Autotsar.ATADodgeProtectionWindowSideItem",
                "Autotsar.ATADodgeRoofRackItem",
                "Autotsar.ATADodgeWindowRackItem",
                "Autotsar.ATAJeepBumper1Item",
                "Autotsar.ATAJeepBumper2Item",
                "Autotsar.ATAJeepBumper3Item",
                "Autotsar.ATAJeepBumper4Item",
                "Autotsar.ATAJeepInteractiveTrunkRoofRackItem",
                "Autotsar.ATAJeepInteractiveTrunkWheelRackItem",
                "Autotsar.ATAJeepProtectionWindowFrontItem",
                "Autotsar.ATAJeepProtectionWindowItem",
                "Autotsar.ATAJeepProtectionWindowRearItem",
                "Autotsar.ATAJeepRoofBaseItem",
                "Autotsar.ATAJeepRoofTentItem",
                "Autotsar.ATAJeepSnorkelItem",
                "Autotsar.ATALutonInteractiveTrunkRoofRackItem",
                "Autotsar.ATALutonLadderItem",
                "Autotsar.ATALutonProtectionHoodItem",
                "Autotsar.ATALutonProtectionSideFrontItem",
                "Autotsar.ATALutonProtectionWindowFrontItem",
                "Autotsar.ATALutonProtectionWindowFrontSideItem",
                "Autotsar.ATAMotoBMWClassicMuffler",
                "Autotsar.ATAMotoBMWCustomMuffler",
                "Autotsar.ATAMotoBMWGasTank",
                "Autotsar.ATAMotoBMWModernTire",
                "Autotsar.ATAMotoBMWNormalTire",
                "Autotsar.ATAMotoBMWOldTire",
                "Autotsar.ATAMotoBMWSeat",
                "Autotsar.ATAMotoBMWSeatCustom",
                "Autotsar.ATAMotoBagBMW1",
                "Autotsar.ATAMotoBagBMW2",
                "Autotsar.ATAMotoHarleyBag",
                "Autotsar.ATAMotoHarleyGasTank",
                "Autotsar.ATAMotoHarleyHolster",
                "Autotsar.ATAMotoHarleyModernTire",
                "Autotsar.ATAMotoHarleyMuffler",
                "Autotsar.ATAMotoHarleyNormalTire",
                "Autotsar.ATAMotoHarleyOldTire",
                "Autotsar.ATAMotoHarleySeat",
                "Autotsar.ATAMotoQuadSeat",
                "Autotsar.ATAMustangBullbar1Item",
                "Autotsar.ATAMustangBullbar2Item",
                "Autotsar.ATAMustangBullbar3Item",
                "Autotsar.ATAMustangFendersWideItem",
                "Autotsar.ATAMustangHood2Item3",
                "Autotsar.ATAMustangHood3Item3",
                "Autotsar.ATAMustangHood4Item3",
                "Autotsar.ATAMustangProtectionWindowFrontItem",
                "Autotsar.ATAMustangProtectionWindowLeftItem",
                "Autotsar.ATAMustangProtectionWindowRearItem",
                "Autotsar.ATAMustangProtectionWindowRightItem",
                "Autotsar.ATAMustangRoofRackItem",
                "Autotsar.ATAMustangSkirtsSideItem",
                "Autotsar.ATAMustangSpoilerFrontItem",
                "Autotsar.ATAMustangSpoilerRear1Item",
                "Autotsar.ATAMustangSpoilerRear2Item",
                "Autotsar.ATAPetyarbuiltProtectionGasTankItem",
                "Autotsar.ATAPetyarbuiltProtectionRearWheelsItem",
                "Autotsar.ATAPetyarbuiltProtectionSideFrontItem",
                "Autotsar.ATAPetyarbuiltProtectionSideItem",
                "Autotsar.ATAPetyarbuiltProtectionSideTopItem",
                "Autotsar.ATAPetyarbuiltProtectionSleeperItem",
                "Autotsar.ATASamaraHood2Item3",
                "Autotsar.ATASamaraHood3Item3",
                "Autotsar.ATATuningChevalierSamara",
                "Autotsar.ATAVanDeRumbRoofBoxItem",
                "Autotsar.ATAVanDeRumbaBullbar1Item",
                "Autotsar.ATAVanDeRumbaBullbar2Item",
                "Autotsar.ATAVanDeRumbaBullbar3Item",
                "Autotsar.ATAVanDeRumbaInteractiveTrunkRoofRackItem",
                "Autotsar.ATAVanDeRumbaLadderItem",
                "Autotsar.ATAVanDeRumbaProtectionHoodItem",
                "Autotsar.ATAVanDeRumbaProtectionWindowFrontItem",
                "Autotsar.ATAVanDeRumbaProtectionWindowFrontSideItem",
                "Autotsar.ATAVanDeRumbaProtectionWindowRearItem",
                "Autotsar.ATAVanDeRumbaRoofBaseItem",
                "Autotsar.ATA_Bus_Kengur_1_Item",
                "Autotsar.ATA_Bus_Kengur_2_Item",
                "Autotsar.ATA_Bus_Kengur_3_Item",
                "Autotsar.ATA_Bus_Protection_door_Item",
                "Autotsar.ATA_Bus_Protection_door_rear_Item",
                "Autotsar.ATA_Bus_Protection_wheels_Item",
                "Autotsar.ATA_Bus_Protection_windows_front_Item",
                "Autotsar.ATA_Bus_Protection_windows_left_Item",
                "Autotsar.ATA_Bus_Protection_windows_right_Item",
                "Autotsar.ATA_Bus_Roof_Box_Item",
                "Autotsar.ATA_Bus_Roof_Rack",
                "Autotsar.TrailerFirstTrunk",
                "Autotsar.TrailerSecondTrunk",
                "Base.1000Tank1",
                "Base.1000Tank2",
                "Base.1000Tank3",
                "Base.500Tank1",
                "Base.500Tank2",
                "Base.500Tank3",
                "Base.ATA1000Trunk",
                "Base.ATA1000Trunk1",
                "Base.ATA1000Trunk2",
                "Base.ATA1000Trunk3",
                "Base.ATA1100Trunk",
                "Base.ATA1100Trunk1",
                "Base.ATA1100Trunk2",
                "Base.ATA1100Trunk3",
                "Base.ATA1200Trunk",
                "Base.ATA1200Trunk1",
                "Base.ATA1200Trunk2",
                "Base.ATA1200Trunk3",
                "Base.ATA150Trunk",
                "Base.ATA150Trunk1",
                "Base.ATA150Trunk2",
                "Base.ATA150Trunk3",
                "Base.ATA200Trunk",
                "Base.ATA200Trunk1",
                "Base.ATA200Trunk2",
                "Base.ATA200Trunk3",
                "Base.ATA250Trunk",
                "Base.ATA250Trunk1",
                "Base.ATA250Trunk2",
                "Base.ATA250Trunk3",
                "Base.ATA300Trunk",
                "Base.ATA300Trunk1",
                "Base.ATA300Trunk2",
                "Base.ATA300Trunk3",
                "Base.ATA400Trunk",
                "Base.ATA400Trunk1",
                "Base.ATA400Trunk2",
                "Base.ATA400Trunk3",
                "Base.ATA500Trunk",
                "Base.ATA500Trunk1",
                "Base.ATA500Trunk2",
                "Base.ATA500Trunk3",
                "Base.ATA600Trunk",
                "Base.ATA600Trunk1",
                "Base.ATA600Trunk2",
                "Base.ATA600Trunk3",
                "Base.ATA700Trunk",
                "Base.ATA700Trunk1",
                "Base.ATA700Trunk2",
                "Base.ATA700Trunk3",
                "Base.ATA800Trunk",
                "Base.ATA800Trunk1",
                "Base.ATA800Trunk2",
                "Base.ATA800Trunk3",
                "Base.ATA900Trunk",
                "Base.ATA900Trunk1",
                "Base.ATA900Trunk2",
                "Base.ATA900Trunk3",
                "Base.ATAFreestorageTrunk",
                "Base.ATAProtectionWheelsChain",
                "Base.ATARoofLightItem",
                "Base.ATASleepingBag",
                "Base.ATASpoilerFront",
                "Base.ATSMegaTrunk",
                "Base.BoatAnchor",
                "Base.BoatMotorName_Default_Item",
                "Base.BoatMotorName_NP_Item",
                "Base.BoatMotorName_Orianna_Item",
                "Base.SailingYachtName_Default_Item",
                "Base.SailingYachtName_La_Brigandine_Item",
                "Base.SailingYachtName_Sakharov_Item",
                "Base.partBoatMotor",
                "Base.partBoatSailingYacht",
            },
        },
        Tool = {
            items = {
                "Aquatsar.Compass",
                "Aquatsar.DeflatedTireTube",
                "Aquatsar.Lifebuoy",
                "Aquatsar.TireTube",
                "TMC.CartContainer",
                "TMC.CartContainer2",
                "TMC.TrolleyContainer",
                "TMC.TrolleyContainer2",
            },
        },
    },
})
