--------------------------------------------------------------------------------
-- Better Sorting Reborn — mod-support pack: Unknown Clothing Store.
-- https://steamcommunity.com/sharedfiles/filedetails/?id=2810771031
--
-- The mod declares all its cosplay outfits in the Base module under short
-- numeric names (Base.502, Base.36, …); none of them is a vanilla item, and
-- the whole set is guarded by the single "Cosplaywa" mod ID.
--
-- Seven outfits are carried by a scoped rule instead of an explicit list:
-- their names ("Base.Little Busters" and six Chinese ones) contain a space
-- or non-ASCII characters, both rejected by BSR's strict item format. The
-- rule applies the same ClothBody mapping the original used.
--
-- Mappings migrated from Better Sorting v2.0.4 (UnknownClothingStore_Items.lua).
--------------------------------------------------------------------------------

BSR = BSR or {}
BSR.ModPacks = BSR.ModPacks or {}

table.insert(BSR.ModPacks, {
    name = "UnknownClothingStore",
    mods = { "Cosplaywa" },
    rules = {
        {
            contains = {
                "Base.Little Busters",
                "Base.入学新生",
                "Base.水手夏装",
                "Base.猎人套装",
                "Base.生徒会长",
                "Base.秋意渐浓",
                "Base.西点毕业生",
            },
            category = "ClothBody",
        },
    },
    data = {
        ClothBody = {
            items = {
                "Base.003",
                "Base.007",
                "Base.01",
                "Base.02",
                "Base.021",
                "Base.022",
                "Base.023",
                "Base.032",
                "Base.035",
                "Base.037",
                "Base.041",
                "Base.042",
                "Base.045",
                "Base.0499",
                "Base.05",
                "Base.058",
                "Base.11",
                "Base.12",
                "Base.15",
                "Base.170",
                "Base.173",
                "Base.191",
                "Base.20",
                "Base.200",
                "Base.202",
                "Base.203",
                "Base.206",
                "Base.207",
                "Base.208",
                "Base.209",
                "Base.21",
                "Base.210",
                "Base.211",
                "Base.212",
                "Base.2121",
                "Base.217",
                "Base.218",
                "Base.22",
                "Base.220",
                "Base.222",
                "Base.223",
                "Base.224",
                "Base.228",
                "Base.23",
                "Base.230",
                "Base.231",
                "Base.232",
                "Base.233",
                "Base.234",
                "Base.235",
                "Base.236",
                "Base.237",
                "Base.238",
                "Base.239",
                "Base.24",
                "Base.240",
                "Base.241",
                "Base.242",
                "Base.243",
                "Base.244",
                "Base.245",
                "Base.246",
                "Base.247",
                "Base.248",
                "Base.249",
                "Base.25",
                "Base.250",
                "Base.251",
                "Base.252",
                "Base.253",
                "Base.254",
                "Base.255",
                "Base.256",
                "Base.258",
                "Base.259",
                "Base.26",
                "Base.260",
                "Base.261",
                "Base.262",
                "Base.264",
                "Base.265",
                "Base.266",
                "Base.267",
                "Base.268",
                "Base.269",
                "Base.27",
                "Base.270",
                "Base.271",
                "Base.272",
                "Base.275",
                "Base.28",
                "Base.283",
                "Base.29",
                "Base.30",
                "Base.300",
                "Base.301",
                "Base.31",
                "Base.35",
                "Base.36",
                "Base.38",
                "Base.4",
                "Base.40",
                "Base.400",
                "Base.401",
                "Base.402",
                "Base.404",
                "Base.405",
                "Base.406",
                "Base.407",
                "Base.408",
                "Base.409",
                "Base.410",
                "Base.411",
                "Base.42",
                "Base.44",
                "Base.45",
                "Base.47",
                "Base.48",
                "Base.49",
                "Base.500",
                "Base.501",
                "Base.502",
                "Base.51",
                "Base.53",
                "Base.531",
                "Base.55",
                "Base.56",
                "Base.57",
                "Base.58",
                "Base.59",
                "Base.6",
                "Base.60",
                "Base.61",
                "Base.66",
                "Base.70",
                "Base.71",
                "Base.72",
                "Base.74",
                "Base.75",
                "Base.76",
                "Base.77",
                "Base.78",
                "Base.79",
                "Base.80",
                "Base.81",
                "Base.88",
                "Base.902",
                "Base.90499",
                "Base.911",
                "Base.912",
                "Base.915",
                "Base.9161",
                "Base.920",
                "Base.921",
                "Base.92121",
                "Base.924",
                "Base.9240",
                "Base.925",
                "Base.926",
                "Base.927",
                "Base.9275",
                "Base.928",
                "Base.9283",
                "Base.929",
                "Base.930",
                "Base.933",
                "Base.934",
                "Base.936",
                "Base.938",
                "Base.939",
                "Base.94",
                "Base.940",
                "Base.943",
                "Base.944",
                "Base.949",
                "Base.951",
                "Base.952",
                "Base.953",
                "Base.954",
                "Base.955",
                "Base.957",
                "Base.959",
                "Base.9591",
                "Base.96",
                "Base.960",
                "Base.961",
                "Base.970",
                "Base.971",
                "Base.972",
                "Base.974",
                "Base.975",
                "Base.978",
                "Base.99",
                "Base.9Naganami",
                "Base.Naganami",
                "Base.aa",
                "Base.aa1",
                "Base.aa2",
                "Base.bigbag",
                "Base.d",
                "Base.r",
                "Base.tail1",
            },
        },
        WepMelee = {
            items = {
                "Base.111",
            },
        },
    },
})
