local vanillaMilitaryZones = {
--Secret Base
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 5830, y = 12477, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5803, y = 12473, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5814, y = 12476, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5838, y = 12487, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5830, y = 12495, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5859, y = 12492, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5871, y = 12489, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5525, y = 12485, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 5598, y = 12447, z = 0, width = 5, height = 25, properties = { Direction = "W" } },
  { name = "military_vehicle", type = "ParkingStall", x = 5587, y = 12447, z = 0, width = 5, height = 25, properties = { Direction = "E" } },
  { name = "military_container", type = "ParkingStall", x = 5569, y = 12441, z = 0, width = 5, height = 14, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 5583, y = 12435, z = 0, width = 6, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_trailer", type = "ParkingStall", x = 5594, y = 12435, z = 0, width = 12, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5538, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5550, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5557, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5589, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5599, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5615, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5621, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5629, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5538, y = 12435, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirectmion = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5554, y = 12436, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5563, y = 12436, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 5531, y = 12441, z = 0, width = 3, height = 5, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5530, y = 12451, z = 0, width = 3, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 5782, y = 12490, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
--Lousiville Checkpoint
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 12506, y = 4339, z = 0, width = 3, height = 5, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 12515, y = 4350, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12505, y = 4203, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12509, y = 4485, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 12514, y = 4478, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 12540, y = 4316, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 12554, y = 4319, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 12465, y = 4225, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12545, y = 4238, z = 0, width = 3, height = 4, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12466, y = 4263, z = 0, width = 4, height = 6, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 12534, y = 4203, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_container", type = "ParkingStall", x = 12524, y = 4244, z = 0, width = 4, height = 10, properties = { Direction = "S" } },
  { name = "military_vehicle", type = "ParkingStall", x = 12524, y = 4355, z = 0, width = 21, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_angled", type = "ParkingStall", x = 12726, y = 3960, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12694, y = 3963, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_burnt", type = "ParkingStall", x = 12716, y = 3995, z = 0, width = 6, height = 4 },
  { name = "military_burnt", type = "ParkingStall", x = 12763, y = 3989, z = 0, width = 4, height = 6 },
  { name = "military_burnt", type = "ParkingStall", x = 12597, y = 4154, z = 0, width = 4, height = 6 },
--East Army Camp near Louisville
  { name = "military_vehicle_angled", type = "ParkingStall", x = 15598, y = 3882, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 15648, y = 3905, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_container", type = "ParkingStall", x = 15645, y = 3919, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 15605, y = 3918, z = 0, width = 6, height = 4, properties = { Direction = "E" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 15607, y = 3934, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 15612, y = 3934, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 15579, y = 3903, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 15581, y = 3915, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_container", type = "ParkingStall", x = 15579, y = 3934, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_container", type = "ParkingStall", x = 15586, y = 3934, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "military_container", type = "ParkingStall", x = 15574, y = 3917, z = 0, width = 3, height = 15, properties = { Direction = "N" } },
--Burnt Town near Louisville
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 13442, y = 4071, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 14538, y = 4019, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_angled", type = "ParkingStall", x = 13610, y = 4080, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
--March Ridge
  { name = "military_vehicle", type = "ParkingStall", x = 10353, y = 12424, z = 0, width = 5, height = 17, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 10353, y = 12404, z = 0, width = 3, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 10371, y = 12403, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 10373, y = 12381, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 10362, y = 12386, z = 0, width = 4, height = 6, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 9920, y = 12613, z = 0, width = 10, height = 5, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_light_angled", type = "ParkingStall", x = 9930, y = 12630, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle", type = "ParkingStall", x = 9943, y = 12619, z = 0, width = 5, height = 15, properties = { Direction = "E" } },
  { name = "military_container", type = "ParkingStall", x = 9943, y = 12608, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_container", type = "ParkingStall", x = 9943, y = 12601, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 9918, y = 12633, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 10105, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 10092, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy_angled", type = "ParkingStall", x = 10077, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
--Irvington
  { name = "military_container", type = "ParkingStall", x = 979, y = 11484, z = 0, width = 6, height = 4, properties = { Direction = "E" } },
--Brandenburg
  { name = "military_container", type = "ParkingStall", x = 1496, y = 5524, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 1504, y = 5618, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 1498, y = 5619, z = 0, width = 4, height = 6, properties = { Direction = "S" } },
  { name = "military_vehicle", type = "ParkingStall", x = 1509, y = 5560, z = 0, width = 21, height = 5, properties = { Direction = "N" } },
  { name = "military_trailer", type = "ParkingStall", x = 1513, y = 5544, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_burnt", type = "ParkingStall", x = 1530, y = 5621, z = 0, width = 3, height = 6 },
  { name = "military_burnt", type = "ParkingStall", x = 1536, y = 5545, z = 0, width = 5, height = 4 },
}

return vanillaMilitaryZones