require 'Items/ProceduralDistributions'
require 'Items/SuburbsDistributions'
require 'Items/Distributions'
require "Vehicles/VehicleDistributions"

-- =========================================================
-- Helper para obtener el multiplicador del Sandbox
-- =========================================================
local function CC_WorldLootMult()
    if not SandboxVars or not SandboxVars.CamisetaChilena then return 1 end
    if not SandboxVars.CamisetaChilena.EnableMod then return 0 end
    return SandboxVars.CamisetaChilena.WorldLootMultiplier or 1
end

-- =========================================================
-- Tabla de definiciones
-- =========================================================
local CamisetaChilena_Loot = {

   	SchoolLockers = {
        {"CamisetaChilena.Camisa_Escolar", 1.0},
        {"CamisetaChilena.Uniforme_Verde", 0.7},
        {"CamisetaChilena.Uniforme_Verde_Largo", 0.6},
        {"CamisetaChilena.Chaleco_Hombre_Verde", 0.6},
        {"CamisetaChilena.Chaleco_Verde_Mujer", 0.6},
        {"CamisetaChilena.Falda_Cuadrille", 0.6},
        {"CamisetaChilena.Pantalones_Cuadrille", 0.6},
        {"CamisetaChilena.Pantalones_Negros", 0.6},
        {"CamisetaChilena.Corbata_Hombre_Escolar", 0.8},
        {"CamisetaChilena.Humita_Mujer_Verde", 0.7},
        {"CamisetaChilena.Zapatos_Blancos", 0.5},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.3},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.3},
        {"CamisetaChilena.Hoodie_Ponmi", 0.3},
        {"CamisetaChilena.Camiseta_Minecraft", 0.4},
        {"CamisetaChilena.Camiseta_Hellfire", 0.3},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.3},
        {"CamisetaChilena.Camiseta_Pulentos", 0.3},
        {"CamisetaChilena.Camiseta_Dewey", 0.3},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Gakuran_MuyNegro", 0.1},
        {"CamisetaChilena.Gakuran_MuyNegroAbierto", 0.1},
        {"CamisetaChilena.Camiseta_Zombhub", 0.01},
    },
	
	SchoolLockersBad = {
        {"CamisetaChilena.Camiseta_Zombhub", 0.4},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.1},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.5},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.6},
        {"CamisetaChilena.Camiseta_Duki", 0.6},
        {"CamisetaChilena.Gorra_BZRP", 0.5},
        {"CamisetaChilena.Gorra_Duki_Atras", 0.4},
        {"CamisetaChilena.Dolphin_Short_31_Min", 0.5},
    },
	
	GasStorageCombo = {
        {"CamisetaChilena.Apron_Pronto", 1.2},
        {"CamisetaChilena.ApronWaist_Pronto", 0.8},
        {"CamisetaChilena.Camiseta_Oxxo", 1.0},
    },

    CafeKitchenCoffee = {
        {"CamisetaChilena.Apron_Juan_Valdez", 1.5},
        {"CamisetaChilena.Apron_Starbucks", 1.2},
        {"CamisetaChilena.ApronWaist_Starbucks", 0.8},
    },

    BakeryKitchenBaking = {
        {"CamisetaChilena.Apron_Gengar", 1.0},
        {"CamisetaChilena.ApronWaist_Gengar", 0.8},
    },

    KitchenCannedFood = {
        {"CamisetaChilena.Apron_Pronto", 0.3},
        {"CamisetaChilena.Apron_Gengar", 0.3},
    },

    StoreShelfSnacks = {
        {"CamisetaChilena.Camiseta_Oxxo", 0.6},
    },

    DinerBackRoomCounter = {
        {"CamisetaChilena.Apron_Pronto", 0.8},
        {"CamisetaChilena.ApronWaist_Pronto", 0.5},
    },

    CrateCoffee = {
        {"CamisetaChilena.Apron_Juan_Valdez", 1.0},
    },
    
    GigamartBBQ = {
        {"CamisetaChilena.Apron_Gengar", 0.6},
        {"CamisetaChilena.Apron_Starbucks", 0.4},
    },

    ClothingStoresSport = {
        {"CamisetaChilena.Camiseta_Vidal", 0.8},
        {"CamisetaChilena.Camiseta_Sanchez", 0.8},
        {"CamisetaChilena.Camiseta_Valdivia", 0.6},
        {"CamisetaChilena.Camiseta_Figueroa", 0.4},
        {"CamisetaChilena.Camiseta_Bravo", 0.4},
        {"CamisetaChilena.Camiseta_Bravo_2", 0.4},
        {"CamisetaChilena.Camiseta_Endler", 0.4},
        {"CamisetaChilena.Short_Chileno", 1.0},
        {"CamisetaChilena.Short_Chileno_Girl", 1.0},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.5},
        {"CamisetaChilena.Jersey_Curry", 0.5},
        {"CamisetaChilena.Jersey_Sakuragi", 0.3},
        {"CamisetaChilena.Camiseta_Chicago_Bulls", 0.6},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.2},
        {"CamisetaChilena.Jersey_Xokas", 0.1},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.5},
        {"CamisetaChilena.Camiseta_Alexa", 0.4},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.3},
        {"CamisetaChilena.Camiseta_John_Cena", 0.4},
        {"CamisetaChilena.Camiseta_Vaquer", 0.4},
        {"CamisetaChilena.Camiseta_Roja", 0.5},
		{"CamisetaChilena.Camiseta_Alexa_2", 0.4},
        {"CamisetaChilena.Camiseta_Alexa_3", 0.4},
        {"CamisetaChilena.Camiseta_Kairi", 0.4},
        {"CamisetaChilena.Camiseta_Liv", 0.4},
        {"CamisetaChilena.Camiseta_Liv_2", 0.4},
        {"CamisetaChilena.Camiseta_Rey_Misterio", 0.4},
        {"CamisetaChilena.Jersey_Negra", 0.5},
        {"CamisetaChilena.Suit_SquidGame_Verde", 0.3},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
	
    },
	
    ClothingStoresSummer = {
        {"CamisetaChilena.Bikini_Top_Alexa", 0.6},
        {"CamisetaChilena.Bikini_Top_Vaquer", 0.6},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.5},
        {"CamisetaChilena.Bikini_Top_Twice", 0.5},
        {"CamisetaChilena.Bikini_Top_31_Min", 0.5},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.1},
        {"CamisetaChilena.Bikini_Dulce_Princesa", 0.4},
        {"CamisetaChilena.Bikini_Gengar", 0.4},
        {"CamisetaChilena.Bikini_Marin", 0.4},
        {"CamisetaChilena.Bikini_Akatsuki", 0.2},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.1},
        {"CamisetaChilena.Short_Chileno", 0.8},
        {"CamisetaChilena.Short_Chileno_Girl", 0.8},
        {"CamisetaChilena.Dolphin_Shorts_31_Min", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.5},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.5},
        {"CamisetaChilena.Camiseta_Vidal", 0.4},
        {"CamisetaChilena.Camiseta_Vaquer", 0.4},
        {"CamisetaChilena.Camiseta_Alexa", 0.4},
        {"CamisetaChilena.Camiseta_Zombhub", 0.1},
		{"CamisetaChilena.Camiseta_Momo", 0.5},
        {"CamisetaChilena.Camiseta_Nayeon", 0.5},
        {"CamisetaChilena.Camiseta_Sana", 0.5},
        {"CamisetaChilena.Camiseta_Kpop", 0.5},
        {"CamisetaChilena.Hoodie_Kpop", 0.5},
        {"CamisetaChilena.Falda_Kpop", 0.3},
        {"CamisetaChilena.Pantis_Kpop", 0.3},
        {"CamisetaChilena.Short_Kpop", 0.3},
        {"CamisetaChilena.Camiseta_HarleyQuin", 0.4},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },
	
    CrateComics = {
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Bufanda_Mikasa", 0.6},
        {"CamisetaChilena.Bufanda_Inosuke", 0.6},
        {"CamisetaChilena.Bufanda_Nezuko", 0.6},
        {"CamisetaChilena.Bufanda_Tanjiro", 0.6},
        {"CamisetaChilena.Bufanda_Tomioka", 0.6},
        {"CamisetaChilena.Bufanda_Zenitsu", 0.6},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.5},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.5},
        {"CamisetaChilena.Suit_Goku", 0.1},
        {"CamisetaChilena.Suit_Saitama", 0.1},
        {"CamisetaChilena.Suit_Invencible", 0.1},
        {"CamisetaChilena.Camiseta_DBZ", 0.8},
        {"CamisetaChilena.Camiseta_DBZ_2", 0.7},
        {"CamisetaChilena.Camiseta_Minecraft", 0.8},
        {"CamisetaChilena.Pants_Ponmi", 0.4},
        {"CamisetaChilena.Hoodie_Ponmi", 0.4},
        {"CamisetaChilena.Mascara_Shaco", 0.3},
        {"CamisetaChilena.Mascara_Tulio", 0.3},
    },
	
    GymLockers = {
        {"CamisetaChilena.Short_Chileno", 1.5},
        {"CamisetaChilena.Short_Chileno_Girl", 1.5},
        {"CamisetaChilena.Camiseta_Vidal", 0.8},
        {"CamisetaChilena.Camiseta_Sanchez", 0.8},
        {"CamisetaChilena.Camiseta_Valdivia", 0.6},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.5},
        {"CamisetaChilena.Jersey_Curry", 0.5},
        {"CamisetaChilena.Jersey_Sakuragi", 0.3},
        {"CamisetaChilena.Camiseta_Roja", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.6},
        {"CamisetaChilena.Camiseta_Vaquer", 0.4},
        {"CamisetaChilena.Jersey_Xokas", 0.05},
        {"CamisetaChilena.Suit_Saitama", 0.01},
        {"CamisetaChilena.Pantalon_Rosa", 0.4},
        {"CamisetaChilena.Camiseta_Antagonista", 0.4},
		{"CamisetaChilena.Gorra_Colo", 0.4},
        {"CamisetaChilena.Gorra_Chile", 0.4},
		{"CamisetaChilena.Camiseta_Alexa_2", 0.4},
        {"CamisetaChilena.Camiseta_Alexa_3", 0.4},
        {"CamisetaChilena.Camiseta_Kairi", 0.4},
        {"CamisetaChilena.Camiseta_Liv", 0.4},
        {"CamisetaChilena.Camiseta_Liv_2", 0.4},
        {"CamisetaChilena.Camiseta_Rey_Misterio", 0.4},
        {"CamisetaChilena.Jersey_Negra", 0.5},
        {"CamisetaChilena.Suit_SquidGame_Verde", 0.3},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },
	
    ClothingStorageAllShirts = {
        {"CamisetaChilena.Camiseta_Vidal", 0.6},
        {"CamisetaChilena.Camiseta_Sanchez", 0.5},
        {"CamisetaChilena.Camiseta_Valdivia", 0.4},
        {"CamisetaChilena.Camiseta_Figueroa", 0.2},
        {"CamisetaChilena.Camiseta_Bravo", 0.2},
        {"CamisetaChilena.Camiseta_Bravo_2", 0.05},
        {"CamisetaChilena.Camiseta_Endler", 0.2},
        {"CamisetaChilena.Short_Chileno", 0.5},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.4},
        {"CamisetaChilena.Camiseta_Pulentos", 0.4},
        {"CamisetaChilena.Camiseta_Vaquer", 0.3},
        {"CamisetaChilena.Camiseta_Dewey", 0.3},
        {"CamisetaChilena.Camiseta_ST", 0.3},
        {"CamisetaChilena.Camiseta_Minecraft", 0.3},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.3},
        {"CamisetaChilena.Camiseta_Duki", 0.3},
        {"CamisetaChilena.Camiseta_Twice", 0.2},
        {"CamisetaChilena.Camiseta_Momo_Twice", 0.2},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.3},
        {"CamisetaChilena.Jersey_Sakuragi", 0.2},
        {"CamisetaChilena.Jersey_Xokas", 0.05},
        {"CamisetaChilena.Pijama_AT", 0.4},
        {"CamisetaChilena.Pants_Disney", 0.4},
        {"CamisetaChilena.Suit_Kill_Bill", 0.05},
        {"CamisetaChilena.Suit_Goku", 0.05},
        {"CamisetaChilena.Suit_Superman", 0.01},
        {"CamisetaChilena.Camiseta_Zombhub", 0.01},
    },
	
    ClothingStoresWoman = {
        {"CamisetaChilena.Short_Chileno_Girl", 1.0},
        {"CamisetaChilena.Pants_Momo_Twice", 0.5},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.4},
        {"CamisetaChilena.Camiseta_Twice", 0.6},
        {"CamisetaChilena.Camiseta_Momo_Twice", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_31_Min", 0.6},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.5},
        {"CamisetaChilena.Bikini_Top_Twice", 0.5},
        {"CamisetaChilena.Bikini_Gengar", 0.4},
        {"CamisetaChilena.Bikini_Akatsuki", 0.3},
        {"CamisetaChilena.Camiseta_Endler", 0.5},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.2},
        {"CamisetaChilena.Suit_Kill_Bill", 0.1},
        {"CamisetaChilena.Camiseta_Alexa", 0.4},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.3},
		{"CamisetaChilena.Camiseta_Momo", 0.5},
        {"CamisetaChilena.Camiseta_Nayeon", 0.5},
        {"CamisetaChilena.Camiseta_Sana", 0.5},
        {"CamisetaChilena.Camiseta_Kpop", 0.5},
        {"CamisetaChilena.Hoodie_Kpop", 0.5},
        {"CamisetaChilena.Falda_Kpop", 0.3},
        {"CamisetaChilena.Pantis_Kpop", 0.3},
        {"CamisetaChilena.Short_Kpop", 0.3},
        {"CamisetaChilena.Camiseta_HarleyQuin", 0.4},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },
	
    BedroomDresser = {
        {"CamisetaChilena.Camiseta_Vidal", 0.3},
        {"CamisetaChilena.Camiseta_Sanchez", 0.3},
        {"CamisetaChilena.Camiseta_Valdivia", 0.2},
        {"CamisetaChilena.Camiseta_Figueroa", 0.05},
        {"CamisetaChilena.Camiseta_Bravo", 0.1},
        {"CamisetaChilena.Camiseta_Bravo_2", 0.01},
        {"CamisetaChilena.Camiseta_Endler", 0.1},
        {"CamisetaChilena.Short_Chileno", 0.4},
        {"CamisetaChilena.Short_Chileno_Girl", 0.4},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.3},
        {"CamisetaChilena.Camiseta_Pulentos", 0.3},
        {"CamisetaChilena.Camiseta_Dewey", 0.2},
        {"CamisetaChilena.Camiseta_Dewey_2", 0.2},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.3},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.3},
        {"CamisetaChilena.Bikini_Dulce_Princesa", 0.2},
        {"CamisetaChilena.Bikini_Gengar", 0.2},
        {"CamisetaChilena.Bikini_Top_31_Min", 0.2},
        {"CamisetaChilena.Pijama_AT", 0.5},
        {"CamisetaChilena.Pants_Disney", 0.4},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.2},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.1},
        {"CamisetaChilena.Gorra_BZRP", 0.2},
        {"CamisetaChilena.Gorra_Duki", 0.2},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Suit_Kill_Bill", 0.01},
        {"CamisetaChilena.Suit_Goku", 0.01},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.05},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
    },
	
    WardrobeRedneck = {
        {"CamisetaChilena.Camiseta_Vidal", 0.6},
        {"CamisetaChilena.Camiseta_Sanchez", 0.6},
        {"CamisetaChilena.Short_Chileno", 0.5},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.4},
        {"CamisetaChilena.Camiseta_John_Cena", 0.4},
        {"CamisetaChilena.Camiseta_Pulentos", 0.3},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.3},
        {"CamisetaChilena.Camiseta_Hellfire", 0.2},
        {"CamisetaChilena.Jersey_Curry", 0.3},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.3},
        {"CamisetaChilena.Camiseta_Chicago_Bulls", 0.3},
        {"CamisetaChilena.Camiseta_Dewey", 0.2},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.3},
        {"CamisetaChilena.Camiseta_Vaquer", 0.2},
        {"CamisetaChilena.Gorra_BZRP", 0.2},
        {"CamisetaChilena.Gorra_31_Min", 0.2},       
        {"CamisetaChilena.Suit_Bruce_Lee", 0.05},
        {"CamisetaChilena.Apron_Juan_Valdez", 0.1},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
    },
	
    Locker = {
        {"CamisetaChilena.Camiseta_Sanchez", 0.6},
        {"CamisetaChilena.Camiseta_Vidal", 0.6},
        {"CamisetaChilena.Short_Chileno", 0.5},
        {"CamisetaChilena.Camiseta_Valdivia", 0.4},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.3},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.4},
        {"CamisetaChilena.Camiseta_John_Cena", 0.4},        
        {"CamisetaChilena.Apron_Starbucks", 0.8},
        {"CamisetaChilena.Apron_Juan_Valdez", 0.8},
        {"CamisetaChilena.Apron_Pronto", 0.8},
        {"CamisetaChilena.Gorra_31_Min", 0.4},
        {"CamisetaChilena.Gorra_BZRP", 0.4},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Jersey_Curry", 0.4},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.4},
        {"CamisetaChilena.Camiseta_Hellfire", 0.3},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
        {"CamisetaChilena.Suit_Superman", 0.01},
        {"CamisetaChilena.Bikini_Akatsuki", 0.05},
        {"CamisetaChilena.Mascara_Shaco", 0.1},
		{"CamisetaChilena.Gorra_Colo", 0.4},
        {"CamisetaChilena.Gorra_Chile", 0.4},		
        {"CamisetaChilena.Mascara_Tulio", 0.3},
    },
	
    ClosetShelfGeneric = {
        {"CamisetaChilena.Camiseta_Sanchez", 0.4},
        {"CamisetaChilena.Camiseta_Vidal", 0.4},
        {"CamisetaChilena.Short_Chileno", 0.3},
        {"CamisetaChilena.Short_Chileno_Girl", 0.3},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.3},
        {"CamisetaChilena.Camiseta_Pulentos", 0.3},
        {"CamisetaChilena.Jersey_Curry", 0.2},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.2},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Gorra_BZRP", 0.2},
        {"CamisetaChilena.Bufanda_Mikasa", 0.2},
		{"CamisetaChilena.Bufanda_BobMarley", 0.2},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Pants_Disney", 0.3},
        {"CamisetaChilena.Suit_Goku", 0.01},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
    },
	
    CrateClothesRandom = {
        {"CamisetaChilena.Camiseta_Sanchez", 0.8},
        {"CamisetaChilena.Short_Chileno", 0.6},
        {"CamisetaChilena.Camiseta_Vidal", 0.6},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.5},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.3},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.4},
        {"CamisetaChilena.Bikini_Gengar", 0.3},
        {"CamisetaChilena.Suit_Kill_Bill", 0.05},
        {"CamisetaChilena.Apron_Juan_Valdez", 0.2},
		{"CamisetaChilena.Camiseta_Chapulin", 0.3},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.3},
        {"CamisetaChilena.Camiseta_SquidGame", 0.2},
        {"CamisetaChilena.Camiseta_Daddy_Yankee", 0.4},
        {"CamisetaChilena.Camiseta_Tego_Calderon", 0.4},
    },
	
    BookstoreBooks = {
        {"CamisetaChilena.Revista_CDF_Vol1", 0.1},
        {"CamisetaChilena.Revista_Kpop_Vol1", 0.1},
        {"CamisetaChilena.Revista_Artequin_Vol1", 0.1},
        {"CamisetaChilena.Revista_Gorras_Vol1", 0.1},
        {"CamisetaChilena.Revista_Bufandas_Vol1", 0.1},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.05},
    },
	
	LibraryBooks = {
        {"CamisetaChilena.Revista_CDF_Vol1", 0.1},
        {"CamisetaChilena.Revista_Kpop_Vol1", 0.1},
        {"CamisetaChilena.Revista_Artequin_Vol1", 0.1},
        {"CamisetaChilena.Revista_Gorras_Vol1", 0.1},
        {"CamisetaChilena.Revista_Bufandas_Vol1", 0.1},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.05},
    },

    LivingRoomShelf = {
        {"CamisetaChilena.Revista_CDF_Vol1", 0.1},
        {"CamisetaChilena.Revista_Kpop_Vol1", 0.1},
        {"CamisetaChilena.Revista_Artequin_Vol1", 0.1},
        {"CamisetaChilena.Revista_Gorras_Vol1", 0.1},
        {"CamisetaChilena.Revista_Bufandas_Vol1", 0.1},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Camiseta_Endler", 0.1},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.05},
    },
	
	LivingRoomSideTable = { 
        {"CamisetaChilena.Revista_CDF_Vol1", 0.1},
        {"CamisetaChilena.Revista_Kpop_Vol1", 0.1},
        {"CamisetaChilena.Revista_Artequin_Vol1", 0.1},
        {"CamisetaChilena.Revista_Gorras_Vol1", 0.1},
        {"CamisetaChilena.Revista_Bufandas_Vol1", 0.1},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.05},
    },
	
    HolidayStuff = {
        {"CamisetaChilena.Camiseta_Bodoqe", 0.5},
        {"CamisetaChilena.Camiseta_Pulentos", 0.5},
        {"CamisetaChilena.Camiseta_Vaquer", 0.4},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
        {"CamisetaChilena.Camiseta_Sanchez", 0.3},
        {"CamisetaChilena.Camiseta_Mentita", 0.4},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Bufanda_Mikasa", 0.6},
        {"CamisetaChilena.Gorra_31_Min", 0.4},
        {"CamisetaChilena.Gorra_BZRP", 0.4},
        {"CamisetaChilena.Suit_Superman", 0.2},
        {"CamisetaChilena.Suit_Los_Increibles", 0.2},
        {"CamisetaChilena.Suit_Goku", 0.1},
        {"CamisetaChilena.Suit_Saitama", 0.1},
        {"CamisetaChilena.Suit_Kill_Bill", 0.1},
        {"CamisetaChilena.Bikini_Akatsuki", 0.2},
		{"CamisetaChilena.Mascara_Casa_Papel", 0.2},
        {"CamisetaChilena.Mascara_Tulio", 0.3},
        {"CamisetaChilena.Mascara_Marshmello", 0.2},
        {"CamisetaChilena.Mascara_Vendeta", 0.2},
        {"CamisetaChilena.Mascara_SquidGame", 0.2},
        {"CamisetaChilena.Suit_SquidGame", 0.1},
		{"CamisetaChilena.Suit_Casa_Papel", 0.1},
        {"CamisetaChilena.Suit_Shaco", 0.05},
        {"CamisetaChilena.Suit_Derpy", 0.05},
		{"CamisetaChilena.Suit_Grizzbolt", 0.05},
        {"CamisetaChilena.DerpyHead", 0.05},
		{"CamisetaChilena.RickHead", 0.05},
		{"CamisetaChilena.GrizzboltHead", 0.05},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.01},
    },

    UniversityDesk_Therapy = {
        {"CamisetaChilena.Camiseta_Hellfire", 0.5},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.1},
        {"CamisetaChilena.Camiseta_Endler", 0.1},
        {"CamisetaChilena.Gorra_31_Min", 0.3},
        {"CamisetaChilena.Camiseta_ST", 0.4},
        {"CamisetaChilena.Camiseta_WR", 0.4},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Camiseta_Minecraft", 0.3},
        {"CamisetaChilena.Mascara_Shaco", 0.1},
        {"CamisetaChilena.Mascara_Tulio", 0.3},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
    },
		
    BedroomDresserChild = {
        {"CamisetaChilena.Camiseta_Pulentos", 0.8},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.6},
        {"CamisetaChilena.Camiseta_Mentita", 0.8},
        {"CamisetaChilena.Gorra_31_Min", 0.5},
        {"CamisetaChilena.Camiseta_Dewey", 0.4},
        {"CamisetaChilena.Camiseta_Dewey_2", 0.4},
        {"CamisetaChilena.Camiseta_Minecraft", 0.8},
        {"CamisetaChilena.Camiseta_DBZ", 0.5},
        {"CamisetaChilena.Camiseta_Gengar", 0.6},
        {"CamisetaChilena.Hoodie_Ponmi", 0.5},
        {"CamisetaChilena.Camiseta_Disney", 0.7},
        {"CamisetaChilena.Pants_Disney", 0.7},
        {"CamisetaChilena.Pants_Ponmi", 0.5},
        {"CamisetaChilena.Suit_Superman", 0.1},
        {"CamisetaChilena.Suit_Los_Increibles", 0.1},
        {"CamisetaChilena.Suit_Goku", 0.05},
        {"CamisetaChilena.Suit_Saitama", 0.05},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Pijama_AT", 0.8},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.5},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.5},
        {"CamisetaChilena.Camiseta_Zombhub", 0.001},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
		
    },

    CrateRandomJunk = {
        {"CamisetaChilena.Short_Chileno", 0.3},
        {"CamisetaChilena.Camiseta_Vidal", 0.2},
        {"CamisetaChilena.Short_Chileno_Girl", 0.2},
        {"CamisetaChilena.Camiseta_Mentita", 0.2},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.2},
        {"CamisetaChilena.Gorra_31_Min", 0.1},
        {"CamisetaChilena.Apron_Juan_Valdez", 0.1},
        {"CamisetaChilena.Suit_Superman", 0.01},
		{"CamisetaChilena.Mascara_Casa_Papel", 0.2},
        {"CamisetaChilena.Mascara_Tulio", 0.3},
		{"CamisetaChilena.Suit_Casa_Papel", 0.1},
		{"CamisetaChilena.Suit_Rick", 0.1},
		{"CamisetaChilena.RickHead", 0.05},
        {"CamisetaChilena.Mascara_Marshmello", 0.2},
        {"CamisetaChilena.Mascara_Vendeta", 0.2},
        {"CamisetaChilena.Mascara_SquidGame", 0.2},
        {"CamisetaChilena.Suit_SquidGame", 0.1},
        {"CamisetaChilena.Suit_Shaco", 0.05},
        {"CamisetaChilena.Suit_Derpy", 0.05},
		{"CamisetaChilena.Suit_Grizzbolt", 0.05},
        {"CamisetaChilena.DerpyHead", 0.05},
		{"CamisetaChilena.GrizzboltHead", 0.05},
    },
	
    Gifts = {
        {"CamisetaChilena.Camiseta_Bodoqe", 0.6},
        {"CamisetaChilena.Camiseta_Pulentos", 0.6},
        {"CamisetaChilena.Camiseta_Hellfire", 0.4},
        {"CamisetaChilena.Camiseta_Sanchez", 0.5},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.3},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.3},
        {"CamisetaChilena.Camiseta_Minecraft", 0.4},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Bufanda_Mikasa", 0.5},
        {"CamisetaChilena.Camiseta_Twice", 0.4},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.4},
        {"CamisetaChilena.Gorra_BZRP", 0.3},
        {"CamisetaChilena.Suit_Superman", 0.1},
        {"CamisetaChilena.Suit_Goku", 0.1},
        {"CamisetaChilena.Suit_Kill_Bill", 0.1},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
		{"CamisetaChilena.Mascara_Casa_Papel", 0.2},
        {"CamisetaChilena.Mascara_Tulio", 0.3},
		{"CamisetaChilena.Suit_Casa_Papel", 0.1},
        {"CamisetaChilena.Mascara_Marshmello", 0.2},
        {"CamisetaChilena.Mascara_Vendeta", 0.2},
        {"CamisetaChilena.Mascara_SquidGame", 0.2},
        {"CamisetaChilena.Suit_SquidGame", 0.1},
        {"CamisetaChilena.Suit_Shaco", 0.05},
        {"CamisetaChilena.Suit_Derpy", 0.05},
		{"CamisetaChilena.Suit_Grizzbolt", 0.05},
        {"CamisetaChilena.DerpyHead", 0.05},
		{"CamisetaChilena.GrizzboltHead", 0.05},
		{"CamisetaChilena.Suit_Rick", 0.1},
		{"CamisetaChilena.RickHead", 0.05},
    },
	
    ClothingStoresPants = {
        {"CamisetaChilena.Short_Chileno", 1.2},
        {"CamisetaChilena.Short_Chileno_Girl", 1.2},
        {"CamisetaChilena.Dolphin_Shorts_31_Min", 0.8},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.8},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.6},
        {"CamisetaChilena.Pants_Momo_Twice", 0.5},
        {"CamisetaChilena.Pants_Akatsuki", 0.4},
        {"CamisetaChilena.Pants_Disney", 0.6},
        {"CamisetaChilena.Pants_Ponmi", 0.4},
        {"CamisetaChilena.PantsWithShoulderStraps_Gengar", 0.3},
        {"CamisetaChilena.PantsWithShoulderStraps_MB", 0.3},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.2},
		{"CamisetaChilena.Camiseta_Daddy_Yankee_2", 0.04},
        {"CamisetaChilena.Pants_Hisoka", 0.2},
    },
	
    ClothingStoresUnderwearWoman = {
        {"CamisetaChilena.Bikini_Top_31_Min", 0.7},
        {"CamisetaChilena.Bikini_Top_Vaquer", 0.6},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.6},
        {"CamisetaChilena.Bikini_Top_Twice", 0.5},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.5},
        {"CamisetaChilena.Bikini_Top_Dewey", 0.4},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.3},
        {"CamisetaChilena.Bikini_Gengar", 0.4},
        {"CamisetaChilena.Bikini_Dulce_Princesa", 0.4},
        {"CamisetaChilena.Bikini_Akatsuki", 0.2},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.05},
		{"CamisetaChilena.Pantis_Kpop", 0.3},
		{"CamisetaChilena.Short_Kpop", 0.1},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },

    ClothingStoresJumpers = {
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.6},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.6},
        {"CamisetaChilena.Hoodie_Ponmi", 0.5},
        {"CamisetaChilena.Camiseta_Hellfire", 0.3},
        {"CamisetaChilena.Camiseta_DBZ", 0.3},
        {"CamisetaChilena.Chaqueta_Cyberpunk", 0.05},
    },

    ClothingStoresOvershirts = {
        {"CamisetaChilena.Jersey_Curry", 0.6},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.5},
        {"CamisetaChilena.Jersey_Sakuragi", 0.4},
        {"CamisetaChilena.Camiseta_Vidal", 0.4},
        {"CamisetaChilena.Camiseta_Sanchez", 0.4},
        {"CamisetaChilena.Camiseta_Valdivia", 0.3},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.3},
        {"CamisetaChilena.Jersey_Xokas", 0.05},
		{"CamisetaChilena.Camiseta_Daddy_Yankee_2", 0.4},
    },

    ClothingStoresJackets = {
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.5},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.5},
        {"CamisetaChilena.Hoodie_Hisoka", 0.4},
        {"CamisetaChilena.Hoodie_Ponmi", 0.4},
        {"CamisetaChilena.Camiseta_Bravo", 0.3},
        {"CamisetaChilena.Camiseta_Bravo_2", 0.1},
        {"CamisetaChilena.Camiseta_Endler", 0.2},
		{"CamisetaChilena.Suit_Rick", 0.1},
		{"CamisetaChilena.RickHead", 0.05},
    },

    ClothingStoresDress = {
        {"CamisetaChilena.Uniforme_Verde", 0.5},
        {"CamisetaChilena.Uniforme_Verde_Largo", 0.4},
        {"CamisetaChilena.Chaleco_Verde_Mujer", 0.4},
        {"CamisetaChilena.Falda_Verde_Corta", 0.5},
        {"CamisetaChilena.Falda_Verde_Larga", 0.4},
        {"CamisetaChilena.Humita_Mujer_Verde", 0.4},
        {"CamisetaChilena.Gakuran_MuyNegro", 0.3},
        {"CamisetaChilena.Gakuran_MuyNegroAbierto", 0.3},
        {"CamisetaChilena.Falda_Cuadrille", 0.4},
        {"CamisetaChilena.Humita_Mujer_Negra", 0.5},
        {"CamisetaChilena.PantsWithShoulderStraps_Gengar", 0.3},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.2},
        {"CamisetaChilena.Bikini_Gengar", 0.3},
        {"CamisetaChilena.Bikini_Dulce_Princesa", 0.3},
        {"CamisetaChilena.Camiseta_Momo_Twice", 0.3},
		{"CamisetaChilena.Camiseta_Momo", 0.5},
        {"CamisetaChilena.Camiseta_Nayeon", 0.5},
        {"CamisetaChilena.Camiseta_Sana", 0.5},
        {"CamisetaChilena.Camiseta_Kpop", 0.5},
        {"CamisetaChilena.Hoodie_Kpop", 0.5},
        {"CamisetaChilena.Falda_Kpop", 0.3},
        {"CamisetaChilena.Pantis_Kpop", 0.3},
        {"CamisetaChilena.Short_Kpop", 0.3},
        {"CamisetaChilena.Camiseta_HarleyQuin", 0.4},
    },

    ClothingStoresShoes = {
        {"CamisetaChilena.Zapatos_Blancos", 0.8},
        {"CamisetaChilena.Zapatos_Rosados", 0.8},
    },
	
    ClothingStoresBoots = {
        {"CamisetaChilena.Pants_Momo_Twice", 0.2},
        {"CamisetaChilena.Pants_Akatsuki", 0.2},
        {"CamisetaChilena.Pants_Disney", 0.2},
    },

    ClothingStoresSocks = {
        {"CamisetaChilena.Bikini_Top_31_Min", 0.5},
        {"CamisetaChilena.Bikini_Top_Vaquer", 0.4},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.05},
    },

    ClothingStoresHeadwear = {
        {"CamisetaChilena.Gorra_31_Min", 0.8},
        {"CamisetaChilena.Gorra_31_Min_Atras", 0.4},
        {"CamisetaChilena.Gorra_BZRP", 0.8},
        {"CamisetaChilena.Gorra_Duki", 0.8},
        {"CamisetaChilena.Gorra_Momo", 0.7},
        {"CamisetaChilena.Gorra_Twice", 0.7},
        {"CamisetaChilena.Respirador_Viper", 0.05},
		{"CamisetaChilena.Gorra_Colo", 0.4},
        {"CamisetaChilena.Gorra_Chile", 0.4},
    },
	BackstageClothingRack = {
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 1.0},
        {"CamisetaChilena.Camiseta_Momo_Twice", 1.0},
        {"CamisetaChilena.Camiseta_Twice", 1.0},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.8},
        {"CamisetaChilena.Camiseta_Duki", 0.8},
        {"CamisetaChilena.Camiseta_Arcangel", 0.7},
        {"CamisetaChilena.Camiseta_Alexa", 0.6},
        {"CamisetaChilena.Bikini_Top_Twice", 0.6},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.6},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.5},
        {"CamisetaChilena.Pants_Momo_Twice", 0.5},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.4},
        {"CamisetaChilena.Gorra_Duki", 0.4},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.1},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },

    BackstageLockers = {
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.8},
        {"CamisetaChilena.Camiseta_Gengar", 0.6},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.5},
        {"CamisetaChilena.Bikini_Gengar", 0.4},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.4},
        {"CamisetaChilena.Hoodie_Ponmi", 0.4},
        {"CamisetaChilena.PantsWithShoulderStraps_Gengar", 0.3},
        {"CamisetaChilena.Bikini_Top_Dewey", 0.3},
    },

    BackstageDresser = {
        {"CamisetaChilena.Bikini_Top_Twice", 0.7},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.7},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.6},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
        {"CamisetaChilena.Camiseta_Arcangel", 0.5},
        {"CamisetaChilena.Camiseta_Duki", 0.5},
        {"CamisetaChilena.Camiseta_Bad_Bunny", 0.5},
        {"CamisetaChilena.Gorra_Momo", 0.4},
        {"CamisetaChilena.Gorra_Twice", 0.4},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.3},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.05},
		{"CamisetaChilena.Suit_Rick", 0.1},
		{"CamisetaChilena.RickHead", 0.05},
    },

    UniversityWardrobe = {
        {"CamisetaChilena.Camiseta_Twice", 0.7},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.6},
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.4},
        {"CamisetaChilena.Camiseta_Duki", 0.5},
        {"CamisetaChilena.Gorra_BZRP", 0.4},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.6},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.6},
        {"CamisetaChilena.Camiseta_Hellfire", 0.5},
        {"CamisetaChilena.Camiseta_Palworld", 0.4},
    },
	
    CrateTailoring = {       
        {"CamisetaChilena.Bikini_Top_Vaquer", 0.4},
        {"CamisetaChilena.Pants_Momo_Twice", 0.3},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.2},
        {"CamisetaChilena.Pantalones_Cuadrille", 0.4},
    },

	BedroomSidetableChild = {
        {"CamisetaChilena.Camiseta_Bodoqe", 0.6},
        {"CamisetaChilena.Camiseta_Pulentos", 0.6},
        {"CamisetaChilena.Camiseta_Mentita", 0.5},
        {"CamisetaChilena.Camiseta_Hunson", 0.4},
        {"CamisetaChilena.Camiseta_AT", 0.4},
        {"CamisetaChilena.Camiseta_AT_2", 0.4},
        {"CamisetaChilena.Dolphin_Short_31_Min", 0.5},
        {"CamisetaChilena.Gorra_31_Min", 0.4},
        {"CamisetaChilena.Camiseta_Minecraft", 0.5},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Mascara_Tulio", 0.1},		
    },

    WardrobeChild = {
        {"CamisetaChilena.Camiseta_Bodoqe", 0.6},
        {"CamisetaChilena.Camiseta_Pulentos", 0.6},
        {"CamisetaChilena.Camiseta_Mentita", 0.5},
        {"CamisetaChilena.Camiseta_Hunson", 0.5},
        {"CamisetaChilena.Hoodie_Ponmi", 0.4},
        {"CamisetaChilena.Dolphin_Shorts_31_Min", 0.5},
        {"CamisetaChilena.Dolphin_Shorts_Dulce_Princesa", 0.5},
        {"CamisetaChilena.Bikini_Top_31_Min", 0.3},
        {"CamisetaChilena.Pants_Disney", 0.4},
        {"CamisetaChilena.Suit_Los_Increibles", 0.1},
    },

    BoxingLockers = {
        {"CamisetaChilena.Dolphin_Shorts_WWE", 1.0}, 
        {"CamisetaChilena.Camiseta_John_Cena", 0.6},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.5},
        {"CamisetaChilena.Jersey_Curry", 0.5},
        {"CamisetaChilena.Camiseta_Vidal", 0.4},
        {"CamisetaChilena.Short_Chileno", 0.6},
    },
	
	FitnessTrainer = {
        {"CamisetaChilena.Jersey_Curry", 0.6},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.6},
        {"CamisetaChilena.Camiseta_Bravo", 0.4},
        {"CamisetaChilena.Camiseta_Bravo_2", 0.2},
        {"CamisetaChilena.Short_Chileno", 0.5},
        {"CamisetaChilena.Gorra_BZRP", 0.3},
        {"CamisetaChilena.Jersey_Xokas", 0.1},
    },
	
    ClothingRack = {
        {"CamisetaChilena.Camiseta_Vidal", 0.4},
        {"CamisetaChilena.Camiseta_Sanchez", 0.4},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.4},
        {"CamisetaChilena.Camiseta_Pulentos", 0.4},
        {"CamisetaChilena.Camiseta_Vaquer", 0.3},
        {"CamisetaChilena.Camiseta_Mentita", 0.3},
        {"CamisetaChilena.Short_Chileno", 0.4},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.2},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.2},
        {"CamisetaChilena.Hoodie_Ponmi", 0.2},
    },
	
	WardrobeClassy = {
        {"CamisetaChilena.Bikini_Top_Blackpink", 0.5},
        {"CamisetaChilena.Bikini_Top_Twice", 0.5},
        {"CamisetaChilena.Camiseta_Momo_Twice_Bulls", 0.4},
        {"CamisetaChilena.Camiseta_Momo_Twice", 0.4},
        {"CamisetaChilena.Jersey_Curry", 0.4},
        {"CamisetaChilena.Jersey_Michael_Jordan", 0.4},
        {"CamisetaChilena.Dolphin_Shorts_WWE", 0.3},
        {"CamisetaChilena.PantsWithShoulderStraps_Gengar", 0.2},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.2},
        {"CamisetaChilena.Bikini_Top_Zombhub", 0.05},
    },

    WardrobeGeneric = {
        {"CamisetaChilena.Camiseta_Vidal", 0.5},
        {"CamisetaChilena.Camiseta_Sanchez", 0.5},
        {"CamisetaChilena.Camiseta_Roja", 0.5},
        {"CamisetaChilena.Short_Chileno", 0.4},
        {"CamisetaChilena.Short_Chileno_Girl", 0.4},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.3},
        {"CamisetaChilena.Camiseta_Pulentos", 0.3},
        {"CamisetaChilena.Camiseta_Vaquer", 0.3},
        {"CamisetaChilena.Camiseta_Mentita", 0.3},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.2},
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.2},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Gorra_BZRP", 0.2},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Bufanda_Mikasa", 0.1},
        {"CamisetaChilena.Pijama_AT", 0.2},
        {"CamisetaChilena.Suit_Los_Increibles", 0.05},
    },
	
	DresserGeneric = {
        {"CamisetaChilena.Bikini_Top_31_Min", 0.4},
        {"CamisetaChilena.Bikini_Top_Vaquer", 0.4},
        {"CamisetaChilena.Bikini_Top_Alexa", 0.3},
        {"CamisetaChilena.Dolphin_Short_31_Min", 0.5},
        {"CamisetaChilena.Dolphin_Shorts_Gengar", 0.4},
        {"CamisetaChilena.Short_Chileno", 0.3},
        {"CamisetaChilena.Short_Chileno_Girl", 0.3},
        {"CamisetaChilena.Camiseta_Zombhub", 0.05},
        {"CamisetaChilena.Fishnet_Leotard_Momo", 0.1},
		{"CamisetaChilena.Falda_Azul_Larga", 0.2},
        {"CamisetaChilena.Camiseta_Chapulin", 0.1},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.1},
		{"CamisetaChilena.Camiseta_Hardy", 0.4},
    },
	
	CampingStoreClothes = {
        {"CamisetaChilena.Bufanda_Tanjiro", 0.6},
        {"CamisetaChilena.Bufanda_Mikasa", 0.6},
        {"CamisetaChilena.Bufanda_Inosuke", 0.6},
        {"CamisetaChilena.Bufanda_Nezuko", 0.6},
        {"CamisetaChilena.Bufanda_Tomioka", 0.6},
        {"CamisetaChilena.Bufanda_Zenitsu", 0.6},
        {"CamisetaChilena.Bufanda_BobMarley", 0.4},
        {"CamisetaChilena.Gorra_31_Min", 0.3},
        {"CamisetaChilena.Gorra_BZRP", 0.3},
        {"CamisetaChilena.Camiseta_WR", 0.4},
        {"CamisetaChilena.Falda_Militar", 0.3},
        {"CamisetaChilena.Bikini_Marin", 0.1},
        {"CamisetaChilena.Suit_Viper", 0.02},
        {"CamisetaChilena.Respirador_Viper", 0.02},
    },
	
	ArmyStorageElectronics = {
        {"CamisetaChilena.Chaqueta_Cyberpunk", 0.15},
        {"CamisetaChilena.Suit_Viper", 0.1},
        {"CamisetaChilena.Respirador_Viper", 0.15},
    },
	
    CrateClothesRandom = {
        {"CamisetaChilena.Gorra_31_Min", 0.4},
        {"CamisetaChilena.Gorra_BZRP", 0.4},
        {"CamisetaChilena.Bufanda_BobMarley", 0.3},
        {"CamisetaChilena.Bufanda_Tanjiro", 0.3},
        {"CamisetaChilena.Bufanda_Mikasa", 0.3},
        {"CamisetaChilena.Apron_Starbucks", 0.4},
        {"CamisetaChilena.Apron_Juan_Valdez", 0.4},
        {"CamisetaChilena.Camiseta_WR", 0.5},
        {"CamisetaChilena.Camiseta_Chicago_Bulls", 0.4},
        {"CamisetaChilena.Camiseta_Batman", 0.4},
        {"CamisetaChilena.Camiseta_DBZ", 0.3},
        {"CamisetaChilena.Camiseta_Minecraft", 0.4},
        {"CamisetaChilena.Pants_Akatsuki", 0.2},
        {"CamisetaChilena.Pants_Disney", 0.2},
        {"CamisetaChilena.Suit_Saitama", 0.05},
        {"CamisetaChilena.Suit_Goku", 0.05},
        {"CamisetaChilena.Suit_Superman", 0.05},
		{"CamisetaChilena.Camiseta_Chapulin", 0.3},
        {"CamisetaChilena.Camiseta_Barbilla_Roja", 0.3},
        {"CamisetaChilena.Camiseta_SquidGame", 0.2},
        {"CamisetaChilena.Camiseta_Daddy_Yankee", 0.4},
        {"CamisetaChilena.Camiseta_Tego_Calderon", 0.4},
    },
	
	LivingRoomWardrobe = {
        {"CamisetaChilena.Hoodie_DragonBallKaiser", 0.4},
        {"CamisetaChilena.Hoodie_ChainsawMan", 0.4},
        {"CamisetaChilena.Hoodie_Ponmi", 0.3},
        {"CamisetaChilena.Camiseta_Vidal", 0.5},
        {"CamisetaChilena.Camiseta_Sanchez", 0.5},
        {"CamisetaChilena.Camiseta_Bodoqe", 0.4},
        {"CamisetaChilena.Camiseta_Pulentos", 0.4},
        {"CamisetaChilena.Gorra_31_Min", 0.2},
        {"CamisetaChilena.Gorra_BZRP", 0.2},
        {"CamisetaChilena.Bufanda_Harry_Potter", 0.2},
		{"CamisetaChilena.Bufanda_Hufflepuff", 0.2},
		{"CamisetaChilena.Bufanda_RavenClaw", 0.2},
		{"CamisetaChilena.Bufanda_Slytherin", 0.2},
        {"CamisetaChilena.Bufanda_Tanjiro", 0.1},
        {"CamisetaChilena.Bufanda_Mikasa", 0.1},
        {"CamisetaChilena.Bufanda_Zenitsu", 0.1},
        {"CamisetaChilena.Camiseta_Chicago_Bulls", 0.3},
        {"CamisetaChilena.Camiseta_DBZ", 0.3},
        {"CamisetaChilena.Camiseta_Minecraft", 0.3},
        {"CamisetaChilena.Camiseta_WR", 0.3},
        {"CamisetaChilena.Pants_Akatsuki", 0.2},
        {"CamisetaChilena.Pants_Disney", 0.2},
        {"CamisetaChilena.Pijama_AT", 0.15},
        {"CamisetaChilena.Suit_Bruce_Lee", 0.05},
        {"CamisetaChilena.Suit_Kill_Bill", 0.05},
    },
	
	MagazineRackMixed = {
        {"CamisetaChilena.Revista_CDF_Vol1", 0.1},
        {"CamisetaChilena.Revista_Kpop_Vol1", 0.1},
        {"CamisetaChilena.Revista_Artequin_Vol1", 0.1},
        {"CamisetaChilena.Revista_Gorras_Vol1", 0.1},
        {"CamisetaChilena.Revista_Bufandas_Vol1", 0.1},
		{"CamisetaChilena.Revista_ZombHub_Vol3", 0.05},
    }
	
}

-- =========================================================
-- Función para aplicar la distribución
-- =========================================================
local function ApplyCamisetaLoot()
    print("[CamisetaChilena] Iniciando inyeccion de loot mundial...")
    
    local mult = CC_WorldLootMult()
    if mult <= 0 then 
        print("[CamisetaChilena] Mod desactivado en Sandbox.")
        return 
    end

    -- Insertar items en contenedores procedurales
    for location, locationItems in pairs(CamisetaChilena_Loot) do
        if ProceduralDistributions.list[location] then
            for _, item in ipairs(locationItems) do
                table.insert(ProceduralDistributions.list[location].items, item[1])
                table.insert(ProceduralDistributions.list[location].items, item[2] * mult)
            end
        else
            -- Esto te avisará si una zona no existe (útil para depurar)
            print("[CamisetaChilena] WARNING: Locacion no encontrada en el mapa: " .. location)
        end
    end

    -- Insertar outfits en maniquíes
    if ProceduralDistributions.list["ClothingDisplaysMannequins"] then
        local outfitsManiqui = {
            {"LaRoja", 1.0},
            {"Duki_Trap_Outfit", 1.0},
            {"MomoTwice", 3.0},
			{"GengarGastly", 0.5},
            {"SquidGamePlayer", 0.8},
            {"SquidGameGuard", 0.5},
            {"Kpop_Idol", 0.3},
            {"FireForceMaki", 0.6},
            {"TamakiKotatsu", 0.6},
            {"Invincible_Suit", 0.5},
            {"SchoolBoyGreen_Full", 0.5},
       }
        
        for _, outfit in ipairs(outfitsManiqui) do
            table.insert(ProceduralDistributions.list["ClothingDisplaysMannequins"].items, outfit[1])
            table.insert(ProceduralDistributions.list["ClothingDisplaysMannequins"].items, outfit[2] * mult)
        end
    end
    
    print("[CamisetaChilena] Loot mundial aplicado con éxito. Multiplicador: " .. mult)
end

Events.OnPostDistributionMerge.Add(ApplyCamisetaLoot)