m_milzones = {}
--Fort Redstone
if getActivatedMods():contains("FORTREDSTONE") then
    table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 5632, y = 11795, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 5632, y = 11798, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 5462, y = 12046, z = 0, width = 5, height = 10, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 5536, y = 11291, z = 0, width = 6, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 5538, y = 11713, z = 0, width = 6, height = 4, properties = { Direction = "W" } })
end
--Louisville Quarantine Zone
if getActivatedMods():contains("Louisville_Quarantine_Zone") then
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 13442, y = 4071, z = 0, width = 4, height = 6, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 13631, y = 4072, z = 0, width = 3, height = 5, properties = { Direction = "S" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 13745, y = 4084, z = 0, width = 5, height = 3, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_container", type = "ParkingStall", x = 13607, y = 4105, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 13618, y = 4124, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 13496, y = 4084, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 13967, y = 4070, z = 0, width = 3, height = 5, properties = { Direction = "S" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 13690, y = 4085, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 14007, y = 4065, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 13997, y = 4068, z = 0, width = 5, height = 3, properties = { Direction = "E" } })
end
--Raven Creek
if getActivatedMods():contains("RavenCreek") then
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 3007, y = 11257, z = 0, width = 4, height = 12, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_trailer_light", type = "ParkingStall", x = 3007, y = 11291, z = 0, width = 4, height = 12, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_container", type = "ParkingStall", x = 3007, y = 11331, z = 0, width = 4, height = 12, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 4713, y = 11206, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer_heavy", type = "ParkingStall", x = 3880, y = 12835, z = 0, width = 3, height = 4, properties = { Direction = "N", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_container", type = "ParkingStall", x = 3886, y = 12781, z = 0, width = 3, height = 15, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_container", type = "ParkingStall", x = 3772, y = 12867, z = 0, width = 3, height = 4, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 3950, y = 13366, z = 0, width = 4, height = 3, properties = { Direction = "W" } })
end
--Fort Knox
if getActivatedMods():contains("Fort Knox") then
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 10994, y = 13628, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11006, y = 13668, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 10967, y = 13662, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11000, y = 13646, z = 0, width = 5, height = 3, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 10479, y = 13852, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 10491, y = 13823, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 10491, y = 13808, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 10468, y = 13805, z = 0, width = 3, height = 4, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11161, y = 14443, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11152, y = 14495, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11152, y = 14499, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11149, y = 14618, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 11267, y = 14560, z = 0, width = 6, height = 5, properties = { Direction = "S" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11201, y = 14682, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11206, y = 14688, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11185, y = 14695, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 11222, y = 14663, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 11232, y = 14683, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11251, y = 14684, z = 0, width = 3, height = 5, properties = { Direction = "S" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11247, y = 14687, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11465, y = 14695, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11282, y = 14660, z = 0, width = 6, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11302, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11311, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11329, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11338, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11356, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11365, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11383, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11392, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11411, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11420, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11438, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11447, y = 14660, z = 0, width = 5, height = 34, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11637, y = 14606, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15195, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15199, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15203, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15207, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15211, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15215, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15219, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15223, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15227, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15231, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15235, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15239, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15243, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15247, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15251, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15255, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15259, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15263, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15267, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_trailer", type = "ParkingStall", x = 11549, y = 15271, z = 0, width = 5, height = 4, properties = { Direction = "E", FaceDirection = true } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11549, y = 15275, z = 0, width = 5, height = 4, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_light", type = "ParkingStall", x = 11097, y = 14650, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 11089, y = 14627, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11042, y = 14623, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 11023, y = 14696, z = 0, width = 3, height = 5, properties = { Direction = "S" } })
	table.insert(m_milzones, { name = "military_burnt", type = "ParkingStall", x = 10987, y = 14694, z = 0, width = 3, height = 5 })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 10998, y = 14640, z = 0, width = 5, height = 3, properties = { Direction = "W" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11000, y = 14687, z = 0, width = 5, height = 3, properties = { Direction = "E" } })
	table.insert(m_milzones, { name = "military_vehicle", type = "ParkingStall", x = 11069, y = 14677, z = 0, width = 3, height = 5, properties = { Direction = "N" } })
	table.insert(m_milzones, { name = "military_vehicle_heavy", type = "ParkingStall", x = 10997, y = 14619, z = 0, width = 5, height = 3, properties = { Direction = "E" } })
end