v_milzones = {
--Secret Base
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5830, y = 12477, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5803, y = 12473, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5814, y = 12476, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5838, y = 12487, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5830, y = 12495, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5859, y = 12492, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5871, y = 12489, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5525, y = 12485, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 5598, y = 12447, z = 0, width = 5, height = 25, properties = { Direction = "W" } },
  { name = "military_vehicle", type = "ParkingStall", x = 5587, y = 12447, z = 0, width = 5, height = 25, properties = { Direction = "E" } },
  { name = "military_container", type = "ParkingStall", x = 5569, y = 12441, z = 0, width = 5, height = 14, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 5583, y = 12435, z = 0, width = 6, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_trailer", type = "ParkingStall", x = 5594, y = 12435, z = 0, width = 12, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5538, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5550, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5557, y = 12563, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5589, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5599, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5615, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5621, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5629, y = 12561, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5538, y = 12435, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirectmion = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5554, y = 12436, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 5563, y = 12436, z = 0, width = 5, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 5782, y = 12490, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
--Lousiville Checkpoint
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 12506, y = 4339, z = 0, width = 3, height = 5, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12515, y = 4350, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12505, y = 4203, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12509, y = 4485, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12514, y = 4478, z = 0, width = 3, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 12540, y = 4316, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12554, y = 4319, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 12465, y = 4225, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12545, y = 4238, z = 0, width = 3, height = 4, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12466, y = 4263, z = 0, width = 4, height = 6, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 12534, y = 4203, z = 0, width = 3, height = 5, properties = { Direction = "S" } },
  { name = "military_container", type = "ParkingStall", x = 12524, y = 4244, z = 0, width = 4, height = 10, properties = { Direction = "S" } },
  { name = "military_vehicle", type = "ParkingStall", x = 12524, y = 4355, z = 0, width = 21, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 12726, y = 3960, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 12694, y = 3963, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_burnt", type = "ParkingStall", x = 12716, y = 3995, z = 0, width = 6, height = 4 },
  { name = "military_burnt", type = "ParkingStall", x = 12763, y = 3989, z = 0, width = 4, height = 6 },
  { name = "military_burnt", type = "ParkingStall", x = 12597, y = 4154, z = 0, width = 4, height = 6 },
--Louisville
  { name = "military_vehicle_light", type = "ParkingStall", x = 12506, y = 3482, z = 0, width = 6, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12514, y = 3482, z = 0, width = 6, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12482, y = 3442, z = 0, width = 3, height = 6, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12482, y = 3452, z = 0, width = 3, height = 6, properties = { Direction = "S", FaceDirection = true } },
--Burnt Town near Louisville
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 13442, y = 4071, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 14538, y = 4019, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 13610, y = 4080, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
--Muldraugh
  { name = "military_vehicle_light", type = "ParkingStall", x = 10585, y = 11230, z = 0, width = 6, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 10593, y = 11230, z = 0, width = 6, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10631, y = 11196, z = 0, width = 3, height = 8, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10631, y = 11204, z = 0, width = 3, height = 8, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10546, y = 11196, z = 0, width = 3, height = 8, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10546, y = 11204, z = 0, width = 3, height = 8, properties = { Direction = "S", FaceDirection = true } },
--March Ridge
  { name = "military_vehicle", type = "ParkingStall", x = 10353, y = 12424, z = 0, width = 5, height = 17, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 10353, y = 12404, z = 0, width = 3, height = 5, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 10371, y = 12403, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10373, y = 12381, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 10362, y = 12386, z = 0, width = 4, height = 6, properties = { Direction = "S", FaceDirection = true } },
  { name = "military_container", type = "ParkingStall", x = 10105, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 10092, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 10077, y = 12601, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
--Doe Valley
  { name = "military_vehicle", type = "ParkingStall", x = 8124, y = 10260, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle_", type = "ParkingStall", x = 8134, y = 10260, z = 0, width = 6, height = 4, properties = { Direction = "W" } },
  { name = "military_vehicle", type = "ParkingStall", x = 8105, y = 10232, z = 0, width = 4, height = 10, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 8105, y = 10245, z = 0, width = 4, height = 10, properties = { Direction = "N" } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 8162, y = 10252, z = 0, width = 6, height = 4, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle", type = "ParkingStall", x = 8131, y = 10226, z = 0, width = 6, height = 4, properties = { Direction = "E" } },
  { name = "military_vehicle", type = "ParkingStall", x = 8141, y = 10226, z = 0, width = 6, height = 4, properties = { Direction = "E" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 6784, y = 9908, z = 0, width = 6, height = 4, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle", type = "ParkingStall", x = 6788, y = 9979, z = 0, width = 20, height = 5, properties = { Direction = "S" } },
  { name = "military_vehicle", type = "ParkingStall", x = 6788, y = 9990, z = 0, width = 20, height = 5, properties = { Direction = "N" } },
  { name = "military_vehicle", type = "ParkingStall", x = 6795, y = 9916, z = 0, width = 12, height = 4, properties = { Direction = "W" } },
  { name = "military_trailer_light", type = "ParkingStall", x = 7461, y = 7967, z = 0, width = 5, height = 7, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 7462, y = 7950, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_container", type = "ParkingStall", x = 7472, y = 7953, z = 0, width = 4, height = 6, properties = { Direction = "S" } },
--Rosewood
  { name = "military_vehicle", type = "ParkingStall", x = 9110, y = 11833, z = 0, width = 5, height = 15, properties = { Direction = "E" } },
  { name = "military_trailer_heavy", type = "ParkingStall", x = 9115, y = 11795, z = 0, width = 3, height = 6, properties = { Direction = "S", FaceDirection = true } },
--Brandenburg
  { name = "military_vehicle", type = "ParkingStall", x = 3016, y = 6142, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_vehicle", type = "ParkingStall", x = 3016, y = 6150, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "military_vehicle", type = "ParkingStall", x = 3024, y = 6142, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_vehicle", type = "ParkingStall", x = 3024, y = 6150, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 3032, y = 6142, z = 0, width = 5, height = 3, properties = { Direction = "W" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 3032, y = 6150, z = 0, width = 5, height = 3, properties = { Direction = "E" } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 3018, y = 6159, z = 0, width = 4, height = 6, properties = { Direction = "N" } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 3052, y = 6143, z = 0, width = 3, height = 7, properties = { Direction = "N", FaceDirection = true } },
  { name = "military_vehicle_heavy", type = "ParkingStall", x = 3052, y = 6150, z = 0, width = 3, height = 7, properties = { Direction = "S", FaceDirection = true } },
--West Point
  { name = "military_vehicle_light", type = "ParkingStall", x = 12309, y = 6777, z = 0, width = 6, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12317, y = 6777, z = 0, width = 6, height = 3, properties = { Direction = "E", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12309, y = 6698, z = 0, width = 6, height = 3, properties = { Direction = "W", FaceDirection = true } },
  { name = "military_vehicle_light", type = "ParkingStall", x = 12317, y = 6698, z = 0, width = 6, height = 3, properties = { Direction = "E", FaceDirection = true } },
}