Distributions = Distributions or {};
 
local distributionTable = {
	
	Box_FrockinStompersShoeBox = {
		ignoreZombieDensity = true,
		rolls = 1,
		items = {
			"FE_ShoesRE_Sandals", 1,
			"FE_ShoesRE_Sandals_T", 1,
			"FE_ShoesRE_Crocs", 1,
			"FE_ShoesRE_CrocsSlipper", 1,
			"FE_ShoesRE_Slippers", 1,
			"FE_Shoe_Trainers_LowTop", 1,
			"FE_Shoe_TrainersBlack_LowTop", 1,
			"FE_Shoe_TrainersWhite_LowTop", 1,
			"FE_Shoe_Trainers_HighTop", 1,
			"FE_Shoe_TrainersBlack_HighTop", 1,
			"FE_Shoe_TrainersWhite_HighTop", 1,
			"FE_BootsRE_Combat_AnkleHigher", 1,
			"FE_BootsRE_Combat_AnkleHigherLoose", 1,
			"FE_BootsRE_Combat_AnkleHigh", 1,
			"FE_ShoesRE_Combat", 1,
			"FE_BootsRE_LeatherCasual_AnkleHigher", 1,
			"FE_BootsRE_LeatherCasual_AnkleHigh", 1,
			"FE_ShoesRE_LeatherCasual", 1,
			"FE_ShoesRE_Casual", 1,
			"FE_BootsRE_Gaiters_KneeLow", 1,
			"FE_BootsRE_Gaiters_AnkleHigh", 1,
			"FE_BootsRE_LegWarmers_KneeLow", 1,
			"FE_BootsRE_LegWarmers_AnkleHigh", 1,
			"FE_BootsRE_LegWarmers_Ankle", 1,
			"FF_Boots_Cowboy_Plain", 1,
			"FF_Boots_Leather", 1,
			"FF_Boots_Leather_Short", 1,
			"FF_Boots_Cowboy", 1,
			"FF_Shoe_Boots_Ankle", 1,
			"FF_Shoe_Boots_Ankle_Steel", 1,
			"FF_Shoe_Boots_Ankle_Platform", 1,
			"FF_Boots_Common", 1,
			"FF_Boots_UGG", 1,
			"FF_Boots_UGG_DwarfHeel", 1,
			"FF_Boots_UGG_Heel", 1,
			"FF_BootsRE_Leather_DwarfHeel", 1,
			"FF_BootsRE_Leather_Heel", 1,
			"FF_Boots_Military_Ankle", 1,
			"FF_Shoe_Common", 1,
			"FF_Shoe_Trainers", 1,
			"FF_Shoe_TrainersBlack", 1,
			"FF_Shoe_TrainersWhite", 1,
		},
		
	},
	
	Box_FrockinStompersShoeBoxLuxury = {
		ignoreZombieDensity = true,
		rolls = 1,
		items = {
			"FE_HeelsRE_SnkSkn_AnkleHigh", 1,
			"FE_HeelsRE_Leather_AnkleHigh", 1,
			"FE_HeelsRE_Animal_AnkleHigh", 1,
			"FE_BootsRE_WideCalf_AnkleHigher", 1,
			"FE_BootsRE_WideCalf_AnkleHigh", 1,
			"FE_BootsRE_WideCalf_Ankle", 1,
			"FE_BootsRE_Stiletto_AnkleHigh", 1,
			"FE_BootsRE_Stiletto_Ankle", 1,
			"FE_HeelsRE_Stiletto_Premium_AnkleHigh", 1,
			"FE_HeelsRE_Stiletto_Premium_Ankle", 1,
			"FE_BootsRE_MEGAGoth_AnkleHigh", 1,
			"FE_BootsRE_MEGAGoth_Ankle", 1,
			"FE_BootsRE_MEGACool_AnkleHigh", 1,
			"FE_BootsRE_MEGACool_Ankle", 1,
			"FE_HeelsRE_Converse_AnkleHigh", 1,
			"FE_BootsRE_Chelsea_AnkleHigher", 1,
			"FE_BootsRE_Chelsea_AnkleHigh", 1,
			"FE_ShoesRE_Chelsea", 1,
			"FF_Shoe_Women", 1,
			"FF_Shoe_Women_Platform", 1,
			"FF_Shoe_Women_2", 1,
			"FF_Shoe_Moccasin", 1,
			"FF_Boots_Platform_Ankle", 1,
			"FF_Boots_Platform_AnkleLow", 1,
			"FF_Boots_Pointy_AnkleLow", 1,
			"FF_Boots_Pointy_Ankle", 1,
			"FE_ShoesRE_LegWarmers_MJ_KneeLow", 1,
			"FE_ShoesRE_LegWarmers_MJ_AnkleHigh", 1,
			"FE_ShoesRE_LegWarmers_MJ_Ankle", 1,
		},
		
	},
	
	Box_FrockinStompersShoeBoxLong = {
		ignoreZombieDensity = true,
		rolls = 1,
		items = {
			"FE_HeelsRE_Leather_ThighHigh", 1,
			"FE_BootsRE_WideCalf_ThighHigher", 1,
			"FE_BootsRE_WideCalf_ThighHigh", 1,
			"FE_BootsRE_Gaiters_ThighHigh", 1,
			"FE_Boots_Converse_Thighhigh", 1,
			"FF_Boots_UGG_Thighhigh", 1,
			"FF_Boots_UGG_ThighhighHeel", 1,
			"FF_Boots_Military_Thighhigher", 1,
			"FF_Boots_Military_Thighhigh", 1,
			"FF_BootsRE_Leather_ThighhighHeel", 1,
			"FE_HeelsRE_Leather_KneeHigher", 1,
			"FE_HeelsRE_Leather_KneeHigh", 1,
			"FE_BootsRE_WideCalf_KneeHigher", 1,
			"FE_BootsRE_WideCalf_KneeHigh", 1,
			"FE_BootsRE_Gaiters_KneeHigh", 1,
			"FE_BootsRE_LegWarmers_KneeHigh", 1,
			"FF_BootsRE_Leather_KneehighHeel", 1,
			"FF_Boots_Military_Kneehigher", 1,
			"FF_Boots_Military_Kneehigh", 1,
			"FE_HeelsRE_Converse_ThighHigh", 1,
			"FE_Boots_Converse_Kneehigher", 1,
			"FE_Boots_Converse_Kneehigh", 1,
			"FF_Boots_HighHeels", 1,
			"FF_Boots_Pointy_Kneehigh", 1,
		},
		
	},
	
	Box_FrockinStompersShoeBoxLongLuxury = {
		ignoreZombieDensity = true,
		rolls = 1,
		items = {
			"FE_BootsRE_Stiletto_ThighHigher", 1,
			"FE_BootsRE_Stiletto_ThighHigh", 1,
			"FE_HeelsRE_Stiletto_Premium_ThighHigher", 1,
			"FE_HeelsRE_Stiletto_Premium_ThighHigh", 1,
			"FE_BootsRE_MEGAGoth_ThighHigher", 1,
			"FE_BootsRE_MEGAGoth_ThighHigh", 1,
			"FE_BootsRE_LegWarmers_ThighHigh", 1,
			"FE_ShoesRE_LegWarmers_MJ_ThighHigh", 1,
			"FF_Boots_Platform_Thighhigh", 1,
			"FF_Boots_PlatformPunk_Thighhigh", 1,
			"FF_Boots_HF_New", 1,
			"FF_Boots_HF_New_Longest", 1,
			"FF_Boots_HF_New_Longer", 1,
			"FF_Boots_HF_New_Long", 1,
			"FE_HeelsRE_SnkSkn_KneeHigher", 1,
			"FE_HeelsRE_SnkSkn_KneeHigh", 1,
			"FE_HeelsRE_Animal_KneeHigher", 1,
			"FE_HeelsRE_Animal_KneeHigh", 1,
			"FE_BootsRE_Stiletto_KneeHigher", 1,
			"FE_BootsRE_Stiletto_KneeHigh", 1,
			"FE_HeelsRE_Stiletto_Premium_KneeHigher", 1,
			"FE_HeelsRE_Stiletto_Premium_KneeHigh", 1,
			"FE_HeelsRE_Converse_KneeHigher", 1,
			"FE_HeelsRE_Converse_KneeHigh", 1,
			"FE_BootsRE_MEGAGoth_KneeHigher", 1,
			"FE_BootsRE_MEGAGoth_KneeHigh", 1,
			"FE_BootsRE_MEGACool_KneeHigher", 1,
			"FE_BootsRE_MEGACool_KneeHigh", 1,
			"FE_ShoesRE_LegWarmers_MJ_KneeHigh", 1,
			"FF_Boots_UGG_Kneehigh", 1,
			"FF_Boots_UGG_KneehighHeel", 1,
			"FF_Boots_Platform_Kneehigher", 1,
			"FF_Boots_Platform_Kneehigh", 1,
			"FF_Boots_PlatformPunk_Kneehigher", 1,
			"FF_Boots_PlatformPunk_Kneehigh", 1,
		},
		
	},
	
}

table.insert(Distributions, 1, distributionTable);