--Ammo Maker by STIMP_TM

ammoMakerAmmoParts = {

    ["ammomaker.ammomaker_BulletRifleS"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsRifleS",
        recycleRecipe     = "RecycleBulletsRifleS",
        partCat           = "Rifle",
        moldType          = "ammomaker.ammomaker_MoldBulletsRifleS",
        boxType           = "ammomaker.ammomaker_BoxBulletsRifleS",
    },
    ["ammomaker.ammomaker_BulletRifleSAP"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsRifleSAP",
        recycleRecipe     = "RecycleBulletsRifleSAP",
        partCat           = "Rifle",
        moldType          = "ammomaker.ammomaker_MoldBulletsRifleS",
        boxType           = "ammomaker.ammomaker_BoxBulletsRifleSAP",
    },
    ["ammomaker.ammomaker_BulletRifleSHP"] = {
        partClass         = "Projectile",
        partExtraClass    = "HollowPoint",
        recycleRecipe     = "RecycleBulletsRifleSHP",
        partCat           = "Rifle",
        baseType          = "ammomaker.ammomaker_BulletRifleS",
        boxType           = "ammomaker.ammomaker_BoxBulletsRifleSHP",
    },
    ["ammomaker.ammomaker_BulletRifleM"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsRifleM",
        recycleRecipe     = "RecycleBulletsRifleM",
        partCat           = "Rifle",
        moldType          = "ammomaker.ammomaker_MoldBulletsRifleM",
        boxType           = "ammomaker.ammomaker_BoxBulletsRifleM",
    },
    ["ammomaker.ammomaker_BulletRifleL"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsRifleL",
        recycleRecipe     = "RecycleBulletsRifleL",
        partCat           = "Rifle",
        moldType          = "ammomaker.ammomaker_MoldBulletsRifleL",
        boxType           = "ammomaker.ammomaker_BoxBulletsRifleL",
    },
    ["ammomaker.ammomaker_BulletHandgunS"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsHandgunS",
        recycleRecipe     = "RecycleBulletsHandgunS",
        partCat           = "Pistol",
        moldType          = "ammomaker.ammomaker_MoldBulletsHandgunS",
        boxType           = "ammomaker.ammomaker_BoxBulletsHandgunS",
    },
    ["ammomaker.ammomaker_BulletHandgunM"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsHandgunM",
        recycleRecipe     = "RecycleBulletsHandgunM",
        partCat           = "Pistol",
        moldType          = "ammomaker.ammomaker_MoldBulletsHandgunM",
        boxType           = "ammomaker.ammomaker_BoxBulletsHandgunM",
    },
    ["ammomaker.ammomaker_BulletHandgunL"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBulletsHandgunL",
        recycleRecipe     = "RecycleBulletsHandgunL",
        partCat           = "Pistol",
        moldType          = "ammomaker.ammomaker_MoldBulletsHandgunL",
        boxType           = "ammomaker.ammomaker_BoxBulletsHandgunL",
    },
    ["ammomaker.ammomaker_Balls00"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeBalls00",
        recycleRecipe     = "RecycleBalls00",
        partCat           = "Shotgun",
        moldType          = "ammomaker.ammomaker_MoldBalls00",
        boxType           = "ammomaker.ammomaker_BoxBalls00",
    },
    ["ammomaker.ammomaker_Slug12"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeSlugs12",
        recycleRecipe     = "RecycleSlugs12",
        partCat           = "Shotgun",
        moldType          = "ammomaker.ammomaker_MoldSlugs12",
        boxType           = "ammomaker.ammomaker_BoxSlugs12",
    },
    ["ammomaker.ammomaker_Projectile40HE"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeProjectile40HE",
        partCat           = "Grenade",
    },
    ["ammomaker.ammomaker_Projectile40INC"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeProjectile40INC",
        partCat           = "Grenade",
    },
    ["ammomaker.ammomaker_Projectile40MPB"] = {
        partClass         = "Projectile",
        makeRecipe        = "MakeProjectile40MPB",
        partCat           = "Grenade",
    },
    ["ammomaker.ammomaker_CasingBottleneckS"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingBottleneckSOld",
        partFired         = "ammomaker.ammomaker_CasingBottleneckS",
        makeRecipe        = "MakeCasingsBottleneckS",
        recycleRecipe     = "RecycleCasingsBottleneckS",
        partCat           = "Rifle",
        boxType           = "ammomaker.ammomaker_BoxCasingsBottleneckS",
        bagType           = "ammomaker.ammomaker_BagCasingsBottleneckSOld",
    },
    ["ammomaker.ammomaker_CasingBottleneckM"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingBottleneckMOld",
        partFired         = "ammomaker.ammomaker_CasingBottleneckM",
        makeRecipe        = "MakeCasingsBottleneckM",
        recycleRecipe     = "RecycleCasingsBottleneckM",
        partCat           = "Rifle",
        boxType           = "ammomaker.ammomaker_BoxCasingsBottleneckM",
        bagType           = "ammomaker.ammomaker_BagCasingsBottleneckMOld",
    },
    ["ammomaker.ammomaker_CasingBottleneckL"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingBottleneckLOld",
        partFired         = "ammomaker.ammomaker_CasingBottleneckL",
        makeRecipe        = "MakeCasingsBottleneckL",
        recycleRecipe     = "RecycleCasingsBottleneckL",
        partCat           = "Rifle",
        boxType           = "ammomaker.ammomaker_BoxCasingsBottleneckL",
        bagType           = "ammomaker.ammomaker_BagCasingsBottleneckLOld",
    },
    ["ammomaker.ammomaker_CasingBottleneckMRim"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingBottleneckMRimOld",
        partFired         = "ammomaker.ammomaker_CasingBottleneckMRim",
        makeRecipe        = "MakeCasingsBottleneckMRim",
        recycleRecipe     = "RecycleCasingsBottleneckMRim",
        partCat           = "Rifle",
        boxType           = "ammomaker.ammomaker_BoxCasingsBottleneckMRim",
        bagType           = "ammomaker.ammomaker_BagCasingsBottleneckMRimOld",
    },
    ["ammomaker.ammomaker_CasingStraightS"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightSOld",
        partFired         = "ammomaker.ammomaker_CasingStraightS",
        makeRecipe        = "MakeCasingsStraightS",
        recycleRecipe     = "RecycleCasingsStraightS",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightS",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightSOld",
    },
    ["ammomaker.ammomaker_CasingStraightM"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightMOld",
        partFired         = "ammomaker.ammomaker_CasingStraightM",
        makeRecipe        = "MakeCasingsStraightM",
        recycleRecipe     = "RecycleCasingsStraightM",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightM",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightMOld",
    },
    ["ammomaker.ammomaker_CasingStraightL"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightLOld",
        partFired         = "ammomaker.ammomaker_CasingStraightL",
        makeRecipe        = "MakeCasingsStraightL",
        recycleRecipe     = "RecycleCasingsStraightL",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightL",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightLOld",
    },
    ["ammomaker.ammomaker_CasingStraightSRim"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightSRimOld",
        partFired         = "ammomaker.ammomaker_CasingStraightSRim",
        makeRecipe        = "MakeCasingsStraightSRim",
        recycleRecipe     = "RecycleCasingsStraightSRim",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightSRim",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightSRimOld",
    },
    ["ammomaker.ammomaker_CasingStraightMRim"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightMRimOld",
        partFired         = "ammomaker.ammomaker_CasingStraightMRim",
        makeRecipe        = "MakeCasingsStraightMRim",
        recycleRecipe     = "RecycleCasingsStraightMRim",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightMRim",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightMRimOld",
    },
    ["ammomaker.ammomaker_CasingStraightLRim"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingStraightLRimOld",
        partFired         = "ammomaker.ammomaker_CasingStraightLRim",
        makeRecipe        = "MakeCasingsStraightLRim",
        recycleRecipe     = "RecycleCasingsStraightLRim",
        partCat           = "Pistol",
        boxType           = "ammomaker.ammomaker_BoxCasingsStraightLRim",
        bagType           = "ammomaker.ammomaker_BagCasingsStraightLRimOld",
    },
    ["ammomaker.ammomaker_HullShotgunS"] = {
        partClass         = "Hull",
        partOld           = "ammomaker.ammomaker_HullFiredShotgunS",
        partFired         = "ammomaker.ammomaker_HullFiredShotgunS",
        makeRecipe        = "MakeHullsShotgunS",
        recycleRecipe     = "RecycleHullsShotgunS",
        repairRecipe      = "RepairHullsFiredShotgunS",
        partCat           = "Shotgun",
        boxType           = "ammomaker.ammomaker_BoxHullsShotgunS",
        bagType           = "ammomaker.ammomaker_BagHullsFiredShotgunS",
    },
    ["ammomaker.ammomaker_HullShotgunL"] = {
        partClass         = "Hull",
        partOld           = "ammomaker.ammomaker_HullFiredShotgunL",
        partFired         = "ammomaker.ammomaker_HullFiredShotgunL",
        makeRecipe        = "MakeHullsShotgunL",
        recycleRecipe     = "RecycleHullsShotgunL",
        repairRecipe      = "RepairHullsFiredShotgunL",
        partCat           = "Shotgun",
        boxType           = "ammomaker.ammomaker_BoxHullsShotgunL",
        bagType           = "ammomaker.ammomaker_BagHullsFiredShotgunL",
    },
    ["ammomaker.ammomaker_CasingGrenade"] = {
        partClass         = "Casing",
        partOld           = "ammomaker.ammomaker_CasingGrenadeOld",
        partFired         = "ammomaker.ammomaker_CasingGrenade",
        makeRecipe        = "MakeCasingGrenade",
        recycleRecipe     = "RecycleCasingGrenade",
        partCat           = "Grenade",
    },

};