-- Works:

ItemTag.register("Trex:BellPepperdriedTrex")
ItemTag.register("Trex:BroccolidriedTrex")
ItemTag.register("Trex:BrusselSproutsdriedTrex")
ItemTag.register("Trex:CarrotsdriedTrex")
ItemTag.register("Trex:CauliflowerdriedTrex")
ItemTag.register("Trex:CucumberdriedTrex")
ItemTag.register("Trex:DaikondriedTrex")
ItemTag.register("Trex:EggplantdriedTrex")
ItemTag.register("Trex:OniondriedTrex")
ItemTag.register("Trex:PumpkindriedTrex")
ItemTag.register("Trex:SpinachdriedTrex")
ItemTag.register("Trex:SweetPotatodriedTrex")
ItemTag.register("Trex:TurnipdriedTrex")
ItemTag.register("Trex:ZucchinidriedTrex")
ItemTag.register("Trex:TomatodriedTrex")

ItemTag.register("Trex:CookBellPepperdriedTrex")
ItemTag.register("Trex:CookBroccolidriedTrex")
ItemTag.register("Trex:CookCarrotsdriedTrex")
ItemTag.register("Trex:CookCauliflowerdriedTrex")
ItemTag.register("Trex:CookCucumberdriedTrex")
ItemTag.register("Trex:CookOniondriedTrex")
ItemTag.register("Trex:CookPumpkindriedTrex")
ItemTag.register("Trex:CookSpinachdriedTrex")
ItemTag.register("Trex:CookSweetPotatodriedTrex")
ItemTag.register("Trex:CookTurnipdriedTrex")
ItemTag.register("Trex:CookZucchinidriedTrex")
ItemTag.register("Trex:CookTomatodriedTrex")

ItemTag.register("Trex:CookPotatodriedTrex")
ItemTag.register("Trex:PotatodriedTrex")
ItemTag.register("Trex:LunchbagchipsemptyTrex")
